//! `c2rs subsys` — the per-subsystem metric scoreboard (decision 15).
//!
//! **Offline. No toolchain, no capture, no scan.** It reads
//! `docs/whitebox/ref/` and the committed workload section census and prints;
//! that is what lets it degrade cleanly and what keeps it out of every path
//! `scripts/gate.sh` grades. See [`c2_harness::subsys`] for the separation
//! rule it obeys verbatim (`docs/FUNCTION_BYTE_MATCH.md` §0).
//!
//! `--markdown` emits the body of `docs/SUBSYS_METRICS.md`; the doc is
//! regenerated by `scripts/subsys_metrics.sh`, which is the one producer.
//!
//! `--ref-dir` exists so `scripts/subsys_metrics.sh --self-test` can point the
//! binary at a deliberately corrupted copy of the reference index and watch the
//! verifier go red. A control never seen failing is decoration (`#3336`).

use std::process::ExitCode;

use c2_harness::provenance::repo_root;
use c2_harness::subsys::{render, SUBSYSTEMS};

use crate::{Args, Arity, Spec};

static SUBSYS_SPEC: Spec = Spec {
    cmd: "subsys",
    opts: &[
        ("--markdown", Arity::Flag),
        ("--ref-dir", Arity::Value),
        ("--keys", Arity::Flag),
    ],
    requires: &[],
    max_positionals: 0,
};

fn usage() {
    eprintln!(
        "usage: c2rs subsys [--markdown] [--keys] [--ref-dir DIR]\n\
         \n\
         \x20 the per-subsystem 4-tuple for each of docs/whitebox/ref/SUBSYS.md §1's\n\
         \x20 ten subsystems: read / agreement / exercised / byte-owned, every\n\
         \x20 denominator printed beside its numerator, with a workload stamp.\n\
         \n\
         \x20 --markdown   emit the body of docs/SUBSYS_METRICS.md instead of the\n\
         \x20              console report (scripts/subsys_metrics.sh wraps this)\n\
         \x20 --keys       emit only the `subsys-metric <key> <value>` lines\n\
         \x20 --ref-dir D  read the whitebox reference index from D instead of\n\
         \x20              <repo>/docs/whitebox/ref — used by the self-test to\n\
         \x20              corrupt the input deliberately and watch VERIFY go red\n\
         \n\
         \x20 EXIT 0 verified · 1 the table no longer reproduces from the tree.\n\
         \x20 These keys are PROGRESS instruments (FUNCTION_BYTE_MATCH.md §0):\n\
         \x20 never in gate.sh's verdict, and they license no emit."
    );
}

pub(crate) fn cmd_subsys(rest: &[String]) -> ExitCode {
    let args = match Args::parse(&SUBSYS_SPEC, rest) {
        Ok(a) => a,
        Err(c) => {
            usage();
            return c;
        }
    };

    let root = repo_root();
    let r = render(&root, args.path("--ref-dir"), SUBSYSTEMS);

    if args.has("--keys") {
        for line in c2_harness::subsys::keys(SUBSYSTEMS, &r.verified, &r.census) {
            println!("subsys-metric {line}");
        }
    } else if args.has("--markdown") {
        print!("{}", r.markdown);
    } else {
        print!("{}", r.text);
    }

    if r.verified.ok() {
        ExitCode::SUCCESS
    } else {
        eprintln!(
            "\nsubsys: VERIFY FAILED with {} problem(s) — the metric table no longer \
             reproduces from this tree.",
            r.verified.failures.len()
        );
        for f in &r.verified.failures {
            eprintln!("  - {f}");
        }
        ExitCode::FAILURE
    }
}
