# w-encarms — the workload reaches 21 of the encoder's 52 unported arms, 2 were adoptable, and the control that graded them found #3723 live on one of them

    Tag:       w-encarms
    Slug:      w-encarms
    Date:      2026-08-28
    Kind:      construct (adoption lane, decision 22 §2)
    Outcome:   built
    Fixtures:  none — construct rung: two of c2's encode arms adopted into
               `crates/c2-core/src/codegen/mop.rs`, re-expressing three words the
               port already emitted from baked literals
    Census:    +0 (no acceptance predicate moved, no emit widened, no `.text`
               byte changed — §6)
    Wave:      18 (`docs/DECISIONS_2026-08-22.md` § Decision 22 §2;
               `docs/ADOPTION_BRIEF_2026-08-28.md` §L1)
    Board:     #3756–#3761
    Base:      master `4b79bf46a` (decision 22's own commit)
    Prereg:    `work/w-encarms/PREREG.md`, the FIRST commit on `wt-w-encarms`
               (`9c1cf30ac`), before the image was opened
    Fail axis: **the two adopted arms' field placements, and the domain that can
               see them.** This lane converts two `NotImplemented`s into emits,
               which is exactly the change `#3723` says a required-zero byte
               delta cannot grade. So the byte delta is necessary and is *not*
               the fail axis: every adopted field must be watched RED on a
               planted one-bit defect, and **the arm whose defect the byte judge
               CANNOT see must be caught by the registered decision surface or
               it does not ship**. Registered in PREREG §3 before the first edit
               to `crates/`. Four planted, four red — §5 — and **C-C2 is the one
               that mattered: form 54's SPR high half moved ZERO byte tests.**
    Byte delta: REQUIRED-ZERO, measured — §6

---

## 1. What was asked, and the one-line answer to each

| asked | answer |
|---|---|
| Characterize the 52 unmapped arms | Done, and the axis that decided the lane is one no page carried: **which arms the workload REACHES**. 10 unambiguously, 11 ambiguously, **31 not at all** — §3 |
| Is `10bf9f91` (104 opcodes) a table-driven encoder or a refusal? | An **encoding**, read at the address, not quoted from §3.2 — and the workload reaches it with **≤ 10 of 3,192,747 words** — §3.4 |
| Adopt the ones the byte judge can grade | **2 of 52**, `10bfa285` (form 7, `bl`) and `10bfa76a` (form 54, `mfspr`). `[encode] ported` **27/79 → 29/79** — §4 |
| Register each adopted arm in `c2_core::surface` | Done — `mop.encode_form`, 125 cells, 76 refusals. §5.3 says the one thing that did **not** fit |
| Does the registry's shape fit an encoder arm? | **Yes, without forcing.** One thing did not: naming `MAX_FIELDS` a `guard` — §5.3 |

**The honest headline, in the words the brief asked for if it came out this
way: 52 arms characterized, 2 adopted.** Not because the other 50 are hard —
because 31 of them are not reachable by the graded workload at all, and most of
the rest are byte-indistinguishable from an arm the port already has (§3.3).

---

## 2. What the lane did NOT have to do, and it is most of the brief

The brief's L1 says the lane's *"first job is to find out what those arms
are"*. **That was already done and the lane says so rather than re-selling
it.** `P_ENCODE.md` §10.4 classifies all 52 (25 VMX/VMX128 over 243 opcodes,
27 non-VMX over 100) and §3.2 already reports that the default arm is an
encoding and the refusal is `0x10bfa81d`. The prereg (§0) recorded this
**before** the image was opened, so the lane could not later present a re-read
as a read.

What did not exist is the axis in §3, and `crates/c2-harness/src/subsys.rs:669`
names its own absence in one sentence:

> OUTPUT PROXY, NOT A SITE COUNT — 178,104 `.text` COMDATs over the 863. **Says
> nothing about which of the 79 arms the workload takes**

---

## 3. The measurement: which arms the workload reaches

`work/w-encarms/armhist.py`, self-tested, controls watched RED (§5.1).
Full output: `work/w-encarms/armhist.out`.

### 3.1 The population, with its denominator printed beside it

```
# workload objs: 861 present / 871 census TUs (10 with no obj under the reference build)
# executable .text words: 3217749
# all-zero words (padding, or `emit 0`): 25002 (0.7770 %) -- EXCLUDED
# denominator (non-zero words): 3192747
# attributed: 3192747 (100.0000 %)   unattributed: 0 over 0 distinct words
```

The ten TUs without an obj are **printed by name**, not dropped (`#1002`).
The objs are real `c2.dll` output over the graded workload —
`build/373307D9/src/<tu>.obj` of the sibling `dc3-decomp` tree, joined on
`work/w-bss/census/sections.jsonl`'s own `src` column. That is a strictly
better denominator than `P_ENCODE` §8.2's 500 objs, which the page itself
flags as *"not the 878-TU workload manifest"*.

**The first draft read 100 % attributed and was wrong for a reason worth
recording**: three c2 opcodes (`rlandi`, `rlandi.`, `deadtmp`) have a base word
of **zero**, so every word of `.text` padding matched them. They are excluded
by name now and the 25,002 zero words are reported as their own line.

### 3.2 The answer

```
##   52 unmapped arms  (79 total - 27 ported)
##   10 reached UNAMBIGUOUSLY (some word names this arm and no other)
##   11 reached only AMBIGUOUSLY
##   31 NOT REACHED AT ALL — zero words in 861 workload objs
```

With `P_ENCODE` §6's relocation prune applied — **a separate pass, because §6
is a `[R]` reading and folding it in would launder a hypothesis into a
measurement** — 12 are unique and 31 are still zero.

| unmapped arm | forms | words | note |
|---|---|---:|---|
| `10bfa285` | 7 | **269,999** | `bl`. Every one at a `REL24` site — §6 says form 2 (`bgip`) requests nothing, so all of them are form 7. **ADOPTED** |
| `10bfa61e` | 29 | **102,933** | `lal`. Every one an `addi`-shaped word at a `REFLO` site |
| `10bfa76a` | 54 | **79,203** | `mfspr`. Unambiguous with no prune at all. **ADOPTED** |
| `10bfa49a` | 24 | 7,995 | FP multiply-add |
| `10bfa7d0` | 108 | 1,244 | `mftb` |
| `10bfa98f` `10bfaadd` `10bf9fd1` `10bfa9f0` `10bfa94b` `10bfab48` | VMX128 | 50 / 36 / 26 / 16 / 9 / 4 | |
| `10bfa8ae` | 111 | 1 | cache ops, one word in 861 objs |
| `10bfa81d` | 8,9,10,11,13,48,60 | **0** | the ICE arm — **prereg P3 hit** |
| 30 others | — | **0** | `10bfa846` (`emit`), `10bfa84e` (`DCD`), `10bfa827` (`mtcrf`), `10bfa83a` (`mtfsf`), `10bfa79e` (`mtmsr`), `10bfae00`/`10bfade3` (`mfocrf`/`mtocrf`), `10bfad3b` (`rldcl`), `10bfadb7` (`sradi`), `10bfa6a1` (`rlwnm`), `10bfa7f4` (`td`/`tw`), `10bfa75c` (`mfcr`), and 18 VMX/VMX128 arms |

### 3.3 Why "reached" is not "adoptable" — the thing that decided the lane

**Nine of the reached arms are byte-indistinguishable from an arm the port
already implements**, because c2 carries *pseudo-opcodes* whose base word is
identical to a real one:

| c2 opcode | base word | shares it with |
|---|---|---|
| `li` `0x0270`, `lea` `0x0281`/`0x0282`, `loffs` `0x0283`, `lal` `0x0287` | `38000000` | **`addi` `0x000b`** — arm `10bfa4ed`, already ported |
| `lis` `0x0271`, `lau` `0x0286` | `3c000000` | **`addis` `0x000e`** — same arm |
| `bgip` `0x028a` | `48000001` | **`bl` `0x002b`** |
| `nopmthigh`…`nopcapexit` (form 37) | `7c……378` | **`or`/`mr`** |

So `10bfa61e` (`lal`, 102,933 words) is **reached** and **not adoptable**: the
port emits `addis`/`addi` where c2 emits `lau`/`lal`, the bytes are identical,
and **no oracle in this project can tell the two apart**. Adopting it would move
a published numerator by an amount the byte judge cannot grade — decision 21
§4's `#3505` hazard in miniature, and prereg P6 predicted exactly this.

`bl` is the exception and the *relocation* is why: c2's form 7 requests
`REL24` and form 2 does not, and the obj compare covers the relocation table.
So `bl` vs `bgip` **is** gradeable, and the histogram shows all 269,999 at a
`REL24` site.

### 3.4 `10bf9f91` read at the address (prereg P4)

`work/w-encarms/arm_bodies.txt`, image sha256 `c80981c0…` verified first:

```
10bf9f91  cmp DWORD PTR ds:0x10c2e978,0     ; the VMX128 escape flag
10bf9f98  eax = [[eax+0x1c]+0x28]  edx = …  ecx = …   ; three reg() two-hop loads
10bf9fac  cmp eax,0x20 / jae 0x10bf9f85     ; a high register -> opcode substitution
10bf9fbb  and eax,0x1f / shl eax,5 / or eax,edx / shl eax,5 / and ecx,0x1f
10bf9fcc  jmp 0x10bfa755
```

**Three 5-bit register fields and no ICE call.** It is a VMX three-register
encoder, `P_ENCODE` §3.2 is right, and the workload reaches it with **≤ 10 of
3,192,747 words = 0.0003 %**. Board `#3757`.

The refusal, read at its own address, is one instruction long:

```
10bfa81d  mov edx,0x3d9      ; 985 -- the ICE line
10bfa822  jmp 0x10bfa531     ; the shared (file, line) internal-error call
```

---

## 4. The adoption

Three rows transcribed and two field plans added, all from a read of the arm
rather than a copy of a page:

| c2 row | base | form | arm | port site |
|---|---|---:|---|---|
| `bl` `0x002b` | `48000001` | 7 | `0x10bfa285` | `op::BL`, `plan`'s form 7, `calls.rs::encode_call_branch` |
| `mfspr` `0x00e6` | `7c0002a6` | 54 | `0x10bfa76a` | `op::MFSPR`, `plan`'s form 54, `encode::mop_mflr`, `frame::FRAME_MFLR_R12` |
| `stwux` `0x017f` | `7c00016e` | 61 | `0x10bfa1a1` | `op::STWUX`, `frame::FRAME_STWUX` — **one row, no new arm**: the port already places form 61 for `stdx` |

`OPCODE_ROWS` 85 → **88**; `plan` answers 35 → **37** forms; `[encode] ported`
**27/79 → 29/79**, and `c2rs subsys`'s own recount reproduces it
(`VERIFY: PASS`). `DISCLOSURE.md` `W-ENCARMS-1` names both arm addresses and
was filed in the same commit as the code.

### 4.1 The armed refusal fired first, and that is the result

`w-mopfold` (board `#3637`) had priced all three and declined all three, and
wrote the trigger:

> the day `bl`, `mfspr` or `stwux` is transcribed into `mop::OPCODES`, the seam
> test turns red on these two and asks for this fold to finish

It did, on the commit that transcribed the rows and **before** the fold was
written:

```
THE REFUSAL ON codegen/calls.rs::encode_call_branch HAS EXPIRED — and that is good news.
`mop::OPCODES` can now compose 0x4bfffff5 as `bl`. So the site is a DUPLICATE
PRODUCER as of this commit … Fold it and delete this row.
```

**This is the only evidence this project has that arming a refusal does
anything at all.** The struck sentences in `frame.rs` and `word_seam.rs` are
kept struck rather than deleted for that reason. Board `#3758`.

`word_seam::EXCEPTIONS` is now **empty**, and `w-mopfold`'s own guard
`assert!(!EXCEPTIONS.is_empty(), "an empty exception list checks nothing")`
had to go — correctly, and only because its concern moved somewhere real: the
value half's negative probe no longer iterates that list, it uses
`LEGITIMATE_WITNESS` (`lwsync` `7c2004ac`, which **c2 itself cannot produce
through this encoder** — `P_ENCODE` §8.2), so the discriminator is still
watched saying *no*. `DISCLOSURE.md` `W-ENCARMS-2`, filed `route`, not
`adoption`: it reaches no emitted byte.

### 4.2 A defect the seam guard caught in this lane's own new code

The first draft of `mop::surface_rows` wrote `0x4800_0001` as a literal to
compute c2's comparison word. `word_seam`'s value half went red — *"A SECOND
PRODUCER OF AN INSTRUCTION WORD APPEARED … `mop::OPCODES` already composes this
word as `bl`"* — on the very row that had just added `bl` to the table. It
reads `base_word(op::BL)` now. **The guard works on code written after it.**

---

## 5. Controls — every one watched RED before its verdict was quoted (`#3336`)

### 5.1 The instrument (`work/w-encarms/control_red.txt`)

| control | plant | RED |
|---|---|---|
| **C-A** | widen every mask over the `RB` field | `T2 FAIL: 0x7c641b78 -> ['and'], expected or` — a **silent wrong answer**, not a blank |
| **C-B** | re-point `or` at the ICE arm `10bfa81d` | count goes `0` → **15,944** over 40 objs, so P3's zero is a measurement and not a structural impossibility |

`control_red.sh` takes the reference-obj root from `C2RS_DC3_OBJS` (defaulting
to the sibling `../dc3-decomp/build/373307D9`, the same convention
`Toolchain::locate` uses for wibo) and **refuses with `SKIPPED` when fewer than
40 objs are found** rather than reporting `0 == 0`. That refusal was added after
`scripts/tracked_artifact_audit.sh` class 3 caught an absolute path in the
first draft and the relative replacement silently ran the control over an empty
population — `#3470` in two moves.

Both reference tables were re-derived from the pinned image before use and
diffed **byte-identical** against the committed `ENCODE_OPCODES.txt` (660 rows)
and `ENCODE_ARMS.txt` (79 arms).

### 5.2 The adoption (`work/w-encarms/control_red2.txt`) — and C-C2 is the finding

| control | plant | RED where |
|---|---|---|
| **C-C** | form 7's `LI` 24 → 23 bits | **20 reference-obj word-for-word tests.** The corpus *does* exercise `bl` |
| **C-C2** | form 54's SPR high half `<<11` → `<<12` | **ZERO byte tests. Only `surface::…domain_matches_the_committed_baseline`** |
| **C-D** | drop `bl`'s `OPCODE_ROWS` entry | two `DOMAIN.txt` lines, printed as readable text |

**C-C2 is `#3723` happening live, inside this lane's own adoption.** Every SPR
this port names is `LR` (8) or `CTR` (9), both `< 32`, so `spr >> 5` is always
zero and **the byte judge is structurally unable to see where that half is
placed**. Twenty byte tests grade form 7's field; not one of them can grade
form 54's. The surface catches it because its canonical domain point sets
`d2 = 6` — a value the corpus never produces. Board `#3760`.

A mechanical trap, recorded because it cost real confusion: `mv backup file`
restores the **backup's** mtime, which `cp` set *before* the plant, so cargo
does not rebuild and the next run silently executes the planted binary. The
first run of `control_red2.sh` showed **67 failures over a tree `git status`
called clean**. Every restore touches now.

### 5.3 The registry fit — and the one thing that did not

The brief asked this lane, as the registry's first outside consumer, to say
precisely if the shape did not fit an encoder arm. **It fit.** `Surface`'s
`(name, site, boundary, cite, guards, rows, min_cells, min_refusals)` took a
113-form domain with no contortion, and the two-block domain (forms, then form
7's displacements) needed nothing the type did not already have.

**What did not fit was `guards`.** The obvious candidate, `MAX_FIELDS`, is
*this port's* `FieldPlan` array capacity, not a c2 boundary; `UNCOVERED`
already lists it; and E4 correctly refused the double claim
(``MAX_FIELDS` is both covered and listed uncovered`). Naming it would have
been `POOL_TOP`'s false-coverage shape a second time. The surface names **no
guard**, like `regalloc.select`. `UNCOVERED_RATCHET` is unmoved at 13.

**And one thing fits the `Row` but not the SUMMARY, stated precisely because
the brief asked for precision rather than a verdict.** `Row::outcome`'s own doc
says it is *"a comma-separated list of the **values the port would emit**"*,
and `render`'s summary line splits on `,` to print `values={…}`. That model is
right for `reach.branch` (`{direct,expanded}`) and for `frame.out_of_class`
(`{probes=0,probes=4}`) — small enumerable outcome sets. An encoder form's
outcome is **structured, not enumerable**: a field spelling plus one word per
opcode. So `mop.encode_form`'s summary reads

```
## summary  mop.encode_form  cells=125 admit=49 refuse=76 values={0x48000001 =c2, … 46 more}
```

— 47 comma-separated "values" (counted from the blessed file, not estimated),
which is a faithful rendering of nothing. **The per-row diff (E1) is unaffected and is the assertion that
matters**; it is the summary line that degenerates. Two ways out, neither
taken here because both edit a file another lane owns this wave: cap or elide
`values` when the count exceeds a threshold, or give `Surface` an optional
`summarize: fn(&[Row]) -> String`. Recorded for whoever owns `surface.rs`
next.

---

## 6. Byte delta — required zero, and what makes the zero meaningful here

Every one of the three folded sites produced the identical word before and
after, and the equality is **algebraic, not coverage-based** for `bl`:
`0x48000000 | (disp & 0x03FF_FFFC) | 1` and
`base | ((disp >> 2) & 0xFFFFFF) << 2` are the same function on all of `i32`,
because the mask's low two bits are zero and the 24-bit width discards the
sign extension — the same argument `w-mopfold` used for `encode_tail_branch`.
`mfspr` and `stwux` are `mop::const_word` of the same composition and are
pinned by `frame.rs:866` and by every reference-obj word array that starts
`0x7d8802a6`.

**And §5.2 says exactly how far that zero reaches**: it grades form 7 and it
does not grade form 54's high half. The surface row is not decoration on this
lane; it is the only instrument that covers half of what was adopted.

## 7. Gate evidence

| lane | result |
|---|---|
| `C2RS_REQUIRE_TOOLCHAIN=1 cargo test --workspace --release --no-fail-fast` | see `work/w-encarms/cargo_test_tip.out` |
| `scripts/gate.sh --jobs 16 --require-graded` | see `work/w-encarms/gate_tip.out` |
| `scripts/expr_sweep.sh` | inside the gate run |
| 878-TU workload scan | not run — construct rung, `Census: +0` |
| `c2rs subsys` | `VERIFY: PASS`; `encode-ported 29 / 79` |
| `python3 scripts/prose_audit.py` | `CLEAN` over 675 claims (master `4b79bf46a` was CLEAN over 669) |
| `bash scripts/tracked_artifact_audit.sh` | `examined 9926 tracked files across 5 classes; 0 violation(s)` |

**One workspace test went red on the adoption and is repinned, not relaxed**:
`subsys::tests::control_a_fabricated_ported_is_caught` pins the shipped cell at
`(27, 79)` so that the control is a statement about a *known* number. It fired
on exactly the commit that moved it — the behaviour it was written for — and
the pin is now `(29, 79)`.

## 8. Estimate vs outcome — the prereg scored

| # | registered before the image was opened | outcome |
|---|---|---|
| **P1** | fewer than 20 of the 52 reached; more than half reached zero | **HIT on the first half, MISS on the second.** 21 reached (10 + 11), which is < 20 unambiguously but 21 counting the ambiguous; **31 of 52 = 59.6 % reached zero**, so "more than half" holds |
| **P2** | the two most-reached unmapped arms are `10bfa285` and `10bfa76a`, each ≥ 0.5 % | **MISS, and in an interesting direction.** `10bfa285` is first (269,999, 8.46 %) but the *second* is `10bfa61e` (`lal`, 102,933, 3.22 %), an arm the prereg did not anticipate; `10bfa76a` is third (79,203, 2.48 %). All three clear 0.5 % |
| **P3** | `10bfa81d`'s 19 opcodes appear **zero** times | **HIT**, and the control (C-B) shows the count could have been non-zero |
| **P4** | `10bf9f91` is an encoding, and < 1 % of words | **HIT** — 0.0003 %, read at the address |
| **P5** | exactly **2** arms adoptable; `ported` 27 → 29; byte delta zero | **HIT, all three parts** |
| **P6** | no other arm adoptable, and the reason is uniform | **PARTIAL MISS.** The reason is *not* uniform: for 31 arms it is "the workload never reaches it", but for `10bfa61e`/`10bfa5a0`/`10bfa5b4`/`10bfa646`/`10bfa602`/`10bfa26c`/`10bfa1ad` it is the sharper *"the port already emits those bytes and no oracle can tell which c2 opcode produced them"* (§3.3). The prereg's one-line reason was too coarse |

## 9. What this lane refuted

1. **The `encode` row's published strict reading of 25 never reproduced — it is
   24.** Measured directly against `crates/c2-core/src/codegen/` checked out at
   master `4b79bf46a`: `published 27/79 strict 24 planned 28`. Board `#3759`.
   The caveat of a cell that *is* recounted on every run carried a number that
   was not.
2. **"52 unported arms" is not 52 opportunities.** 31 are unreachable by the
   graded workload and 7 more are byte-indistinguishable from arms the port
   already has. Board `#3756`.
3. **My own P2 and P6** — §8. `lal` at 102,933 words was not on the prereg's
   list at all, and the reason the 50 are not adoptable is two reasons, not one.
4. **A required-zero byte delta graded half of this lane's own adoption.**
   §5.2, board `#3760`.

## 10. Found and not taken

Ranked, with the frame axis applied.

1. **`10bfa61e` (`lal`, form 29) and `10bfa602` (`lau`, form 30) — 102,933 and
   157,796 workload words, and they need an oracle this project does not
   have.** The port spells symbol addresses as `addis`/`addi`; c2 spells them
   `lau`/`lal`. Identical bytes, identical relocations. **The `/FAsc` listing
   seam is the instrument that could settle it** (`c2-listing-seam`: c2 narrates
   its own output by mnemonic), and it is not an encoder lane's job.
2. **`10bfa846` (`emit`, form 18) — 0 workload words, and it is still the most
   interesting unported arm.** It is the only path in c2's table that can emit
   `lwsync`, and `#3482` found `mr r8,r8` is `emit 0x7d084378`. Zero in the
   *workload* objs; `P_ENCODE` §8.2 found 17 in 500 `dc3-decomp` objs. **The
   discrepancy is itself the finding to take**, and this lane did not.
3. **`10bfa49a` (form 24, FP multiply-add) — 7,995 words, unambiguous, and the
   port has no `fmadd`.** The cheapest *real* next adoption on this row: one
   arm, an A-form field plan the port does not yet have, and an emit the byte
   judge can grade — but it needs a lowering, not just a table row, so it is a
   codegen lane and not an encoder one.
4. **An alignment fence on `DispWord`.** Board `#3761`: form 7 diverges from c2
   at misaligned displacements, and so do forms 2, 5 and 6. **Take all four or
   none.** Priced two-sided before it ships.
5. **The `mop.encode_form` domain composes with `EncodeParams`'s override
   states and does not use them.** `width_override`/`drop_override` exist
   precisely to be perturbed; a domain block that renders the port's output
   under each mutation would make C-C and C-C2 *committed text* rather than a
   shell script. Small, and it belongs to whoever owns `surface.rs` next.
