#!/usr/bin/env python3
"""GRID-N — the ARITY axis of `guard_chain_shared_tail`, and nothing else.

The shipped fence says, in its own words, that with one witness there is no way
to tell *"the `lis` is after the second rotate step"* from *"the `lis` is three
steps before the last"*.  Both fit `vswprnc` at six formals.  This grid varies
**arity alone** — same guards, same store, same two arms, same tail — and reads
the `lis`'s position out of each obj.

STRUCTURAL BLIND SPOT of this grid, stated here rather than discovered later:
it varies arity and holds the guard indices, the store width, the callee count
and the literal values fixed.  It therefore cannot see any rule in which the
`lis`'s position depends on something *other* than the rotate's length.
"""
import sys

# (name, n_formals, store_type, store_elem)
CELLS = [(f"n{n}", n) for n in (3, 4, 5, 6, 7, 8)]

TMPL = """// GRID-N cell {name}: {n} formals -> a {nargs}-argument call.
// Generated by work/w-vsnprnc/gen_arity.py; arity is the ONLY axis.
typedef unsigned int size_t_;
extern "C" {{
int *_errno(void);
typedef int (*outfn_t)(void);
extern int helper(outfn_t{helper_types});
extern int outfn(void);
extern void _invalid_parameter_noinfo(void);

int f({formal_decls}) {{
    int result;
    if (p2 == 0 || p0 == 0 || p1 == 0) {{
        *_errno() = 0x16;
        _invalid_parameter_noinfo();
        return -1;
    }}
    result = helper(outfn{call_args});
    if (result < 0) {{
        *p0 = 0;
    }}
    if (result != -2) {{
        return result;
    }}
    *_errno() = 0x22;
    _invalid_parameter_noinfo();
    return -1;
}}
}}
"""


def formal_type(i):
    # p0 is the store target; p1/p2 are the other two guarded formals and must
    # be unsigned (a signed zero-compare is `cmpwi`, not `cmplwi`).
    if i == 0:
        return "char *"
    if i in (1, 2):
        return "size_t_ "
    return "void *"


def gen(name, n):
    formals = ", ".join(f"{formal_type(i)}p{i}" for i in range(n))
    helper_types = "".join(f", {formal_type(i)}" for i in range(n))
    call_args = "".join(f", p{i}" for i in range(n))
    return TMPL.format(name=name, n=n, nargs=n + 1, formal_decls=formals,
                       helper_types=helper_types, call_args=call_args)


if __name__ == "__main__":
    out = sys.argv[1]
    for name, n in CELLS:
        with open(f"{out}/{name}.cpp", "w") as fh:
            fh.write(gen(name, n))
        print(f"{name}.cpp  {n} formals, {n+1} call args")
