#!/usr/bin/env python3
"""Insert board rows #1157-#1166 at their NUMERIC position, and fail hard rather
than skip if the anchor is not exactly where it is expected."""
import pathlib, re

ROWS = r"""| **1157**<sub>w-f23</sub> | **F2 IS PAID AND ADMITS EXACTLY ZERO ADDITIONAL WORKLOAD BODIES** | **MEASURED at both ends of the 878-TU scan.** A sub-object's *address* is now admitted as a stored value, producing `IlOp::AddrOf`, and the emitter fails closed on it — `parse_simple_gpr_run`'s `[Load, v, StoreInd, ..]` cannot match a **four**-op group, no arm of `store_leaf_text`'s walk matches it, and `straightline` refuses `AddrOf` by name. Graded: `f2_leaf_g8`, `f2_run_addr2` and `f2_run_addr_lit` all go `vocab-gap → codegen-gap` with *"sub-object address feeding arithmetic; out of class"*. And the workload gain is **`fn_in_class` 711,477 → 711,477** | +0 bodies; 3 grid cells move; `fn_blockers` total unmoved at 1,751,966 | rungs/2026-08-08-w-f23.md §3; `work/w-f23/grid/f2_leaf_g8/`, `f2_run_addr2/`, `f2_run_addr_lit/` | **`w-heap` §6.2 said F2 alone converts nothing and the prereg registered it; the measured answer is not "little" but ZERO.** F2's whole value is as F3's prerequisite. The discriminating control is `f2_ctrl_load`, whose IL differs by **exactly the `30`** and which emits `lwz`+`stw` where the address emits one `addi` — if F2 were tried before `parse_load_value` that cell would be a wrong-bytes emit inside an accepted class, so the ordering is pinned by a test over both whole captured segments |
| **1158**<sub>w-f23</sub> | **`w-heap`'s ITEMS 2 AND 3 ARE ONE REFUSAL — F3's SECOND HALF *IS* #844, because `IlFunction` HAS NO CARRIER FOR A COMPOSITION** | **MEASURED by building the reader half and hitting the wall.** `ops` and the call fields (`tail_call`, `framed_call`, `call_seq`) are **alternatives** `codegen::select` tries in a fixed order with `store_leaf_text` **first**, so a function carrying a run's ops *and* any call field emits the run and **silently drops the `bl`** — a complete, plausible, wrong body. So `shape_to_function` returns `None` for `BodyShape::StoreRunCall`, by name rather than with `..` | price 5 → 5, but items 2+3 collapse to one seam with two ends | rungs/2026-08-08-w-f23.md §4.2; `crates/c2-il/src/func/bundle.rs`; `leaf_store.rs::f3_reads_the_store_run_then_call_composition_and_the_bundle_refuses_it` | **This is board #232's exact mechanism, refused in advance instead of shipped and discovered 255 commits later.** The consequence for planning: a lane that pays #844 gets F3's second half free; a lane that "pays F3" without #844 has bought a **census key**. This rung bought the census key and says so — `w-heap` §5's table lists the two as independent rows and they are not |
| **1159**<sub>w-f23</sub> | **THE RESIDUE IS NOW A NUMBER: 8 IL BODIES, 3 OF THEM EMITTED, OUT OF A 402,148-ROW FALL-THROUGH KEY** | **MEASURED** by differencing `fn_blockers` and `emit_blockers` over the whole 878-TU scan at both ends. `expr-op-0x27` **402,148 → 402,140**; the new `:eof` key `store-run-call-no-emitter-carrier` **0 → 8**. Emitted: **22,377 → 22,374** and **0 → 3**. **Exactly two rows differ**; both totals (1,751,966 and 130,579) are unmoved, so no third family absorbed anything | 8 bodies · 3 emitted · 2 keys moved · 0 other keys moved | rungs/2026-08-08-w-f23.md §4.3; `work/w-f23/scan_{base,tip}.jsonl` | The key is **directly sizeable** because every body under it is grammar-complete by construction (`Block::at_end`, so the `:eof` is the true statement and no second blocker hides behind it). The eight TUs are `Character.cpp`, `CharacterTest.cpp`, `ClipDistMap.cpp`, `ClipGraphGen.cpp`, `UsbMidiGuitar.cpp`, `Movie.cpp`, `Rnd_Xbox.cpp`, `SIVideo.cpp` — and `xboxheap.cpp` is **not** among them (#1160) |
| **1160**<sub>w-f23</sub> | **`xboxheap.cpp`'s SHIPPED SPELLING IS BLOCKED BY THE REFERENCE BIND ALONE, AND THE BIND IS TWO READER OBLIGATIONS RATHER THAN ONE** | **MEASURED on the target's own `.ex` at the workload's flags, decoded by hand against its eleven source lines.** Line 8 `auto& listHead = mListHead;` is a store into a **LOCAL**: `26 11 0a · b9 <this> · 33 …08 27 · 32 <ptr> 4b` — and it is the **only** F2 site in that spelling. Lines 9–10 then use the local's token `11 0a` as the store **BASE**, which `parse_store_stmt` refuses because the base must be a formal. The **direct** spelling (`work/w-f23/grid/f2_xboxheap_direct/`) reaches the new key; the shipped one does not | 2 obligations: a `26` local as a store DESTINATION, and that local as a store BASE with its own symbol | rungs/2026-08-08-w-f23.md §5.1; `work/w-f23/il/xboxheap/` | **#839 confirmed load-bearing from the reader's end.** `w-heap` #1128 measured that the two spellings emit **different bodies** — both producers swap and one store moves; this row measures that the reader already separates them at exactly that point, and that collapsing them to one production would emit the other body's words. That is why the shipped F3 test is built on the **direct** segment and labelled as such |
| **1161**<sub>w-f23</sub> | **THE CONSERVATIVE F2 RUN GATE IS DEFENSIBLE AND IT HIDES THE TARGET — reversed, with the reversal's evidence** | **MEASURED, and this row exists because the first choice was wrong.** F2 first shipped refusing *a run that mixes an address with a literal*, on #836/#868's mixed-kind grounds. `xboxheap`'s run is **one literal and two addresses**, so that gate refused the whole run and **F3 could never fire on its own target** — the cell kept printing `expr-op-0x27` after the production landed. Reversed: the four ALLOC/ORDER clauses protect `order::schedule` and `alloc::allocate`, and **neither is reached** on a run containing an address because `parse_simple_gpr_run` declines one group earlier | `f2_run_addr_lit` vocab-gap → codegen-gap; 1,576 sweep cases at 0 mismatch **either way** | rungs/2026-08-08-w-f23.md §3.3 | **Admitting is the fail-closed direction here, and that is measured rather than argued**: an `AddrOf` group is four ops where every group the emitter models is three, so the models the clauses protect are never consulted. The clauses still apply to the LITERALS, so they only ever refuse more. **Do not re-derive the conservative gate** — a lane reading only the shipped code will |
| **1162**<sub>w-f23</sub> | **THE ZERO-OFFSET ADDRESS STAYS REFUSED, AND IT IS A RULE RATHER THAN CAUTION** | **BY CONSTRUCTION, and graded.** `AddrOf { off: 0 }` emits **nothing**, so `s->p = &s->m;` with `m` at offset 0 is the same bare `stw` the plain pointer value emits — a shape the formal path was byte-graded on rungs ago. Cell `f2_leaf_g0` stays `vocab-gap` after the rung | 1 cell; 1 pinning test | rungs/2026-08-08-w-f23.md §3.2; `leaf_store.rs::f2_leaves_the_zero_offset_address_refused_because_c2_emits_no_addi_there` | Admitting it would put a **second production over one fact** — `GAPS.md` §6's "one fact, two locators" — and it is the same fact `w-gen` §5 reports from the other side: the **44** cells of `88-store-run-call.py` that are already `Port=Match` are the offset-0 ones, where the address *is* `this` and there is no `addi` at all |
| **1163**<sub>w-f23</sub> | **F3's REGIME GATE IS #1129's, AND THE READER MAKES IT STRICTER THAN THE SENTENCE** | **SHIPPED AND TESTED.** `w-heap` §3.2's *"the call's argument setup is empty, or writes no register the run reads"* is expressed as **every slot `i` already holds `params[i]`, receiver included**, so the call emits no move. That is stricter than the prose because the reader sees an IL argument **spelling**, not a register: a member load, a literal or a converted value in a slot refuses, since none can be shown to leave `r3` alone without a capture each | slot-exact; axes D/E refuse through the receiver walk rather than a second gate | rungs/2026-08-08-w-f23.md §4.1; `leaf_store.rs::try_parse_store_run_call` | The call is read through the **same four locators** `try_parse_member_tail_call` uses (`eat_callee_push`, `eat_receiver_this`, `eat_call_token`, `eat_call_args`) — a private copy of the receiver walk is `GAPS.md` §6 instance #9's drift, and the `volatile` gate `eat_receiver_this` inherits is the thirteenth live wrong-bytes emit on this project. The **receiver is not an argument**, which is the lane's registered loss (P0) landing: slot 0 had to be *constructed* |
| **1164**<sub>w-f23</sub> | **THE 878-TU SCAN'S `codegen-gap` CANNOT MOVE ON A READER WIDENING THIS SIZE, BECAUSE THE PARTITION IS PER TU** | **MEASURED — the lane's own registered MISS (P6).** `codegen-gap` stayed **0** and `vocab-gap` stayed **861** while 8 functions moved keys, because a TU is `vocab-gap` if **any** of its functions fails to decode, and every one of the 861 still carries another undecodable body. The motion is visible at TU level only on **single-function** TUs, which is what the grid's cells are — three of them flip | 0 TUs move · 8 functions move · 3 single-function cells flip | rungs/2026-08-08-w-f23.md §6; `work/w-f23/scan_tip.log` | **A frontier metric that cannot register a real payment is a metric that will read "unpaid" through several correct lanes.** The per-function `fn_blockers`/`emit_blockers` difference is what did register it, and it is already in the scan JSONL — so the instrument exists and the headline number simply is not it. Quote both, or the next reader-side lane looks like it did nothing |
| **1165**<sub>w-f23</sub> | **`AddrOf` NOW HAS TWO PRODUCERS IN `c2-il`, AND THE `30` IS WHAT KEEPS THEM APART** | **CHECKED before writing, per the peer-key hygiene rule, and then pinned.** `AddrOf` had exactly **one** producer (`leaf_addr.rs`'s address leaf) and now has two, in two different productions over two different *positions* — the returned value and the stored value. They cannot collide: the address leaf is anchored on the `41` result, the store value on the `32`, and F2 is tried **after** `parse_load_value`, which owns the `30` | 2 producers · 1 discriminator byte · 2 whole-segment control cells | rungs/2026-08-08-w-f23.md §2; `leaf_store.rs::f2_admits_a_member_address_as_a_stored_value_and_the_30_still_separates_the_load` | Concurrent lane **w-align16** owns `crates/c2-core/coff/`'s alignment promotion and the `.gl` alignment reader; this lane touches neither. `work/w-splice/peerkeys.py` over both scan JSONLs reads **`FAMILIES THAT VANISHED: 0`** with every count identical — `fndiff-` 44,463, `fnbyte-calltarget` 85,000, `fnbyte-noeffect` 50,628, `in-` 8,766,355. The duplicate-walk hazard is **checked**, not assumed |
| **1166**<sub>w-f23</sub> | **A WIDENING THAT CONVERTS NOTHING CONVERTS NOTHING IN THE SWEEP EITHER — 44 / 1,532, UNMOVED, TWICE** | **MEASURED.** `88-store-run-call.py` graded alone at its own `/Ox /GS- /c` after F2 and again after F3: `checked=1576 mismatches=0 graded=1576 ungraded=0` both times, and the port's own verdict split is **44 `Port=Match` · 1,532 `Port=NotImplemented`** at both — identical to `w-gen` §5's published baseline | 1,576 × 2 runs · 0 mismatch · 0 ungraded · 0 verdicts moved | rungs/2026-08-08-w-f23.md §6.1; `work/w-f23/tally88.sh` | **`mismatches=0` alone does not distinguish RIGHT from SILENT**, which is why `w-gen` published the split and why this lane re-derived it rather than quoting the sweep line. The reading is honest and slightly deflating: the 1,532 refusals are still refusals, and what this rung changed is **which** refusal and where it is recorded. The number to watch on the next lane is this split, not the mismatch count |
"""

p = pathlib.Path('docs/BOARD.md')
s = p.read_text()
anchor = '| **1143**<sub>w-gen</sub> |'
i = s.index(anchor)                      # IndexError -> fail hard, never skip
j = s.index('\n', i) + 1
assert s[j:j + 4] == '\n---\n' or s[j:].startswith('\n---'), (
    'row 1143 is no longer the last row of its table; re-check the numeric position'
)
for n in range(1157, 1167):
    assert f'| **{n}**' not in s, f'row #{n} already exists — renumber, do not overwrite'
s = s[:j] + ROWS + s[j:]
p.write_text(s)
print('inserted rows 1157-1166 after 1143')
