#!/usr/bin/env python3
"""board_rows.py — insert lane w-seam's ten rows (#866-#875) into docs/BOARD.md.

`docs/BOARD.md` is hand-maintained prose, so this exists only so the insertion is
re-runnable and reviewable rather than a shell heredoc; it is idempotent and
refuses if the rows are already there.
"""
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                    "..", ".."))
P = os.path.join(ROOT, "docs", "BOARD.md")

OPEN_ANCHOR = "| **161** | The **emit predicate**, fitted black-box"
OPEN_ROWS = """| **866**<sub>w-seam</sub> | **THE LEAF SCHEDULE AND ALLOCATION TRANSFER UNCHANGED INTO A FRAMED BODY** — `order::schedule` and `alloc::allocate` are fitted entirely on leaf bodies, and the same store run inside a framed body emits the STRING-IDENTICAL run text | **MEASURED over 96 cells at the workload's own flags, 96 graded, 0 out-of-regime.** GRID T: `P2` (two trailing calls, 9 frame words) **12/12 IDENT**, `R` (`this` live across the call) **12/12 IDENT**. GRID T2, a fresh holdout on the axes GRID T holds fixed — six formals, mixed `stb`/`sth`/`stw`/`std` widths, **two base symbols**, a `lis`+`ori` wide literal, a wide literal beside a `li`, a run of **seven**, a non-void trailing call — **34 IDENT / 2 DIFFER**, and both differs are #870. The `mr r31,r3` is **additive**: inserted without moving one other word | rungs/2026-08-06-w-seam.md §3; `work/w-seam/gridt.py`, `gridt2.py`, `gridt.out`, `gridt2.out` | **OPEN because the composition is licensed and not built** — see #871 for why. The verdict is printed TWO ways side by side, IDENT (raw) and PLAN (store base canonicalised), because a callee-saved rename is neither a refutation nor a licence and reporting one of them alone would score it as whichever the lane wanted. Board **#839**'s reference binding is held FIXED across every kind of every configuration: this asks whether a plan transfers, not what the plan is |
| **867**<sub>w-seam</sub> | **WHERE THE `mr r31,r3` SITS — `stores_before_mr = nprod − 1 + min(u, 2)`**, measured through two holdouts and deliberately NOT shipped | **MEASURED. GRID M 24/24/24 graded, 19 hit / 5 MISS; GRID M2 18/18/18 graded, 18 hit / 0 MISS.** The registered hypothesis H-mr (the copy is placed by `layout_slots` as one more producer) is **refuted** as registered — `layout_slots` puts producer `i` before store slot `min(i,u)` and mispredicts the 0-producer and 2-producer cells. The first fitted successor, `nprod − 1 + u`, died on its own holdout with **every miss at a leading unproduced run of 3 and every one off by exactly one**, which names the observable: `store_order`'s `u` is `min(2, #unproduced)`, not the raw leading run. The corrected form survives leading runs of 4, 5 and 6 | rungs/2026-08-06-w-seam.md §4; `work/w-seam/gridm.py`, `gridm2.py` | **NOT SHIPPED, and that was registered in ADDENDUM 1 before the rule existed.** The shape it serves is a value live across a call, which needs the mixed-kind allocation **#868** leaves refused, so an emitter for it would be unreachable. It also reproduces `xboxheap.cpp`'s own body (`nprod` 2, `u` 2 → 3 stores before the copy). `D11-argcall`'s cell puts the copy at index 0 against a predicted 1 and is **outside the regime rather than a miss** — that run does not transfer at all (#870) |
| **870**<sub>w-seam</sub> | **THE TRANSFER BOUNDARY — a trailing call that takes an ARGUMENT breaks the run, and c2 parks the object in a VOLATILE** | **MEASURED, 2 of 36 GRID T2 cells, and prereg T5 named this row as the one that could lose before it did.** `gx(u)` instead of `gx()` moves three things at once: the object goes to **`r10`, a volatile** (or `r31` with a return) because `r3` is wanted for the argument; the **store base changes mid-run** (`stw 11,0(3)` then `stw 11,4(10)`); and the constant pool **re-ranks** to `r11`/`r9` where the leaf takes `r11`/`r10`. `D12-nonvoid` is the control that says the axis is the *argument* and not the return type — an `int`-returning call whose result is stored after the run transfers at IDENT in both framed kinds | rungs/2026-08-06-w-seam.md §3.2; `work/w-seam/gridt2.out` | **This is the gate any framed seam owes**, and it must be syntactic so census and gate cannot disagree. None of the three effects is expressible in `alloc::allocate`'s inputs, which know nothing about a call. So #866's statement is not *"a run in a framed body keeps its leaf plan"* — it is *"iff nothing between the run and the epilogue competes for the run's registers"* |
| **871**<sub>w-seam</sub> | **#322 IS A PREREQUISITE OF #844, NOT A NEIGHBOUR OF IT — every composition #844 names is INVISIBLE to `fnbyte-differs`** | **MEASURED off the scan's own line: `partial by shape: tail 7098 · seq 2150 · framed 123 · cond-pair 4` — 9,375 emitted functions the port already ACCEPTS and nothing grades.** `fnbytes.rs` maps `Selected::{Tail, Framed, Seq, CondPair}` to `FnByte::Partial` by construction, and its module doc says why: reconstructing them in the harness is *"the one way to inflate FBM"*. A store-run-before-a-call seam adds its **whole population** to that bucket, so the standing alarm would read **0 whether the seam were right or wrong** | rungs/2026-08-06-w-seam.md §6; `work/w-seam/PREREG.md` ADDENDUM 2 §A2.4; `crates/c2-harness/src/gap/fnbytes.rs` `complete_body` | **Board #232's shape with the alarm REMOVED rather than merely unwatched** — #232 was a live wrong emit that survived 255 commits under a green gate that could not represent it. This row is the reason w-seam shipped no emitter, and the decision is in the prereg addendum **before** any emitter existed rather than argued afterwards. It also re-prices #322: it is not an FBM nicety, it is the only thing on the #844 path that widens the warranty without widening the accept surface |
| **872**<sub>w-seam</sub> | **A STORE RUN *AFTER* THE CALL DOES NOT TRANSFER — and it is a RULE, not a refusal** | **MEASURED, 12 of 12 GRID T cells graded, 0 out-of-regime: 6 PLAN-only, 6 DIFFER, 0 IDENT.** Every value that must survive the `bl` goes to a **callee-saved** register in `r31`, `r30`, `r29` order — `CallSeq::saved`'s own order — and the volatile pool then re-ranks over what is left. `C6-xboxheap` reads `addi 30,3,64 ; li 11,0 ; stw 30,64(31) …` against the leaf's `addi 11,3,64 ; li 10,0 ; stw 11,64(3) …`. `C1-formals` needs **three** saved GPRs and crosses `FrameLayout::needs_gpr_helper` into `__savegprlr_29` | rungs/2026-08-06-w-seam.md §3.3; `work/w-seam/gridt.out` | **Prereg T2 is this lane's one outright MISS, and it missed twice in the same direction**: it predicted transfer *and* gave itself an escape hatch (*"out of regime on the formal-storing configurations"*). Neither happened — c2 declines nothing and compiles all twelve. The registered claim assumed a boundary where there is a rule, which is the useful form of a miss |
"""

DEC_ANCHOR = "| **720**<sub>w-tu4</sub> ⚠"
DEC_ROWS = """| **868**<sub>w-seam</sub> | **THE NARROW ALLOCATION LIFT — lifting `codegen::alloc`'s mixed refusal only where clause 1 decides with NO TIE** | **REFUTED on 12 of 36 graded cells, and the refusal STANDS.** The sub-case was registered before the grid existed: two producers, one register-derived and one single-word constant, `reg.uses > const.uses` **strictly**, so no tie-break, no kind bonus, and neither refuted key (w-next's, w-alloc2's `H-self`) is consulted. It looks like pure clause 1 and therefore like conservatism. Three spellings × six use-count gaps × two body kinds: `addi-interior` **12/0/0**, `add` **12/0/0**, `slwi` **0/12/0** — the constant takes `r11` on every `slwi` cell, and **at a use-count advantage of THREE as flatly as at one** | **36 selected / 36 reached / 36 GRADED / 0 out-of-regime**, 12 MISS; `xboxheap.cpp` does **not** convert, TU match 10 → 10 | rungs/2026-08-06-w-seam.md §5; `work/w-seam/grida.py`, `grida.out`; `codegen/alloc.rs` `the_strict_use_count_subcase_is_refused_too` | **There is no threshold to narrow around**, and both body kinds agree cell for cell so a frame does not rescue it either. The separating axis is the **SPELLING**, which `ProducerKind::RegisterDerived` cannot represent — the fourth row after #836/#837/#839 to land there. **The `slwi` spelling was in the grid because the prereg required it**: w-alloc2's `F4-shift-r2k1` was already on record, and a grid without it would have come back 24/24 and licensed a widening wrong on a third of its own domain |
| **869**<sub>w-seam</sub> | **A LONE TRAILING VOID CALL IS TAIL-CALLED EVEN BEHIND A STORE RUN — so `<run> g();` is not a framed body at all** | **MEASURED, 12 of 12 cells, frame word count 1.** `void f(S* s,int u,int v){ s->f0=7; gx(); }` is `li r11,7 ; stw r11,0(r3) ; b gx` — one branch, no `mflr`, no `stwu`, five sections. The framed claim is carried by the two-call cells (`P2`, frame word count 9) instead | 12 cells re-classified; the framed row of #866 is `P2`, not `P` | rungs/2026-08-06-w-seam.md §3.1; `work/w-seam/gridt.out` | **Visible only because the frame-word count is PRINTED beside every verdict rather than asserted.** A grid that trusted the source shape would have published twelve framed cells that are not framed and rested the headline on them. Prereg T1 is scored **PARTIAL** for exactly this — right about the bytes, wrong about the shape it was measuring. The consequence for #844 is concrete: a framed store run needs **two calls, or one value live across one call** |
"""

DONE_ANCHOR = "| **700**<sub>w-convert</sub> |"
DONE_ROWS = """| **873**<sub>w-seam</sub> | **AN INSTRUMENT SCORED A REAL REFUTATION AS `OUT OF REGIME` — #843's shape, third lane running** | **CAUGHT and REPAIRED; `work/w-seam/gridt2.out.v1` is kept as the record.** The first GRID T2 run read `36 selected / GRADED 26 / IDENT 26 / DIFFER 0 / out-of-regime 10` and looked like a clean sweep. Two of those ten were the instrument declining to see an answer that was on the line: **`D11-argcall` genuinely does not transfer** and was scored out of regime *because* "the stores do not share one base" — which is the finding (#870); and **`D12-nonvoid` does transfer**, with the base check broken by the *result* store `stw 3,8(31)` sitting **after the `bl`** and never part of the run. `D5`/`D6` are honestly two-base runs, identical leaf and framed. After repair: **36 / 36 / 36 / 0 out-of-regime, 34 IDENT, 2 DIFFER** | rungs/2026-08-06-w-seam.md §3.2; `work/w-seam/gridt2.py` docstring, `gridt2.out.v1` vs `gridt2.out` | Three repairs, each a rule: **split the body at the first branch** so a post-call statement is never mixed into the run; **compare raw text whenever either side has more than one base**, reporting IDENT or DIFFER but never PLAN; and **never let a base check turn a difference into a silence**. STATUS trap 5 inside a grid, and the deliverable was hiding in the counter that was supposed to be the safety net |
| **874**<sub>w-seam</sub> | **A MUTATION HARNESS'S RESTORE TRAP DESTROYED THE LANE'S OWN UNCOMMITTED WORK** | **HAPPENED, recorded rather than quietly redone.** `work/w-seam/mutate.sh` restores with `git checkout -- <file>` in an `EXIT` trap. Its first run aborted on a bad anchor — the `encode_blr()` line appears at the end of **both** `scheduled_gpr_run_text` and `store_leaf_text`, so the `count == 1` assertion failed — and `set -eu` fired the trap, which reverted **both tests the lane had just written and not yet committed** | 2 tests lost and rewritten; 0 measurements lost | rungs/2026-08-06-w-seam.md §7.4; `work/w-seam/mutate.sh`, `patch_store.py` | Two mitigations, both applied: **commit before mutating**, and keep the addition in a **re-runnable file** (`patch_store.py`) rather than in a shell transcript. A restore trap whose blast radius is *everything uncommitted in these files* is a hazard every lane using this pattern inherits, and this project's mutation harnesses all use it |
| **875**<sub>w-seam</sub> | **NO SEAM SHIPPED, AND THE DECISION IS IN THE PREREG RATHER THAN IN THE WRITE-UP** | **DECLINED in advance.** `work/w-seam/PREREG.md` ADDENDUM 2 §A2.4 states the two blockers and the conclusion — the allocation half is refused (#868), and every composition #844 names is invisible to the standing alarm (#871) — and it was committed **before** any emitter existed. The lane's whole `crates/` diff is two tests and one doc block: **all 62 `gap-metric` lines byte-identical at both ends**, checked by `diff` of two sorted files, TU match 10 → 10, `mismatch` 0, `fnbyte-differs` 0 | **174 cells selected / 174 reached / 174 GRADED / 0 out-of-regime** across five grids; workspace tests 909 → **911**, targets 27 at both ends; gate **18/18 PASS**, sweep 16,614 graded / 0 mismatch, cross 81,517 graded / 0 mismatch | rungs/2026-08-06-w-seam.md §1, §6, §7 | **"Zero conversions is better than one wrong emit" is what this looks like when it binds.** The composition itself is *licensed by measurement* (#866) and its three parts already exist and are graded — `codegen::frame`, `scheduled_gpr_run_text`, `calls::call_seq_text`. What is missing is, in order: **#322**, then a parser production, then #870's argument gate, then the spelling axis. Recorded so the next lane inherits an ordered list rather than a green light |
"""


def main():
    s = open(P, encoding="utf-8").read()
    if "w-seam" in s:
        print("rows already present — nothing to do")
        return 0
    for anchor, rows in ((OPEN_ANCHOR, OPEN_ROWS),
                         (DEC_ANCHOR, DEC_ROWS),
                         (DONE_ANCHOR, DONE_ROWS)):
        if s.count(anchor) != 1:
            print("anchor %r appears %d times — refusing" % (anchor[:40],
                                                             s.count(anchor)))
            return 1
        s = s.replace(anchor, rows + anchor, 1)
    open(P, "w", encoding="utf-8").write(s)
    print("BOARD.md: 10 rows added (#866-#875)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
