#!/usr/bin/env python3
"""build_diagnostics.py — generate docs/whitebox/c2_diagnostics.tsv.

PROVENANCE NOTE — this one is the *cleanest* artifact in docs/whitebox/. It is
not disassembly: it reads the RT_STRING resource table of `1033/clui.dll`, which
is the text the compiler prints. That is observable output of the black box, the
category README.md already blesses. It lives here only because it was produced
by the same lane and is useless without the map.

Why it matters: c2.dll itself contains NO diagnostic text — only error *numbers*.
Every 'C1007'/'C1083' hunt in the binary must therefore search for the immediate
(0x3EF, 0x43B), never the string. This table is the number->text dictionary that
makes that possible.

Usage: build_diagnostics.py <clui.dll> <out.tsv>
Columns: id  code  text
  id   = RT_STRING resource id (== the numeric part of the diagnostic code)
  code = C<id> if the id is in a compiler-diagnostic range, else '-'
"""
import sys, struct


def resources(d):
    e = struct.unpack_from("<I", d, 0x3C)[0]
    coff = e + 4
    nsec, = struct.unpack_from("<H", d, coff + 2)
    oszopt, = struct.unpack_from("<H", d, coff + 16)
    opt = coff + 20
    res_rva, res_sz = struct.unpack_from("<II", d, opt + 96 + 8 * 2)
    secs = []
    so = opt + oszopt
    for i in range(nsec):
        n, vs, va, rs, pr = struct.unpack_from("<8sIIII", d, so + 40 * i)
        secs.append((va, vs, pr, rs))

    def r2o(r):
        for va, vs, pr, rs in secs:
            if va <= r < va + max(vs, rs):
                return pr + (r - va)
        return None

    base = r2o(res_rva)

    def walk(off, path):
        n_name, n_id = struct.unpack_from("<HH", d, off + 12)
        out = []
        for i in range(n_name + n_id):
            nm, offs = struct.unpack_from("<II", d, off + 16 + 8 * i)
            ident = ("name#%x" % (nm & 0x7FFFFFFF)) if nm & 0x80000000 else nm
            if offs & 0x80000000:
                out += walk(base + (offs & 0x7FFFFFFF), path + [ident])
            else:
                drva, dsz = struct.unpack_from("<II", d, base + offs)
                out.append((path + [ident], drva, dsz))
        return out

    return walk(base, []), r2o


def main():
    d = open(sys.argv[1], "rb").read()
    ents, r2o = resources(d)
    msgs = {}
    for path, drva, dsz in ents:
        if path[0] != 6:            # RT_STRING
            continue
        block = path[1]             # 1-based block of 16 consecutive ids
        o = r2o(drva)
        end = o + dsz
        for k in range(16):
            if o + 2 > end:
                break
            ln, = struct.unpack_from("<H", d, o)
            o += 2
            if ln:
                s = d[o:o + 2 * ln].decode("utf-16-le", "replace")
                msgs[(block - 1) * 16 + k] = s
                o += 2 * ln

    with open(sys.argv[2], "w") as f:
        f.write("# Diagnostic text from 1033/clui.dll's RT_STRING table — the number->text\n")
        f.write("# dictionary for c2.dll, which itself holds only the numbers. NOT disassembly:\n")
        f.write("# this is text the compiler prints, i.e. observable output. Generated by\n")
        f.write("# docs/whitebox/scripts/build_diagnostics.py; do not hand-edit.\n")
        f.write("id\tcode\ttext\n")
        for i in sorted(msgs):
            t = msgs[i].replace("\t", "\\t").replace("\n", "\\n").replace("\r", "\\r").rstrip("\x00")
            f.write("%d\tC%d\t%s\n" % (i, i, t))
    sys.stderr.write("messages: %d (ids %d..%d)\n" % (len(msgs), min(msgs), max(msgs)))


if __name__ == "__main__":
    main()
