#!/usr/bin/env python3
"""build_strings.py — generate docs/whitebox/c2_strings.tsv.

PROVENANCE: output is DISASSEMBLY-DERIVED (literals lifted out of a third-party
binary, plus their cross-references). See docs/whitebox/DISCLOSURE.md before
adopting any value from it into crates/.

Merges two independent sources so neither one's blind spots survive:
  1. Ghidra's *defined* strings and their cross-references (strings.tsv from
     ExportFlat.java) — has xrefs, but misses literals Ghidra did not type.
  2. A raw scan of the file image for printable ASCII runs — no xrefs, but
     misses nothing. (Ghidra missed e.g. ".bss"; the raw scan catches it.)

Usage: build_strings.py <export-dir> <binary> <out.tsv>
Columns: addr(VA)  section  len  nxref  xref_funcs  source  value
  source = ghidra | raw | ghidra+raw
"""
import sys, os, struct

MINLEN = 4


def sections(data):
    e = struct.unpack_from("<I", data, 0x3C)[0]
    coff = e + 4
    nsec, = struct.unpack_from("<H", data, coff + 2)
    oszopt, = struct.unpack_from("<H", data, coff + 16)
    opt = coff + 20
    imgbase, = struct.unpack_from("<I", data, opt + 28)
    so = opt + oszopt
    out = []
    for i in range(nsec):
        n, vs, va, rs, pr = struct.unpack_from("<8sIIII", data, so + 40 * i)
        out.append((n.rstrip(b"\0").decode(), imgbase + va, vs, pr, rs))
    return imgbase, out


def main():
    exp, binp, outp = sys.argv[1], sys.argv[2], sys.argv[3]
    data = open(binp, "rb").read()
    imgbase, secs = sections(data)

    def off2va(o):
        for n, va, vs, pr, rs in secs:
            if pr <= o < pr + rs:
                return va + (o - pr), n
        return None, None

    rows = {}  # va -> [section, len, nxref, xrefs, source, value]

    # source 1: Ghidra defined strings (carries the xrefs)
    with open(os.path.join(exp, "strings.tsv")) as f:
        f.readline()
        for line in f:
            p = line.rstrip("\n").split("\t")
            if len(p) < 6:
                continue
            va = int(p[0], 16)
            sec = next((n for n, v, vs, pr, rs in secs if v <= va < v + vs), "?")
            rows[va] = [sec, p[1], p[2], p[4], "ghidra", p[5]]

    # source 2: raw printable-ASCII scan of the file image
    cur, start = [], None
    def flush():
        if start is not None and len(cur) >= MINLEN:
            va, sec = off2va(start)
            if va is not None:
                s = "".join(cur)
                if va in rows:
                    rows[va][4] = "ghidra+raw"
                else:
                    rows[va] = [sec, str(len(s) + 1), "0", "", "raw", s]
    for i, b in enumerate(data):
        if 0x20 <= b < 0x7F:
            if start is None:
                start = i
            cur.append(chr(b))
        else:
            if b == 0:
                flush()
            cur, start = [], None
    flush()

    with open(outp, "w") as o:
        o.write("# DISASSEMBLY-DERIVED — generated by docs/whitebox/scripts/build_strings.py.\n")
        o.write("# Literals from c2.dll plus the functions that reference them. Do not paste\n")
        o.write("# any value into crates/ without a docs/whitebox/DISCLOSURE.md entry.\n")
        o.write("addr\tsection\tlen\tnxref\txref_funcs\tsource\tvalue\n")
        for va in sorted(rows):
            r = rows[va]
            o.write("%08x\t%s\t%s\t%s\t%s\t%s\t%s\n" % (va, r[0], r[1], r[2], r[3], r[4], r[5]))
    sys.stderr.write("strings: %d (ghidra-only %d, raw-only %d, both %d)\n" % (
        len(rows),
        sum(1 for r in rows.values() if r[4] == "ghidra"),
        sum(1 for r in rows.values() if r[4] == "raw"),
        sum(1 for r in rows.values() if r[4] == "ghidra+raw")))


if __name__ == "__main__":
    main()
