#!/usr/bin/env python3
"""Append this lane's board rows to docs/BOARD.md, after the previous lane's
explicit unminted-range declaration."""
import os

rows = r"""
| **2780**<sub>w-phase7b</sub> | **`Bindings::per_record`'s 1:1 REQUIREMENT IS UNSATISFIABLE ON THE INPUT for 842 of 871 graded TUs — the missing body-start offsets are ABSENT from `.gl`, not unframed** | **MEASURED** at one dc3 stamp (`a8cb9ca6`) by `IlBundle::gl_body_start_coverage` and cross-checked by a raw search of the whole `.gl` for each `.ex` split point's `80 <LE32>` spelling. `src/system/decomp_pch.cpp` **622 of 1,312**, `src/system/math/vec.cpp` **373 of 811**; **690** and **438** offsets absent byte-for-byte; **0** split points below `0x80` where a short form could hide one | 842 of 871 TUs · **952,723** segments that can bind to NO record · control `src/system/utl/EncryptXTEA.cpp` **5 of 5** and all 23 matches `n of n` | rungs/2026-08-10-w-phase7b.md §3, §3.2 · #918 · #2621 · #2754 | **This is the first binding instrument in the project that reports on the INPUT rather than on a walk.** `fn_names`, `emit-bound`/`emit-gate-segments`, the census's own binding and `gate_cause` all describe a reader, so their answer always reads as a repair address; this one can say there is nothing to repair. `present` is a deliberate OVER-count (any `80 <LE32>` counts), so `total − present` is a LOWER bound |
| **2781**<sub>w-phase7b</sub> | **`emit-predicate-worth 124` INTERSECTS THE BINDABLE POPULATION AT ZERO, and `A∧B∧C` intersects it at 27 of 27** | **MEASURED** as a set join by name (`c2rs gap --factors-tsv` × the coverage set), not as a count comparison. `match` 23 of 23 · `A` 28 of 28 · `A∧B∧C` **27 of 27** · FRONTIER **4 of 4** · `B∧C` 27 of 151 · **`reach-pool` 0 of 124** · `D∨E` 23 of 25 | 871 graded TUs · **29** full-coverage · 842 partial · 7 null | rungs/2026-08-10-w-phase7b.md §3.3 · #213 · #345 · w-bcgap §5 | The 27-of-27 agreement is what makes the 0-of-124 readable: coverage and factor **A** are all but co-extensive, so the population a perfect emit predicate is priced over is EXACTLY the population whose `.gl` cannot describe its `.ex`. `w-bcgap` measured the best model buying 110 of 124 and converting **nothing**; this is why |
| **2782**<sub>w-phase7b</sub> | **`CEILING.md` §2.5's *"Both need factor A alone"* is REFUTED — a PERFECT factor A, in today's `PortC2::build`, converts neither TU** | **DERIVED** from #2780 + #2781 at this tree. An emit set can only be applied in front of `functions()`; behind it the gate has already refused, and the gate's requirement has no solution on either TU's input. `w-vec` §10.5 established that both are refused *before* A is a question; this establishes that A is not sufficient even in the limit | 2 TUs · 0 conversions at A = perfect · the `+2` of §2.5 is unreachable through this path | rungs/2026-08-10-w-phase7b.md §5 · #213 · #361 · rungs/2026-08-09-w-vec.md §10.5 | **`\|D∨E\| = 13` (now 25) is a codegen fact and STANDS; its ROUTE does not.** The replacement sentence: a perfect factor A is worth 0 conversions until the emit set can be applied in front of the parse gate, and that is true on 842 of 871 TUs. The frontier's 27 is raised by an emit-set model **plus a selective binding**, and only the second is a clause |
| **2783**<sub>w-phase7b</sub> | **`codec::gl_offset_framed` IS A VALUE TEST WEARING A POSITION TEST'S DOCSTRING — `gl[o-5] == 0x10` pins the PRECEDING field to `[0x1000, 0x10FF]`** | **MEASURED** by relaxing that one byte to `PREV < 0x10000` (`work/w-phase7b/frame.py`): framed defined records go **31 → 612** on `decomp_pch.cpp` and **36 → 369** on `vec.cpp`, with **0** false positives on the second and **1** on the first. `PREV` is a rising per-record number — 0x1005…0x1015 across `EncryptXTEA.cpp`'s five records, 0x184b… on `vec.cpp`, 0x19a0… on `decomp_pch.cpp` | 2 TUs + 1 control · 31 → 612 · 36 → 369 · **0 conversions** | rungs/2026-08-10-w-phase7b.md §3.2, §10 item 2 | The docstring says it locates the field *"by position within the record, not by what its value happens to be"*; that is true of the offset field and false of the one in front of it, which is why the same reader is **5 of 5** on a 2.5 KB `.gl` and **31 of 1,312** on a 124 KB one. **NOT SHIPPED**: it converts nothing (the totality requirement still fails) and the walk is also `bind::defined_name_set`, where a widening is a tightening (#2622/#2623) |
| **2784**<sub>w-phase7b</sub> | **`vec.cpp`'s EMIT SET IS NAMEABLE FROM ITS OWN `.gl` — both bodies, at exact `.ex` split points** | **MEASURED** off this lane's capture: `??0Vector3@@QAA@MMM@Z` body-start **98,922** and `??0Vector4@@QAA@MMMM@Z` body-start **105,430**, both `4F 1F` split points, both spelled in `.gl` | 2 of 2 emitted bodies present · 438 of the other 809 absent · `fnbyte-exact` **2 of 2** | rungs/2026-08-10-w-phase7b.md §0, §4.2 · #2380–#2395 (T1) | **This reclassifies `w-vec`'s D2 from a ratio to a QUANTIFIER.** The gate does not lack the information it needs about `vec.cpp`; it insists on information about the **438 bodies c2 discards**. The repair is a SELECTIVE binding, and its warrant is an emit set — so D-V1 cannot be paid before factor A, and factor A cannot be applied after the gate |
| **2785**<sub>w-phase7b</sub> | **THE TWO `projection-divergence` TUs DO NOT SHARE A MECHANISM — one is expensive, the other is unreachable on today's reader** | **DERIVED** per TU at this tree, six mechanisms for `decomp_pch.cpp` and seven for `vec.cpp`, sharing exactly ONE row (the COMDAT `.rdata` writer). `decomp_pch.cpp`'s emit set is **∅** — the obj has zero `.text`, `emit-emitted` **0** — and its licence would need every one of 1,312 bodies accounted for against a `.gl` that names **622** | 6 + 7 mechanisms · **1** shared · 3 new (D-P1, D-P2, D-V1) | rungs/2026-08-10-w-phase7b.md §4 · rungs/2026-08-09-w-vec.md §4 · #2503 | A page that prices them as one item is wrong about both. `decomp_pch.cpp` needs a **new acceptance path** in front of the gate whose licence the input cannot supply (**47.4 %** of its bodies are accountable); `vec.cpp` needs a **selective binding** whose licence the input can |
| **2786**<sub>w-phase7b</sub> | **`HeadsetXferEffect.cpp` AND `MeterEffect.cpp` ARE THE ONLY TUs OUTSIDE `A∧B∧C` WHOSE BINDING IS SATISFIABLE, and no lane has looked at either** | **MEASURED** as a set difference: full coverage is **29** TUs = the 23 matches + the FRONTIER 4 + these two. `HeadsetXferEffect.cpp` reads **16 of 16** (A=0 B=0 C=0), `MeterEffect.cpp` **13 of 13** (A=1 B=0 C=0) | 29 full-coverage · 23 match · 4 frontier · **2 unexamined** | rungs/2026-08-10-w-phase7b.md §3.4, §10 item 1 | They are the entire population where a factor-**B** or factor-**C** rung could convert something **without** a binding change. Flagged, not priced — this lane did not capture either |
| **2787**<sub>w-phase7b</sub> | **`.ex` CARRIES NO PER-BODY EMIT MARKER — the optimization word splits 684/127 and 1,092/220 against emit sets of 2 and 0** | **MEASURED** over all 2,123 segments of the two TUs (`work/w-phase7b/exscan.py`). The three bytes after the opt word are `4f 20 80` on **2,123 of 2,123** | 811 + 1,312 segments · 2 distinct opt words · emit sets **2** and **0** | rungs/2026-08-10-w-phase7b.md §10 item 4 | A negative recorded so the next lane does not re-run it: the emit decision is **not** a field on the body. It has to be reconstructed from roots and reachability, which is what `w-root`'s M3A does in Python and what no `crates/` emitter does at all |
| **2788**<sub>w-phase7b</sub> | **`emit_data_obj` EXCLUDES COMDAT BY AN EXPLICIT CLAUSE, so the 4-byte `.rdata` group both target TUs need has 0 of 5 emitters** | **RE-DERIVED** at this tree. `coff::data::CH_DATA_BASE`'s own doc: *"the COMDAT form (`\| 0x1000`, Selection 2) is not emitted here"*. The group is 4 bytes, `ff ff ff ff`, `sel=2`, `chars 0x40301040`, one external, placed after **both** `.XBLD$W` watermarks | 1 group · **0 of 5** emitters · shared by both TUs | rungs/2026-08-10-w-phase7b.md §4.1 D-P3, §4.2 D-V6 · rungs/2026-08-09-w-vec.md §2.1 | The only row the two prices have in common, and it converts **neither** on its own — `decomp_pch.cpp` still needs D-P1/D-P2 in front of it and `vec.cpp` still needs D-V1 and the `.text`+`.data`+`.bss` composition around it |
| **2789**<sub>w-phase7b</sub> | **BOTH REFERENCE OBJS ARE SMALLER THAN THE FIGURES ON RECORD — dc3 has moved again** | **MEASURED** at dc3 `a8cb9ca6`: `decomp_pch.obj` **901 B** (recorded 933), `vec.obj` **1,791 B** (recorded 1,819), and `.debug$S` is 148 B rather than 176 | 2 objs · −32 B and −28 B · 4th dc3 stamp in five lanes | rungs/2026-08-10-w-phase7b.md §2 · #2392 | Every byte figure in that section is this lane's own capture. **State a full stamp**: dc3 `a8cb9ca639df2e938553ae24200307fa7a31abce`, `src/` clean, two dirty tracked files outside `src/` |
| **2790**<sub>w-phase7b</sub> | **`body-out-of-class` FIRES ON 848 OF 848 REFUSED TUs AT THIS MASTER — no `.gl` or binding repair alone crosses the gate anywhere in the workload** | **MEASURED** over all 878 rows, `gate_causes` parsed as SETS. First causes: `gl-stop-26-introduced` **819**, `drectve-not-boilerplate` **13**, `bind-record-count-ne-segments` **12**, `body-out-of-class` **4**. `gl-stop-name-not-mangled` is **absent**, as #2751 left it | 848 refused · 6 distinct cause SETS · `body-out-of-class` in **848** of them | rungs/2026-08-10-w-phase7b.md §1 · #2505 · #2506 · #2751 | `w-vec` #2505 measured this at 851 of 851 one master ago and it survives the `w-decouple` merge unchanged in kind. The consequence for this lane is direct: the framing widening of #2783 could not have converted anything even if the totality requirement were met |
| **2791**<sub>w-phase7b</sub> | **THE FULL-COVERAGE SET IS A CEILING ON THE ACCEPTANCE PATH AND NOT ON THE PROJECT — 29, and the distinction is load-bearing** | **DERIVED.** 29 bounds what `IlBundle::functions()` → `Bindings::per_record` can ever bind. `dyninit_tu()` is a second path that does not use it, and a third — an emit-set arm in front of the gate — is exactly what #2785's D-P1 names | 29 of 871 · 2 existing acceptance paths · 1 named and unbuilt | rungs/2026-08-10-w-phase7b.md §3.4 · #2782 | Recorded as a caveat ON this lane's own headline, because *"29 is the ceiling"* is the sentence this row exists to prevent. It is a ceiling on **one gate**, and the whole point of #2782 is that the gate is the thing to replace |
| **2792**<sub>w-phase7b</sub> | **A DIAGNOSTIC-ONLY LANE, MEASURED AT FOUR LEVELS WITH DIRECTIONS: 0 verdicts moved, 0 byte triples moved, 262 keys `diff`-identical, 0 fixtures moved at either mode** | **MEASURED**, base and tip each scanned by its OWN binary (base `a39a8bfc…`, kept before the first edit; tip `37d33ff6…`). 878 TUs by full `src` path (#2667), per-TU `(exact, differs, refused)` as a SET comparison with the sums printed underneath, and 369 fixtures × `/O1` and `/Ox` × both binaries | 878 · 0 changed (0 toward, 0 away) · 0 triples · 262 keys · 369 × 2 × 2, mismatch **0** everywhere | rungs/2026-08-10-w-phase7b.md §6 · #2409 · #2667 · #2533 | The Level-2 row is a per-TU set comparison **and** a sum, because a lane that moved one TU +1 and another −1 prints an unchanged sum. The `/Ox` half is not optional: `w-biquad` (#2533) shipped a wrong emit at offset 760 that only a both-modes by-name fixture scan saw |
| **2793**<sub>w-phase7b</sub> | **A GREEN `cargo build --release` IS NOT A COMPILED TREE — the release profile does not compile `cfg(test)` bodies** | **OBSERVED** in this lane. A mechanical edit adding a struct field to every `TuResult` initializer matched **two indentations inside ONE struct literal** and wrote the field twice; `cargo build --release --workspace` reported success with the file already broken, and `rustc` raised `E0062` only under `cargo test` | 1 duplicated field · release build **green** · test profile **red** | rungs/2026-08-10-w-phase7b.md §9.1 | Near-miss rather than a refusal, and recorded because the failure mode is generic: any lane that verifies a mechanical edit with `cargo build` and defers `cargo test` has an untested window in which the tree does not compile. The mitigation is one line — **run `cargo test` before the first measurement, not after it** |
"""

tail = """> **`#2794`–`#2819` are minted by nobody and are FREE.** Lane `w-phase7b` was
> allocated `#2780`–`#2819` and used fourteen (`#2780`–`#2793`). The unused
> twenty-six are recorded as explicitly unminted rather than left to be inferred
> from a gap.
"""

here = os.path.dirname(os.path.abspath(__file__))
path = os.path.join(here, "..", "..", "docs", "BOARD.md")
board = open(path).read()
assert "`#2763`–`#2779` are minted by nobody" in board, "anchor missing"
assert "2780" not in board.split("w-decouple")[-1][:200], "already appended?"
open(path, "w").write(board.rstrip("\n") + "\n\n" + rows.strip("\n") + "\n\n" + tail)
print("appended 14 rows")
