#!/bin/sh
# w-inlfence — the FIXTURE neutrality scan. `$1` is the binary, `$2` the flags
# file, `$3` the output stem under work/w-inlfence/.
#
# The list is regenerated by the caller AFTER the last fixture is written and
# checked with `wc -l` against `ls fixtures/cpp/*.cpp | wc -l` — w-fltret §9.2's
# third unnamed refusal was a 313-entry list that omitted its own `_neg` file.
set -eu
bin="$1"; flags="$2"; stem="$3"
here=$(cd "$(dirname "$0")/../.." && pwd)
exec "$bin" gap \
    --list "$here/work/w-inlfence/fixall.txt" \
    --flags-file "$flags" --cwd "$here" --jobs 12 \
    --jsonl "$here/work/w-inlfence/$stem.jsonl" \
    > "$here/work/w-inlfence/$stem.out" 2> "$here/work/w-inlfence/$stem.err"
