// f3_b2_c0_dthis_fctor — w-heap GRID F3, generated by gridgen.py. DO NOT EDIT.
struct BE { BE* mNext; BE* mPrev; };
struct H {
    H(unsigned int a, unsigned int b, H* q);
    BE* Alloc(unsigned int);
    H* mFreeHead; H* mUsedHead; BE mListHead; unsigned int mSize; unsigned int mCount;
};
H::H(unsigned int initSize, unsigned int size, H* q) {
    mSize = size;
    q->mFreeHead = this;
    mUsedHead = this;
    Alloc(initSize);
}
