// f3_a3_c0_dthis_fdiscardint — w-heap GRID F3, generated by gridgen.py. DO NOT EDIT.
struct BE { BE* mNext; BE* mPrev; };
struct H {
    void m(unsigned int a, unsigned int b);
    BE* Alloc(unsigned int);
    H* mFreeHead; H* mUsedHead; BE mListHead; unsigned int mSize; unsigned int mCount;
};
void H::m(unsigned int initSize, unsigned int size) {
    mSize = size;
    mFreeHead = this;
    mUsedHead = this;
    BE* r = Alloc(initSize); (void)r;
}
