// f3_a3_c0_dfree_fvoid — w-heap GRID F3, generated by gridgen.py. DO NOT EDIT.
struct BE { BE* mNext; BE* mPrev; };
struct H {
    static void s(H* h, unsigned int a);
    H* mFreeHead; H* mUsedHead; BE mListHead; unsigned int mSize; unsigned int mCount;
};
extern void g0();
void hf(H* h, unsigned int u, unsigned int v) {
    h->mSize = v;
    h->mFreeHead = h;
    h->mUsedHead = h;
    g0();
}
