// f2_g8_hdirect_iself_j3 — w-heap GRID F2, generated by gridgen.py. DO NOT EDIT.
struct BE { BE* mNext; BE* mPrev; };
struct H {
    H(unsigned int a, unsigned int b);
    H* mFreeHead; H* mUsedHead; BE mListHead; unsigned int mSize; unsigned int mCount;
    BE mSecond;
};
H::H(unsigned int initSize, unsigned int size) {
    mCount = 0;
    mListHead.mNext = &mListHead;
    mListHead.mPrev = &mListHead;
    mSecond.mNext = &mListHead;
}
