#!/usr/bin/env python3
"""Insert w-park's board rows after #1888, and its unminted-remainder note."""
ROWS = """| **1920**<sub>w-park</sub> | **THE LITERAL PATH'S IN-PLACE CLAUSE IS A STATEMENT ABOUT THE *TAIL* SITE, AND IT WAS BEING ASKED AT THE SEQUENCE SITE TOO** | **DONE.** `lit_arg_tail_call` required every non-literal slot to be the formal already in that argument register. At a tail call that is right — there is no park and no prologue, and the argument setup *is* the body. Inside a framed call sequence behind a guarded early return there IS a park, and `park_in_class` already decides the permutation on the same `slot_sources` view in which a literal slot is a **fixed point**. `slot_sources`' own doc says the two views are shared *"so the two cannot disagree about which slots move"* — **they could not disagree; they were never asked.** `ArgSite::{Tail,Sequence}` makes the axis explicit: 9 call sites pass `Tail`, 1 passes `Sequence` | GRID-P **45 cells, 45 graded, 31 `match`, 0 `mismatch`**; base→tip **16 moved `vocab-gap`→`match`, 0 the other way**, as a SET by name | rungs/2026-08-08-w-park.md §3 · `shapes::calls::ArgSite` · GRID-P `work/w-park/gridg.py` | This is the **third** item on the list board #1444 published as two. `w-memcpy` §1 had already found it (*"between them sits `call-arg-lit-permuted`"*) and left it, because the locator is shared with the tail-call form; `ArgSite` is what makes it a change to one class instead of two |
| **1921**<sub>w-park</sub> | **THE WIDENING'S WORKLOAD REACH IS EXACTLY ZERO, AND IT SHIPS ANYWAY** | **MEASURED, both directions.** Over the 878-TU scan **all 251 `gap-metric` keys are byte-identical** base to tip and the per-TU verdict set is unchanged — 0 only-in-base, 0 only-in-tip, 0 changed, compared by name over all 878. The function census is +0. So the class it opens has **no instance in the dc3 workload that is not blocked behind something else**, and every byte of its evidence is manufactured | 878 TUs, 251 keys, 0 moved · 45 grid cells, 16 moved | rungs/2026-08-08-w-park.md §4 · `work/w-park/scan_{base,tip}.jsonl` | Board **#1829**'s shape with a second instance: a widening priced honestly at ~0 immediate reach. It is shipped on the grid, the fixtures and the class — **not** on a TU — and the rung says so in its title rather than in a footnote |
| **1922**<sub>w-park</sub> | **THE `callseq-multiarg-lit-*` FENCE IS REACHABLE ONLY WHEN THE FORMALS ARE IN PLACE — THE PERMUTATION FENCE RUNS FIRST** | **MEASURED by a reverted probe patch**, and it rewrote three `_neg` cells. `callseq-early-return-permuted-args` is asked **before** `callseq-multiarg-lit-*`, so a literal in slot 0 — which makes `slot_sources` non-injective — reaches the permutation fence and never the literal one. GRID-P's `c_s0` and `c_two` controls are green **for a different reason than the one they were generated to test**: they refuse, which is what the control asserts, but the deciding clause is the other fence | 7 cells, 7 distinct keys; 3 rewritten after the probe | rungs/2026-08-08-w-park.md §5 · `work/w-park/decline_probe.md` | Board **#1704**'s defect paying an **eighth** time, and the first time the declining production returned `Option` rather than `Result` — the key was not merely unreported, it was *discarded at the call site*. A `_neg` file that had only been counted would have recorded three clauses it does not test |
| **1923**<sub>w-park</sub> | **`Biquad.cpp` IS BLOCKED AT THE BOTTOM OF ITS OWN LADDER, ONE CONSTRUCT INTO ITS SMALLEST CELL — THE THREE CHOOSER RULES ARE NOT REACHABLE IN IT** | **DECLINED, and the decline is a ladder.** `void BQ::one(float*){ coefs[0] = 1.0f; }` — **one** pooled-constant store through `this`, four words of PowerPC — blocks at **`expr-op-0x27`**, the byte-offset add that re-types a designator. `flts[0]/flts[3]` blocks at **`expr-op-0x28`**, the subscript. Both are in the DESIGNATOR layer, below the pools, below the `if`/`else`, below B-RULE, B-RULE-2, B′-RULE and the label counter. **Not one of the three rules `WB_CHOOSER_FINDINGS` §8 commissioned can be exercised on this TU until two designator opcodes are read** | 6-cell ladder, 0/6 in class; the target's 176 bytes reproduced word-for-word by `work/w-park/cells/bq.cpp` | rungs/2026-08-08-w-park.md §6 · `work/w-park/cells/lad_bq.cpp` | #1888 says these two TUs are *"blocked by three lowering rules the port does not implement"*. That is true and it is not the head of the chain. **`w-dclass` §6.1 already priced `expr-op-0x27`: the #1 key at 23,090 blocked emitted functions, worth six functions and zero TUs** — so the head of Biquad's chain is a key measured to convert almost nothing, which is the worst shape a first refusal can have |
| **1924**<sub>w-park</sub> | **`mmio.cpp`'s THREE BODIES HAVE THREE DIFFERENT FIRST REFUSALS AND ONLY ONE OF THEM IS A CHOOSER** | **DECLINED, per body, by construct ladder.** After #1920: `mmioGetInfo` → **`callseq-tail-lit`** (the `memcpy` statement is an intrinsic and is never consumed as a call); `mmioSetInfo` → **`call-token-0xB9`**, which fires on *anything* after the call — even reading a formal — so its post-call conditional member store is behind one reader refusal and a Class B emitter; `mmioClose` → **`call-token-0x26`**, a guard on a **call result**, which stops all four rungs of its ladder at the same place | 5 + 7 ladder cells; all three targets reproduced word-for-word (`p_getinfo`/`p_setinfo`/`p_close`) | rungs/2026-08-08-w-park.md §6 · `work/w-park/cells/lad_{setinfo,close}.cpp` | **The park (M-RULE) is the only one of the three commissioned rules `mmio.cpp` needs, and it is already SHIPPED** (`seq_entry_park`, w-mmio). What is left is three reader refusals and two emitter classes, none of them a chooser. `mmioGetInfo`'s own 84 bytes are a byte-exact `match` today with the callee renamed — `work/w-park/cells/l3.cpp` — so the entire remaining distance on that body is the word `memcpy` |
| **1925**<sub>w-park</sub> | **`expr-intrinsic-memcpy` IS A MEASURED NON-RULE, NOT AN UNBUILT ONE, AND IT IS THE WHOLE OF `mmioGetInfo`'s REMAINING DISTANCE** | **DECLINED on a prior lane's measurement, re-read rather than re-derived.** `w-memcpy` gridded it three times: `M-ALWAYSCALL` scores **114 of 232**; the expansion is alignment-dependent (`char*` inlines to 5 and calls from 7, `int*` 20/24, `double*` 44/48); **four separately frozen thresholds all miss**, the best at 182; and GRID-M's one unanimous sub-class — *constant size ≥ 48 ⇒ `bl`* — was **refuted by GRID-M2 at 114 of 176**. A third mechanism (both operands local ⇒ the copy is ELIMINATED) accounts for 44 of 176 | 232 + 176 cells, prior lane | rungs/2026-08-08-w-memcpy.md §1 · rungs/2026-08-08-w-park.md §6.1 | This is the sharpest thing on `mmio.cpp`'s row and it is **not** an engineering price. A reader that keyed on selector 172 and emitted a `bl` would be wrong on **118 of 232** measured cells — board #232's shape, at scale. `mmio.cpp` cannot convert until somebody models c2's `memcpy` expansion cost, and no lane has |
| **1926**<sub>w-park</sub> | **THE `/Ox` REFUSAL THIS LANE'S FIXTURE HEADER ASSERTED IS FALSE — A MODE SPLIT *IN* A CLASS IS NOT A REFUSAL *OF* IT** | **CORRECTED before commit, by measurement.** The first draft of `wpark_lit_permuted.cpp`'s header read *"at `/Ox` this file is deliberately 0/N in class"*, written from `shapes::early_return`'s module doc, which records that `/Ox` tail-duplicates the epilogue where `/O1` shares it. Both halves of that doc are right. The inference was not: the fixture is **5/5 in class and a byte-exact `match` at both** — five COMDAT `.text` sections at `/O1`, ONE packed 444-byte `.text` with the epilogue duplicated per arm at `/Ox` — and the port models both sides | 2 profiles, per file, `c2rs gap --flags-file` | rungs/2026-08-08-w-park.md §5.2 · `differential_wpark_lit_permuted_pair` | The paraphrase failure `WB_CHOOSER_FINDINGS` §8 names, one level in: not a rung's price quoted forward, but a rung's *finding* used to derive a claim it does not make. The mitigation is the same and it fired here — the number was measured before the sentence was committed |
"""
NOTE = """
> **`#1927`–`#1939` are minted by nobody and are FREE.** Lane `w-park` was
> allocated `#1920`–`#1939` and used seven (`#1920`–`#1926`). The unused
> thirteen are recorded as explicitly unminted rather than left to be inferred
> from a gap.
"""
p = "docs/BOARD.md"
s = open(p).read()
assert "**1920**<sub>w-park</sub>" not in s
anchor = "\n\n> **`#1889`–`#1899` are minted by nobody and are FREE.**"
i = s.find(anchor)
assert i > 0, "anchor not found"
s = s[:i] + "\n" + ROWS.rstrip("\n") + s[i:]
open(p, "w").write(s.rstrip("\n") + "\n" + NOTE)
print("rows inserted")
