#!/usr/bin/env python3
"""stride.py — the label-counter INTER-FUNCTION STRIDE, on a full cross product.

`labelgrid.py` measured the gap between two framed functions' `$M` numbers as
**2 above the three emitted slots, in all 17 cells**, invariant across twelve
distinct interior control-flow shapes and both held-out short-circuit cells.
That is a much stronger statement than the grid was built to make, so it gets a
cross product rather than a row.

REGISTERED BEFORE RUNNING (w-tu2 PREREG R7 -- a rule must hold on cells it was
not fitted to, or be refused by name):

    first($M of next framed fn) - first($M of this framed fn)
        =  5  for this framed function itself   (3 emitted + 2 unemitted)
        +  1  per intervening LEAF stub
        +  5  per intervening FRAMED function

Fitted on `labelgrid.py`'s `stub1` (1 stub) and confirmed there on the held-out
`stub5` (5 stubs). This grid crosses the middle-content axis with the probe's
interior control flow, which the rule says must not matter at all.

    probe  in {straight, if2_ret, while, and}       -- 4 interior CF shapes
    middle in {none, 1 stub, 2 stub, 5 stub,
               1 framed, 2 framed, 1 stub+1 framed} -- 7 middle contents
    = 28 cells, and the rule predicts every one of them with no free parameter.

Read-only measurement tooling, outside the std-only workspace.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from labelgrid import HEAD, TAIL, compile_cell, labels  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))

PROBES = {
    "straight": "int P(int a,int b){ return g(a)+1; }",
    "if2_ret":  ("int P(int a,int b){ if(a) return 5; if(b) return 11;"
                 " return g(b)+1; }"),
    "while":    "int P(int a,int b){ while(a){ b=g(b); --a; } return b; }",
    "and":      "int P(int a,int b){ if(a&&b) return 5; return g(b)+1; }",
}

STUB = "int s{i}(){{ return 0; }}\n"
# `+{i}` with i STARTING AT 1. The first version of this generator started at 0,
# so `f0` was `return h(x)+0` -- which c2 emits as a TAIL CALL, not a framed
# function: no frame, no `$M`, and a charge of 1 rather than 5. All 12 of the
# grid's disagreements were that one degenerate cell, and the rule was right.
# Recorded rather than silently fixed: a generator that quietly produces a
# different shape than its name claims is the single-cell trap with the cells
# generated by the experimenter.
FRAMED = "int f{i}(int x){{ return h(x)+{i}; }}\n"
# An explicitly NON-framed, non-leaf function, to pin the "1" separately.
TAILC = "int t{i}(int x){{ return h(x); }}\n"


def middle(nstub, nframed, ntail=0):
    s = "".join(STUB.format(i=i) for i in range(nstub))
    f = "".join(FRAMED.format(i=i + 1) for i in range(nframed))
    t = "".join(TAILC.format(i=i) for i in range(ntail))
    return s + f + t


MIDDLES = {
    "none":         (0, 0, 0),
    "stub1":        (1, 0, 0),
    "stub2":        (2, 0, 0),
    "stub5":        (5, 0, 0),
    "framed1":      (0, 1, 0),
    "framed2":      (0, 2, 0),
    "stub1framed1": (1, 1, 0),
    "tail1":        (0, 0, 1),
    "tail2framed1": (0, 1, 2),
}


def main():
    topdir = os.path.join(HERE, "stridegrid")
    os.makedirs(topdir, exist_ok=True)
    print(f"{'probe':10} {'middle':13} {'stride':>7} {'predicted':>10}  ok")
    print("-" * 50)
    ok = bad = 0
    fails = []
    for pn, psrc in PROBES.items():
        for mn, (ns, nf, nt) in MIDDLES.items():
            name = f"{pn}__{mn}"
            src = psrc + "\n" + middle(ns, nf, nt)
            obj = compile_cell(name, src, topdir)
            if obj is None:
                fails.append(name)
                continue
            ls = labels(obj)
            # P's three slots first, then each middle FRAMED fn's three, then Z's.
            # Leaf stubs emit no label at all, so the LAST three are always Z's.
            nums = [v for _, v in ls]
            first_p = min(nums[0:3])
            first_z = min(nums[-3:])
            stride = first_z - first_p
            pred = 5 + 1 * ns + 5 * nf + 1 * nt
            good = stride == pred
            ok += good
            bad += not good
            print(f"{pn:10} {mn:13} {stride:7} {pred:10}  "
                  f"{'.' if good else 'MISMATCH'}")
    print()
    print(f"cells graded {ok + bad} of {len(PROBES) * len(MIDDLES)}   "
          f"agree {ok}   DISAGREE {bad}")
    if fails:
        print("compile-fail:", ", ".join(fails))
    return 0


if __name__ == "__main__":
    sys.exit(main())
