#!/usr/bin/env python3
"""rows.py — insert w-seam2's board rows #1167-#1176 at NUMERIC POSITION.

Re-runnable, and a script rather than a shell transcript for `w-seam`'s own
reason (board #874). Fails hard if a number is already claimed or if an anchor
is missing, so a concurrent lane minting the same number is an error and not a
silent overwrite.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BOARD = os.path.join(ROOT, "docs/BOARD.md")

DONE = [
    ("1167", """| **1167**<sub>w-seam2</sub> | **BOARD #844 IS CLOSED — the composition seam emits a scheduled store run as the MIDDLE of a framed body, byte-exact, and the fix is a CARRIER rather than an emitter** | **DONE.** `c2_il::CallSeq::store_run: Option<StoreRunPrefix>` holds the run and `IlFunction::ops` stays **EMPTY** for the shape, so the race `w-f23` measured is *unspellable* rather than merely re-ordered — there is no dispatch order for `codegen::select` to get wrong. Every other part already existed and is consumed rather than re-derived (#842): `codegen::frame` the prologue and the 96-byte class, `calls::call_seq_text` the `bl`'s self-encoded displacement and the REL24 site, `leaf::store::scheduled_gpr_run` the run, `coff::pdata`/`coff::label` the unwind word and the `$M`/`$T` labels. **Selection is `Selected::Seq`**, so the composition introduces no new obj shape. Graded: **104 cells across four grids, 0 mismatch**; `fnbyte-exact` **36,209 → 36,212**, `fnbyte-shape-seq-exact` **1,227 → 1,230**, `fnbyte-refused` **130,579 → 130,576**; census `fn_in_class` **711,477 → 711,485**; sweep `88-store-run-call` **44 → 83 Port=Match** at 0 mismatch | rungs/2026-08-08-w-seam2.md §1, §2; `crates/c2-core/src/codegen/store_run_call.rs`, `crates/c2-il/src/func/mod.rs` `StoreRunPrefix`; `fixtures/cpp/w844_store_run_call.cpp`, `..._neg.cpp` |"""),
    ("1168", """| **1168**<sub>w-seam2</sub> | **#871's BLOCKING ARGUMENT IS DISCHARGED ON EVERY CLAUSE, and the discharge is MEASURED rather than argued** | **DONE.** C1: `fnbyte-partial` is **0** — `w-fnbyte` closed #322. C2, the load-bearing one: the seam's population lands in `Selected::Seq`, and **`fnbyte-shape-seq-exact` moved 1,227 → 1,230** — the standing alarm did not stay silent, it **fired positively on this lane's own three functions**; had the seam been wrong they would have landed in `fnbyte-shape-seq-differs`. C3's successor clause (the 878-TU scan cannot GENERATE this shape, `w-heap` §6.3) is discharged by `w-gen`'s 1,576-case fragment, run on **every** iteration of this lane and 0 mismatch on all four. C4 is a statement about #322's value and was never a live precondition | rungs/2026-08-08-w-seam2.md §3; `work/w-seam2/metrics_base.txt` vs `metrics_tip.txt` | **The prereg registered C2 as the claim most expected to LOSE** — direction: the composition needs its own `Selected` variant, which `fnbytes.rs` would map to `Partial` and put the alarm back out. It did not, because the composition is a framed call sequence and had no business being a fifth variant. **Board #1101 was right that the gate had been open for days** — and open for a reason nobody had written down: the emitter was never the missing part |"""),
    ("1169", """| **1169**<sub>w-seam2</sub> | **BOARD #866 IS REFUTED IN ITS GENERAL FORM — the leaf schedule does NOT transfer into a framed body when the run stores a value the CALL keeps alive** | **REFUTED, on real `c2` bytes, and it produced two live `Port=Mismatch` verdicts before it was found.** `void P::lf(unsigned a,unsigned b){ m0=0; m1=b; m2=a; }` is `li 11,0 ; stw 5,4(3) ; stw 4,8(3) ; stw 11,0(3) ; blr`; the same run before `Alloc(a)` is `li 11,0 ; stw 4,8(3) ; stw 5,4(3) ; mr 31,3 ; stw 11,0(3) ; bl`. **The two unproduced stores SWAP** — `a` is live until the `bl`, `b` dies at its store — and the *identical* body before a NULLARY callee does not swap. #866's 96 cells and this lane's own 34 are all inside the region where no store reads a live argument. **The receiver is exempt and that is measured too**: storing `this` transfers on every cell | 34/34 IDENT inside the class · 2 fixture `Port=Mismatch` outside it | rungs/2026-08-08-w-seam2.md §4; `work/w-seam2/grid3/` (12 cells), `grid4/` (13, frozen first), `bisect/` | **GRID S could not generate it and neither can the sweep fragment.** Every unproduced store in GRID S and in `scripts/sweep.d/88-store-run-call.py` stores the LAST formal or `this`, never the formal the call passes — so 63 frozen cells and 1,576 generated cases were all green through both wrong emits. `w-heap` §5's *"a generated axis is only as good as the axes it varies"*, landing on the lane that quoted it |"""),
    ("1170", """| **1170**<sub>w-seam2</sub> | **THE `mr r31,r3` SLOT RULE (#867) SHIPS UNCHANGED AFTER FOUR YEARS OF NOT SHIPPING, and its DOMAIN BOUNDARY is located: `nprod == 0, u <= 1`** | **DONE.** `stores_before_mr = nprod - 1 + min(u, 2)`, scored cell by cell against real `c2` at the workload's own flags: **GRID S (the frozen fit set, 36 accept cells) 32 HIT / 4 MISS**, and **GRID S2 (declared post-hoc holdout at `nprod = 3` and `u = 2/4/5/6`) 16 HIT / 0 MISS**. **Every miss is `nprod == 0` with `u <= 1`**, where the formula is negative or off by one — `(0,0) -> -1` against an observed 0, `(0,1) -> 0` against an observed **1** — and at `nprod == 0, u >= 2` it is right on five distinct `u` levels. So the rule ships **unchanged** and the domain is **refused**, not patched | 48/48 inside the domain, across two grids, on top of #867's own 24-fit / 18-holdout | rungs/2026-08-08-w-seam2.md §5; `work/w-seam2/mrslot_grid.txt`, `mrslot_grid2.txt`; `codegen::store_run_call::save_slot` | **The correcting clause is named and NOT taken**: `min(u,1)` at `nprod == 0` would rest on ONE structural cell, and clamping the formula at zero emits `mr 31,3 ; stw 5,16(3)` where c2 emits the reverse — two right words in the wrong order, an obj that still links. The counterexample is pinned beside the refusal. **`u`'s two readings are provably one number**: `store_order` forbids a store whose producer has rank `j` below position `u + j`, so the leading run is always at least `min(2, total)` and `min(leading,2) == min(total,2)` identically — an argument, not a coincidence of 52 cells |"""),
    ("1171", """| **1171**<sub>w-seam2</sub> | **A MULTI-WORD LITERAL ALONE IN A RUN IS IN CLASS AS A LEAF AND NOT IN A FRAMED BODY — the `mr r31,r3` lands BETWEEN the `lis` and the `ori`** | **MEASURED on one obj.** `WD::WD(unsigned a,unsigned b){ m1=70000; m2=b; p0=this; Alloc(a); }` is `lis 11,1 ; stw 5,8(3) ; stw 3,0(3) ; mr 31,3 ; ori 11,11,4464 ; stw 11,4(3)`. `collect_store_run`'s clause 4 refuses a wide literal only *beside another producer*, and states its own reason: a run whose only producer is wide is **one live range with nothing to interleave with**. That is true of a LEAF. In a framed body the callee-saved copy is a second thing that can land there | one cell, and it was found by the fixture and not by 63 frozen ones | rungs/2026-08-08-w-seam2.md §5.1; `fixtures/cpp/w844_store_run_call_neg.cpp` `WD`; `crates/c2-il/.../leaf_store.rs` `try_parse_store_run_call` | **A rule's stated reason is its scope.** Clause 4 said *why* it was safe at one producer, and the sentence stopped being true the moment a non-producer word could be scheduled into the run. The emitter cannot express the shape either way — it splices BETWEEN slots and a producer is one slot — so this is a refusal and not a lowering |"""),
    ("1172", """| **1172**<sub>w-seam2</sub> | **`store-run-call-no-emitter-carrier` IS 8 → 0 — the whole residue `w-f23` sized is converted, and all three emitted bodies are BYTE-EXACT** | **DONE, measured on the 878-TU scan at both ends.** `disp-store-run-call` reads **8, blocked 0**; the `:eof` key is absent from `fn_blockers` and from `emit_blockers`. The three emitted ones are `ClipDistMap.cpp`, `UsbMidiGuitar.cpp`, `Movie.cpp`, and they are byte-exact: `fnbyte-exact` **36,209 → 36,212**, `fnbyte-exact-relocated` **3,803 → 3,806** (each carries its REL24), `fnbyte-calltarget-agree` **+3**. `expr-op-0x27` is **unmoved** at 402,140 / 22,374, so nothing fell back | 8 IL bodies · 3 emitted · +3 `fnbyte-exact` | rungs/2026-08-08-w-seam2.md §1, §7.2; `work/w-seam2/scan_tip.log` | **`codegen-gap` stayed 0 through it** — board #1164: the scan's partition is per TU and every vocab-gap TU carries another undecodable body. The acceptance signal was the `:eof` key and the byte compare, named in the prereg **before** the first probe for exactly that reason |"""),
]

OPEN = [
    ("1173", """| **1173**<sub>w-seam2</sub> | **THE HOIST RULE FOR A LIVE-ARGUMENT STORE — the widest remaining slice of the #844 family, visible and deliberately not fitted** | **Worth: unmeasured here, and it is the whole of what #1169 refuses.** Every store-run-before-a-call whose run stores a formal the call passes is refused today, and `w-gen`'s fragment can generate 1,576 variants of the family. What is known, from 12 probe cells: the store of the live value is **hoisted to the front of the run**, and the receiver at slot 0 is exempt | **What is NOT known**: whether "hoisted to the front" survives more than one live argument, a produced store in front, or a wider run — `work/w-seam2/grid3/` has four broken cells and they are the four that produced the observation | **Do NOT fit on GRID S3 or GRID S4.** They are the cells that refuted `w-seam2`, and a rule read off the cells that refuted a lane is how all six refuted allocation keys got written (`w-heap` §4.1.1). A lane taking this owes a grid built for the hoist, with the leaf control beside every cell | rungs/2026-08-08-w-seam2.md §4.4, §10 |"""),
    ("1174", """| **1174**<sub>w-seam2</sub> | **THE SWEEP FRAGMENT `88-store-run-call.py` DOES NOT VARY THE LIVE-ARGUMENT AXIS — 1,576 generated cases were at 0 mismatch through TWO wrong emits** | **MEASURED, by the wrong emits happening anyway.** The fragment's runs store `mSize = size` (the last formal, never passed) and `mFreeHead = this`; not one of its 1,576 cases stores the formal its call passes. `w-seam2` shipped an emitter that was wrong on that shape, ran the fragment, and got `checked=1576 mismatches=0` — twice. The cell that caught it was a hand-written **fixture** cross-product | **The repair is cheap**: cross the stored value against the call's own argument list, which is one more level on an axis the fragment already has | rungs/2026-08-08-w-seam2.md §4.2, §10 item 5 | **This is board #232's mechanism with the instrument PRESENT and looking at the wrong axis**, which is a third failure mode beside "no instrument" (#232) and "instrument removed" (#871/#876). `w-gen` landed the generator *before* the widening exactly so this could not happen, and it happened anyway — because a generator is only as good as the axes it varies, and the axis it was missing was one no document in this repo had named |"""),
    ("1175", """| **1175**<sub>w-seam2</sub> | **A GATE CAN REFUSE NOTHING AND LOOK EXACTLY LIKE A GATE — `value_is_load` is not "the value is a formal", and the predicate was inert** | **FOUND by `census_gate.rs`, not by reading the predicate and not by any grid.** `w-seam2`'s live-argument gate first read `st.value_is_load && st.ops.get(1) == Some(&IlOp::Load(live))` and matched **nothing**: `StoreStmt::value_is_load` means the value is an *indirect load* (`s->m = t->n`), while a **formal**-valued store has it `false` with `IlOp::Load(tok)` in the value position. The gate compiled, read correctly, refused zero bodies — and the only symptom was `census_gate.rs` still naming two functions the census counted and `PortC2` refused | rungs/2026-08-08-w-seam2.md §6.1 | **A gate that refuses nothing is indistinguishable from a gate that is not there**, and the instrument that told them apart is the one that compares two INDEPENDENT answers — the census's and the port's — rather than checking either against itself. `STATUS.md` trap 5 (*absence reads as a verdict unless something forbids it*) at the level of a single boolean |"""),
    ("1176", """| **1176**<sub>w-seam2</sub> | **`xboxheap.cpp` IS AT TWO, AND NEITHER IS THE SEAM — the frontier's blocker is now #868/#836, the row two lanes have measured and declined** | **RE-PRICED, from the paid side.** #1097 said three, `w-heap` said five, `w-f23` said three. Of those: **F2 PAID** (`w-f23`), **F3 PAID** (reader half `w-f23`, other half **is** #844), **#844 PAID** (here). Remaining: **#868/#836**, `alloc`'s mixed-kind refusal, which is reachable and which this lane did not lift — `parse_simple_gpr_run` declines the four-op `AddrOf` group before `order::schedule` or `alloc::allocate` is asked anything, and `work/w-seam2/grid/sr_pA1`/`sr_pAL` grade the refusal; and **#839**, the reference bind, which is why `xboxheap.cpp` **itself** is unreachable — its shipped spelling stores into a LOCAL whose token then stands in two later stores' base position | 3 → **2**, and **TU match did not move** | rungs/2026-08-08-w-seam2.md §8; `w-f23` §5.1 prices #839 to the byte | **The first time in this row's history that a re-derivation came back CHEAPER than the list it was handed** — board #770 was seven for seven the other way. It is cheaper because two lanes paid, not because anything was re-estimated, and the row says so. **TU match 10 → 10 was registered in the prereg before the first probe**, with the reason: `xboxheap` is behind item 5, and the three functions that did convert live in TUs carrying other undecodable bodies (#1164) |"""),
]


def insert(text, section, rows):
    """Insert rows into `section` at numeric position among the `| **N**` rows."""
    start = text.index("\n## %s\n" % section)
    nxt = text.find("\n## ", start + 1)
    if nxt == -1:
        nxt = len(text)
    body = text[start:nxt]
    lines = body.split("\n")
    for num, row in rows:
        if re.search(r"\|\s*\*\*%s\*\*" % num, text):
            sys.exit("board #%s is already claimed — refusing to overwrite" % num)
        at = None
        for i, ln in enumerate(lines):
            m = re.match(r"\|\s*\*\*(\d+)\*\*", ln)
            if m and int(m.group(1)) > int(num):
                at = i
                break
        if at is None:
            at = len(lines)
            while at > 0 and not lines[at - 1].startswith("|"):
                at -= 1
        lines.insert(at, row)
    return text[:start] + "\n".join(lines) + text[nxt:]


def main():
    s = open(BOARD).read()
    s = insert(s, "Done", DONE)
    s = insert(s, "Open", OPEN)
    open(BOARD, "w").write(s)
    print("inserted %d Done + %d Open rows" % (len(DONE), len(OPEN)))


if __name__ == "__main__":
    main()
