#!/usr/bin/env python3
"""grid.py — lane w-wire.

Generate an exhaustive TU over the WIDENED store-run class and hand it to the
project's own judge: `c2rs diff`, which compiles the TU with the real `c2.dll`
under wibo and byte-compares the port's whole obj against it.

This is deliberately NOT scored against a python transcription of the model.
Every prior lane in this family fitted a model in python and scored a grid with
it; that is the right instrument for FINDING a rule and the wrong one for
shipping an emitter. The correctness rule names one judge and this uses it.

  python3 work/w-wire/grid.py --write     # write the TU
  python3 work/w-wire/grid.py             # write it and run `c2rs diff`

The alphabet is one formal (`u`) and three literals; every word of length 2..4
over it is one probe function, plus the length-5 and length-6 words that carry
the shapes the shorter ones cannot (three producers with two fillers, the
`u = min(2, #unproduced)` boundary).
"""
import itertools
import os
import subprocess
import sys

W = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(W))

ALPHABET = ["u", "1", "2", "3"]


def words():
    seen = set()
    out = []
    for n in (2, 3, 4):
        for w in itertools.product(ALPHABET, repeat=n):
            out.append(w)
            seen.add(w)
    # Length 5 and 6: the shapes shorter words cannot carry — three distinct
    # producers with two and three unproduced stores (`u` is the LEADING RUN,
    # board #584, and it saturates at 2), and the all-produced ties that are
    # `w-order2`'s families A and B.
    for w in [
        "uu123", "u1u23", "1uu23", "123uu", "1u2u3", "uuu12", "uu112",
        "11222", "12321", "12312", "1212u", "u1212", "112u2", "1u122",
        "uuu123", "uu1233", "123123", "112233", "1u2u3u", "u12u3u",
        "1122u3", "u1u2u3", "111223", "123321",
    ]:
        t = tuple(w)
        if t not in seen:
            out.append(t)
            seen.add(t)
    return out


def name(w):
    return "X" + "".join(w).replace("u", "U")


def render(path):
    ws = words()
    with open(path, "w") as f:
        f.write("// GENERATED by work/w-wire/grid.py — lane w-wire, board #642.\n")
        f.write("// Every function is one cell of the WIDENED store-run class:\n")
        f.write("// one base symbol, <= 3 distinct single-word literals, mixed\n")
        f.write("// freely with one formal. Graded by `c2rs diff` against real c2.\n")
        f.write("struct S { unsigned m0,m1,m2,m3,m4,m5,m6,m7; };\n")
        for w in ws:
            body = " ".join("s->m%d = %s;" % (k, v) for k, v in enumerate(w))
            f.write("void %s(S* s, unsigned u) { %s }\n" % (name(w), body))
    return len(ws)


def main():
    src = os.path.join(W, "grid.cpp")
    n = render(src)
    print("wrote %s: %d probe functions" % (src, n))
    if "--write" in sys.argv:
        return
    c2rs = os.path.join(REPO, ".claude", "worktrees", "w-wire",
                        "target", "release", "c2rs")
    if not os.path.exists(c2rs):
        c2rs = os.path.join(W, "..", "..", "target", "release", "c2rs")
    r = subprocess.run([c2rs, "diff", src], capture_output=True, cwd=REPO)
    out = r.stdout.decode("utf8", "replace") + r.stderr.decode("utf8", "replace")
    print(out)
    if "SKIP" in out:
        raise SystemExit("SKIP: toolchain absent")
    # Positive check with a count: a run that graded nothing must not read as a
    # pass. `Port=Match` is the only acceptable verdict.
    if "Port=Match" not in out:
        raise SystemExit("FAIL: the port did not match — see the verdict above")
    print("GRID: %d probe functions, Port=Match" % n)


if __name__ == "__main__":
    main()
