#!/usr/bin/env python3
"""gen_grid.py -- generate the wb-blockorder switch grid (lane w-read-r8, read R8).

The grid answers, from real c2's objs, a question every prior block-order cell
in this repo was structurally incapable of answering.

WHY A NEW GRID, GIVEN `SUBSYS.md:139` SAYS "DO NOT START FROM A PROBE GRID":
this lane did not start from one.  The read came first (the emit walk
FUN_10b338f5, the splice primitives FUN_10bd3815/FUN_10bd3824).  The grid is
the *confirmation probe* the read plan requires of every read, and it is aimed
at one specific thing the read cannot settle on its own.

THE CONTROL THAT MAKES IT A CONTROL.  Every prior block-order cell in this
repo -- `wb-regalloc`'s M2, `wb-loop`'s d5 and a7, `w-ifn`'s nine -- writes its
cases in ASCENDING SOURCE ORDER.  In such a cell "reverse source order" and
"descending case value" are THE SAME SEQUENCE, so no such cell can tell them
apart.  The `scram` family below writes the same case VALUES in a deliberately
non-ascending SOURCE order, so the two predictions disagree cell by cell.

Each arm returns a distinct, deliberately non-affine constant, so the emitted
sequence of `li r3,<imm>` immediates IS the arm order, readable from the
disassembly with no source-order ground truth needed.  The constants avoid any
arithmetic identity that would let c2 fold the switch into a formula.
"""
import os
import sys

# Deliberately non-affine in the case index: no c*k+d fits, so c2 cannot
# strength-reduce the switch into arithmetic and delete the blocks we measure.
MARK = [137, 211, 149, 307, 163, 281, 199, 353, 173, 269,
        191, 331, 157, 293, 179, 317, 167, 271, 181, 311]
DEFAULT_MARK = 997


def arm(v, k):
    return "    case %d: return %d;" % (v, MARK[k])


def fn(name, order, values):
    """order: the source order (list of indices into `values`)."""
    body = ["int %s(int x){" % name, "  switch(x){"]
    for k in order:
        body.append(arm(values[k], k))
    body.append("    default: return %d;" % DEFAULT_MARK)
    body.append("  }")
    body.append("}")
    return "\n".join(body)


def main(outdir):
    cells = []
    src = ["/* wb-blockorder grid -- GENERATED by gen_grid.py, do not hand-edit. */",
           "/* lane w-read-r8, read R8 (block emission order). */", ""]

    # FAMILY A -- dense 0..n-1, ascending source order.  Sweeps the
    # decision-tree/jump-table threshold, which three uncombined prior cells
    # bracket to (8, 12].
    for n in range(2, 17):
        vals = list(range(n))
        name = "sw_dense%02d" % n
        src.append(fn(name, list(range(n)), vals))
        cells.append((name, "dense", n, list(range(n)), vals))

    # FAMILY B -- THE CONTROL.  Same dense value sets, written in a scrambled
    # source order so that source order != value order.
    for n in (4, 5, 6, 7, 8, 12, 13, 16):
        vals = list(range(n))
        # a fixed, reproducible scramble: odds ascending then evens descending
        order = [k for k in range(n) if k % 2] + [k for k in range(n - 1, -1, -1) if k % 2 == 0]
        name = "sw_scram%02d" % n
        src.append(fn(name, order, vals))
        cells.append((name, "scram", n, order, vals))

    # FAMILY C -- sparse values (no dense table possible), ascending source.
    for n in (4, 6, 8, 12):
        vals = [3, 9, 14, 21, 30, 44, 57, 68, 79, 91, 104, 120][:n]
        name = "sw_sparse%02d" % n
        src.append(fn(name, list(range(n)), vals))
        cells.append((name, "sparse", n, list(range(n)), vals))

    # FAMILY D -- sparse AND scrambled: both axes off at once.
    for n in (6, 12):
        vals = [3, 9, 14, 21, 30, 44, 57, 68, 79, 91, 104, 120][:n]
        order = [k for k in range(n) if k % 2] + [k for k in range(n - 1, -1, -1) if k % 2 == 0]
        name = "sw_spscram%02d" % n
        src.append(fn(name, order, vals))
        cells.append((name, "spscram", n, order, vals))

    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "switch_grid.cpp"), "w") as f:
        f.write("\n\n".join(src) + "\n")

    # The expectation file: for each cell, the emitted `li` marker sequence
    # predicted by SOURCE order and by DESCENDING VALUE order.  These two
    # disagree on every `scram` cell, which is the point.
    with open(os.path.join(outdir, "cells.tsv"), "w") as f:
        f.write("cell\tfamily\tn\tsource_order_marks\treverse_source_marks\t"
                "ascending_value_marks\tdescending_value_marks\n")
        for name, fam, n, order, vals in cells:
            by_src = [MARK[k] for k in order]
            by_val_asc = [MARK[k] for k in sorted(range(n), key=lambda k: vals[k])]
            by_val_desc = list(reversed(by_val_asc))
            f.write("%s\t%s\t%d\t%s\t%s\t%s\t%s\n" % (
                name, fam, n,
                ",".join(map(str, by_src)),
                ",".join(map(str, reversed(by_src))),
                ",".join(map(str, by_val_asc)),
                ",".join(map(str, by_val_desc))))
    print("wrote %d cells to %s" % (len(cells), outdir))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__)))
