#!/usr/bin/env python3
"""gen_random.py -- a randomized switch CORPUS for the block-order rule.

Lane w-read-r8.  The prereg registered a corpus check alongside the hand grid,
on the standing ground that "grids and corpora fail in opposite directions": a
grid tests the shapes you thought of, a corpus tests the ones you did not.

This is the corpus half, built by randomization rather than by scanning the
workload -- the workload gives real switches but no ground truth about their
case VALUES without parsing dc3 sources, and case values are precisely what the
rule is stated over.  Randomizing case count, value set, density and SOURCE
ORDER independently gives ground truth for free and covers shapes no human
would author.

Deterministic: seeded, so the corpus regenerates byte-identically.
"""
import os
import random
import sys

N_CELLS = 240
SEED = 20260823


def main(outdir):
    rnd = random.Random(SEED)
    src = ["/* wb-blockorder RANDOM CORPUS -- GENERATED by gen_random.py, seed %d. */" % SEED,
           "/* lane w-read-r8.  Do not hand-edit. */", ""]
    rows = []
    for i in range(N_CELLS):
        n = rnd.randint(2, 24)
        # density: sometimes dense, sometimes sparse, sometimes clustered
        mode = rnd.choice(["dense", "sparse", "clustered", "wide"])
        if mode == "dense":
            base = rnd.randint(-4, 40)
            vals = list(range(base, base + n))
        elif mode == "sparse":
            vals = sorted(rnd.sample(range(0, 400), n))
        elif mode == "clustered":
            vals = []
            while len(vals) < n:
                c = rnd.randint(0, 200)
                for k in range(rnd.randint(1, 4)):
                    if len(vals) < n:
                        vals.append(c + k)
            vals = sorted(set(vals))
            while len(vals) < n:
                v = rnd.randint(0, 400)
                if v not in vals:
                    vals.append(v)
            vals = sorted(vals)
        else:
            vals = sorted(rnd.sample(range(-2000, 4000), n))
        n = len(vals)
        # distinct non-affine markers
        # must fit a signed-16-bit `li r3,imm` field or the marker becomes
        # lis/ori and the extractor cannot read the arm order at all.
        marks = rnd.sample(range(1000, 30000), n)
        order = list(range(n))
        rnd.shuffle(order)                       # random SOURCE order
        name = "rc%03d" % i
        body = ["int sw_%s(int x){" % name, "  switch(x){"]
        for k in order:
            body.append("    case %d: return %d;" % (vals[k], marks[k]))
        body.append("    default: return 32000;")
        body.append("  }")
        body.append("}")
        src.append("\n".join(body))
        rows.append((name, n, vals, marks, order))

    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "random_corpus.cpp"), "w") as f:
        f.write("\n\n".join(src) + "\n")
    with open(os.path.join(outdir, "random_cells.tsv"), "w") as f:
        f.write("cell\tn\tvalues\tmarks\tsource_order_idx\n")
        for name, n, vals, marks, order in rows:
            f.write("sw_%s\t%d\t%s\t%s\t%s\n" % (
                name, n, ",".join(map(str, vals)), ",".join(map(str, marks)),
                ",".join(map(str, order))))
    print("wrote %d random cells" % len(rows))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__)))
