#!/usr/bin/env python3
"""gen_holdout.py -- the OUT-OF-SAMPLE test of the pivot-split arm-order model.

Lane w-read-r8 (read R8).  The model in question was fitted to exactly three
cells (sw_sparse08, sw_sparse12, sw_spscram12) of the main grid.  This repo's
own record is that a rule fitted to the cells you happened to look at is a
curve, not a rule (#3242 declined to recommend dispatch for exactly that
reason), so the model is written down as a PREDICTOR here, its predictions are
frozen, and only then is anything compiled.

THE MODEL, stated so it can fail:
    Let V be the case values sorted ascending, n = |V|.
    A switch that lowers to a DECISION TREE emits its arms in this order:
        n <  8 :  V reversed                       (pure descending)
        n >= 8 :  V[:p] reversed, V[p], V[p+1:] reversed,  where p = n//2
    Source order does not appear in the model at all.

The holdout uses value sets and case counts that appear NOWHERE in the fitting
set.  Each cell is written in a scrambled source order as well, so a model that
secretly depends on source order fails twice over.
"""
import os
import sys

MARK = [137, 211, 149, 307, 163, 281, 199, 353, 173, 269,
        191, 331, 157, 293, 179, 317, 167, 271, 181, 311,
        233, 401, 227, 419, 239, 409, 251, 421]
DEFAULT_MARK = 997

# Value sets disjoint in shape from the fitting set's [3,9,14,21,30,44,...].
HOLDOUT = {
    "hd09": [5, 11, 17, 23, 41, 53, 61, 73, 89],
    "hd10": [2, 13, 19, 29, 37, 47, 59, 71, 83, 97],
    "hd11": [7, 15, 25, 35, 45, 55, 65, 75, 85, 95, 111],
    "hd14": [1, 6, 12, 18, 24, 33, 39, 48, 54, 63, 69, 78, 84, 93],
    "hd16": [4, 8, 16, 22, 28, 34, 42, 46, 52, 58, 64, 72, 76, 88, 94, 102],
    "hd20": [3, 10, 20, 26, 32, 38, 43, 49, 56, 62,
             67, 74, 81, 87, 92, 98, 103, 109, 115, 121],
}


def predict(vals):
    """The frozen model.  Returns marker order for a DECISION-TREE lowering."""
    n = len(vals)
    order = sorted(range(n), key=lambda k: vals[k])   # indices, ascending value
    if n < 8:
        seq = list(reversed(order))
    else:
        p = n // 2
        seq = list(reversed(order[:p])) + [order[p]] + list(reversed(order[p + 1:]))
    return [MARK[k] for k in seq]


def main(outdir):
    src = ["/* wb-blockorder HOLDOUT -- GENERATED by gen_holdout.py. */",
           "/* lane w-read-r8; predictions frozen in holdout_pred.tsv BEFORE compiling. */",
           ""]
    rows = []
    for name, vals in HOLDOUT.items():
        n = len(vals)
        # scrambled source order: odds ascending then evens descending
        order = [k for k in range(n) if k % 2] + [k for k in range(n - 1, -1, -1) if k % 2 == 0]
        body = ["int sw_%s(int x){" % name, "  switch(x){"]
        for k in order:
            body.append("    case %d: return %d;" % (vals[k], MARK[k]))
        body.append("    default: return %d;" % DEFAULT_MARK)
        body.append("  }")
        body.append("}")
        src.append("\n".join(body))
        rows.append((("sw_%s" % name), n, predict(vals),
                     [MARK[k] for k in order]))

    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "holdout_grid.cpp"), "w") as f:
        f.write("\n\n".join(src) + "\n")
    with open(os.path.join(outdir, "holdout_pred.tsv"), "w") as f:
        f.write("cell\tn\tPREDICTED_tree_order\tsource_order\n")
        for name, n, pred, srco in rows:
            f.write("%s\t%d\t%s\t%s\n" % (name, n, ",".join(map(str, pred)),
                                          ",".join(map(str, srco))))
    print("wrote %d holdout cells" % len(rows))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__)))
