/* wb-blockorder HOLDOUT -- GENERATED by gen_holdout.py. */

/* lane w-read-r8; predictions frozen in holdout_pred.tsv BEFORE compiling. */



int sw_hd09(int x){
  switch(x){
    case 11: return 211;
    case 23: return 307;
    case 53: return 281;
    case 73: return 353;
    case 89: return 173;
    case 61: return 199;
    case 41: return 163;
    case 17: return 149;
    case 5: return 137;
    default: return 997;
  }
}

int sw_hd10(int x){
  switch(x){
    case 13: return 211;
    case 29: return 307;
    case 47: return 281;
    case 71: return 353;
    case 97: return 269;
    case 83: return 173;
    case 59: return 199;
    case 37: return 163;
    case 19: return 149;
    case 2: return 137;
    default: return 997;
  }
}

int sw_hd11(int x){
  switch(x){
    case 15: return 211;
    case 35: return 307;
    case 55: return 281;
    case 75: return 353;
    case 95: return 269;
    case 111: return 191;
    case 85: return 173;
    case 65: return 199;
    case 45: return 163;
    case 25: return 149;
    case 7: return 137;
    default: return 997;
  }
}

int sw_hd14(int x){
  switch(x){
    case 6: return 211;
    case 18: return 307;
    case 33: return 281;
    case 48: return 353;
    case 63: return 269;
    case 78: return 331;
    case 93: return 293;
    case 84: return 157;
    case 69: return 191;
    case 54: return 173;
    case 39: return 199;
    case 24: return 163;
    case 12: return 149;
    case 1: return 137;
    default: return 997;
  }
}

int sw_hd16(int x){
  switch(x){
    case 8: return 211;
    case 22: return 307;
    case 34: return 281;
    case 46: return 353;
    case 58: return 269;
    case 72: return 331;
    case 88: return 293;
    case 102: return 317;
    case 94: return 179;
    case 76: return 157;
    case 64: return 191;
    case 52: return 173;
    case 42: return 199;
    case 28: return 163;
    case 16: return 149;
    case 4: return 137;
    default: return 997;
  }
}

int sw_hd20(int x){
  switch(x){
    case 10: return 211;
    case 26: return 307;
    case 38: return 281;
    case 49: return 353;
    case 62: return 269;
    case 74: return 331;
    case 87: return 293;
    case 98: return 317;
    case 109: return 271;
    case 121: return 311;
    case 115: return 181;
    case 103: return 167;
    case 92: return 179;
    case 81: return 157;
    case 67: return 191;
    case 56: return 173;
    case 43: return 199;
    case 32: return 163;
    case 20: return 149;
    case 3: return 137;
    default: return 997;
  }
}
