/* wb-blockorder RANDOM CORPUS -- GENERATED by gen_random.py, seed 20260823. */

/* lane w-read-r8.  Do not hand-edit. */



int sw_rc000(int x){
  switch(x){
    case 2292: return 26578;
    case 3084: return 17570;
    case -1865: return 5603;
    case 400: return 14733;
    case 3359: return 3033;
    case 1210: return 8628;
    case 2881: return 24794;
    case -1943: return 17356;
    case 2655: return 22495;
    case 575: return 20588;
    case 227: return 16071;
    case 3539: return 8371;
    case 1638: return 29473;
    case -475: return 17279;
    case 3098: return 4879;
    case 485: return 2317;
    case -751: return 7493;
    case 1171: return 23754;
    case -871: return 18478;
    case 3408: return 3315;
    case -1523: return 16843;
    case 487: return 4701;
    default: return 32000;
  }
}

int sw_rc001(int x){
  switch(x){
    case 1870: return 21549;
    case -815: return 9118;
    case -1953: return 24281;
    case 3585: return 26382;
    case 27: return 18301;
    case 1979: return 29341;
    case -1531: return 3931;
    case 2635: return 23821;
    case 3317: return 9771;
    case 1302: return 26885;
    case 680: return 4797;
    case 208: return 22001;
    case -833: return 15034;
    case 1037: return 12844;
    default: return 32000;
  }
}

int sw_rc002(int x){
  switch(x){
    case 1874: return 16613;
    case 3438: return 17497;
    case -808: return 7545;
    case -1326: return 7290;
    case 1505: return 4296;
    case 2220: return 11778;
    case -460: return 24049;
    case -379: return 24273;
    case -318: return 5860;
    case 1073: return 18347;
    case 2391: return 2410;
    case -1351: return 20886;
    case -649: return 8816;
    case -407: return 29315;
    case 222: return 11522;
    case 577: return 26550;
    default: return 32000;
  }
}

int sw_rc003(int x){
  switch(x){
    case -596: return 5745;
    case 1927: return 2137;
    case 2540: return 13565;
    case -1367: return 17963;
    case 2031: return 10357;
    case 2100: return 19891;
    case -218: return 11947;
    case 1339: return 29164;
    case 1839: return 24141;
    case 1020: return 2782;
    case 2242: return 7674;
    case -1692: return 6627;
    case -691: return 16189;
    case 2530: return 3445;
    case -33: return 16524;
    case -735: return 23904;
    case 3099: return 3723;
    case 786: return 24621;
    case 3000: return 22921;
    case 1260: return 21070;
    case 370: return 29377;
    case 2090: return 24190;
    default: return 32000;
  }
}

int sw_rc004(int x){
  switch(x){
    case 100: return 18494;
    case 99: return 3769;
    default: return 32000;
  }
}

int sw_rc005(int x){
  switch(x){
    case 200: return 19731;
    case 201: return 21278;
    case 80: return 18131;
    case 203: return 4907;
    case 202: return 21367;
    default: return 32000;
  }
}

int sw_rc006(int x){
  switch(x){
    case 90: return 28215;
    case 91: return 5248;
    case 89: return 22748;
    default: return 32000;
  }
}

int sw_rc007(int x){
  switch(x){
    case 4: return 24494;
    case 1: return 19834;
    case 3: return 27912;
    case 0: return 13943;
    case 2: return 18554;
    case 5: return 17295;
    default: return 32000;
  }
}

int sw_rc008(int x){
  switch(x){
    case 46: return 7183;
    case 53: return 26964;
    case 47: return 23775;
    case 58: return 25276;
    case 41: return 22321;
    case 49: return 4934;
    case 54: return 3570;
    case 61: return 28729;
    case 52: return 22672;
    case 42: return 26300;
    case 51: return 4246;
    case 60: return 2034;
    case 45: return 12654;
    case 55: return 11033;
    case 57: return 12147;
    case 40: return 7757;
    case 48: return 4758;
    case 50: return 24360;
    case 44: return 23994;
    case 43: return 20029;
    case 56: return 28108;
    case 39: return 17989;
    case 59: return 7745;
    default: return 32000;
  }
}

int sw_rc009(int x){
  switch(x){
    case 110: return 2979;
    case 214: return 20019;
    case 59: return 19284;
    case 41: return 25930;
    case 374: return 9346;
    case 349: return 24106;
    case 119: return 1680;
    case 89: return 14339;
    case 152: return 15847;
    case 122: return 1603;
    case 352: return 16334;
    case 224: return 17110;
    case 319: return 13604;
    case 350: return 17367;
    case 140: return 1342;
    case 324: return 9828;
    case 193: return 2641;
    default: return 32000;
  }
}

int sw_rc010(int x){
  switch(x){
    case 129: return 29995;
    case 3067: return 8321;
    case -355: return 24475;
    case 1539: return 12246;
    case 1804: return 1625;
    case -760: return 16886;
    case 2084: return 14270;
    case -622: return 27766;
    case 583: return 19164;
    case 3729: return 23012;
    case -422: return 15778;
    case -173: return 3088;
    case -1310: return 2421;
    case -1244: return 11426;
    case -1778: return 13838;
    default: return 32000;
  }
}

int sw_rc011(int x){
  switch(x){
    case 35: return 18671;
    case 34: return 12883;
    default: return 32000;
  }
}

int sw_rc012(int x){
  switch(x){
    case 32: return 28410;
    case 311: return 8008;
    case 282: return 7810;
    case 368: return 21846;
    case 143: return 17811;
    case 24: return 9718;
    case 378: return 7383;
    case 338: return 6759;
    default: return 32000;
  }
}

int sw_rc013(int x){
  switch(x){
    case 340: return 1469;
    case 1430: return 16724;
    case 623: return 16097;
    case -1538: return 14453;
    case 2220: return 1957;
    case -695: return 10437;
    case 892: return 1396;
    case -57: return 12516;
    case 1085: return 10667;
    case 1612: return 10993;
    default: return 32000;
  }
}

int sw_rc014(int x){
  switch(x){
    case 51: return 7001;
    case 48: return 25707;
    case 41: return 11356;
    case 45: return 13914;
    case 38: return 4186;
    case 35: return 26597;
    case 34: return 1535;
    case 37: return 13306;
    case 47: return 26079;
    case 46: return 14746;
    case 52: return 18887;
    case 43: return 3453;
    case 49: return 16789;
    case 33: return 7861;
    case 50: return 8036;
    case 36: return 29528;
    case 39: return 5874;
    case 42: return 22154;
    case 44: return 26174;
    case 40: return 28730;
    case 53: return 5187;
    default: return 32000;
  }
}

int sw_rc015(int x){
  switch(x){
    case -1411: return 28237;
    case 3694: return 9487;
    case 846: return 20223;
    case 1115: return 3839;
    case 633: return 17946;
    case 3067: return 9592;
    default: return 32000;
  }
}

int sw_rc016(int x){
  switch(x){
    case -1356: return 8910;
    case 103: return 5364;
    case 1463: return 27122;
    case 3468: return 22122;
    case -458: return 20807;
    case -1782: return 19976;
    case 710: return 23526;
    case -1468: return 25907;
    case -1800: return 28474;
    case 2072: return 28767;
    case -581: return 6424;
    default: return 32000;
  }
}

int sw_rc017(int x){
  switch(x){
    case 130: return 8023;
    case 233: return 8428;
    case 254: return 11540;
    case 29: return 23235;
    case 209: return 11979;
    case 342: return 28310;
    case 312: return 18420;
    case 270: return 29729;
    case 155: return 24678;
    case 70: return 24007;
    case 39: return 10201;
    case 48: return 27653;
    default: return 32000;
  }
}

int sw_rc018(int x){
  switch(x){
    case 760: return 6573;
    case 325: return 22700;
    default: return 32000;
  }
}

int sw_rc019(int x){
  switch(x){
    case 83: return 26571;
    case 82: return 22593;
    case 175: return 11355;
    case 176: return 3954;
    case 54: return 14081;
    case 147: return 25129;
    case 81: return 6291;
    case 80: return 15387;
    case 174: return 24860;
    case 22: return 6379;
    default: return 32000;
  }
}

int sw_rc020(int x){
  switch(x){
    case 1716: return 9263;
    case -555: return 6575;
    case -1938: return 2222;
    case 3768: return 2090;
    case -1697: return 15692;
    case 3193: return 13888;
    case 3470: return 6276;
    case -359: return 14883;
    case -773: return 24699;
    case 2043: return 20205;
    case 3726: return 11283;
    case -494: return 7881;
    case 3959: return 21530;
    case 1566: return 22985;
    case -991: return 8186;
    case 1870: return 14440;
    case -689: return 1717;
    case 544: return 29171;
    case 887: return 14069;
    default: return 32000;
  }
}

int sw_rc021(int x){
  switch(x){
    case 3765: return 21066;
    case 3847: return 10510;
    case -1280: return 2621;
    case 2804: return 7640;
    case -1738: return 20339;
    default: return 32000;
  }
}

int sw_rc022(int x){
  switch(x){
    case 26: return 27778;
    case 27: return 28189;
    case 21: return 23467;
    case 28: return 17976;
    case 24: return 1845;
    case 25: return 10213;
    case 22: return 15748;
    case 23: return 23169;
    default: return 32000;
  }
}

int sw_rc023(int x){
  switch(x){
    case 176: return 21342;
    case 45: return 11723;
    case 175: return 1736;
    case 166: return 7323;
    case 151: return 2985;
    case 173: return 17011;
    case 167: return 16941;
    default: return 32000;
  }
}

int sw_rc024(int x){
  switch(x){
    case 365: return 14161;
    case 183: return 7782;
    case 317: return 27322;
    case 215: return 6104;
    case 19: return 10157;
    case 177: return 27912;
    case 73: return 1573;
    case 386: return 28962;
    case 103: return 15266;
    case 395: return 12442;
    case 330: return 22037;
    case 123: return 29526;
    default: return 32000;
  }
}

int sw_rc025(int x){
  switch(x){
    case 248: return 4199;
    case 120: return 21672;
    case 332: return 19875;
    case 31: return 19125;
    case 19: return 18697;
    case 95: return 5727;
    case 380: return 5144;
    case 48: return 24112;
    case 341: return 7637;
    case 108: return 5832;
    case 378: return 2474;
    case 284: return 19099;
    case 168: return 7678;
    case 104: return 1337;
    default: return 32000;
  }
}

int sw_rc026(int x){
  switch(x){
    case 247: return 18826;
    case 312: return 2047;
    case 286: return 13895;
    case 196: return 2590;
    case 159: return 10298;
    case 66: return 18881;
    default: return 32000;
  }
}

int sw_rc027(int x){
  switch(x){
    case 167: return 25343;
    case 185: return 8861;
    case 68: return 18971;
    case 168: return 24050;
    case 169: return 9902;
    case 186: return 11939;
    case 166: return 12195;
    default: return 32000;
  }
}

int sw_rc028(int x){
  switch(x){
    case 19: return 13686;
    case 12: return 1181;
    case 28: return 24197;
    case 25: return 29989;
    case 10: return 18267;
    case 11: return 13180;
    case 14: return 2938;
    case 24: return 16447;
    case 21: return 19134;
    case 15: return 18334;
    case 16: return 5306;
    case 18: return 20499;
    case 20: return 4119;
    case 17: return 9426;
    case 26: return 10299;
    case 27: return 23116;
    case 13: return 27487;
    case 23: return 9186;
    case 22: return 16527;
    default: return 32000;
  }
}

int sw_rc029(int x){
  switch(x){
    case 61: return 4127;
    case 15: return 11606;
    case 58: return 25608;
    case 202: return 22373;
    case 7: return 19508;
    case 60: return 16583;
    case 136: return 3679;
    case 11: return 24250;
    case 143: return 16624;
    case 201: return 10281;
    case 200: return 9043;
    case 59: return 13876;
    case 99: return 23659;
    case 16: return 15155;
    case 166: return 15442;
    case 8: return 26871;
    case 9: return 28765;
    case 203: return 11536;
    case 137: return 24261;
    case 70: return 22826;
    case 10: return 26077;
    default: return 32000;
  }
}

int sw_rc030(int x){
  switch(x){
    case 170: return 22065;
    case 171: return 12282;
    case 173: return 7584;
    case 172: return 25665;
    default: return 32000;
  }
}

int sw_rc031(int x){
  switch(x){
    case 5: return 17714;
    case 4: return 11897;
    case 6: return 21950;
    case 9: return 7181;
    case 7: return 20761;
    case 8: return 22308;
    default: return 32000;
  }
}

int sw_rc032(int x){
  switch(x){
    case 2836: return 15239;
    case 211: return 15732;
    case 456: return 17453;
    case 1488: return 2551;
    case 694: return 28526;
    case 584: return 20547;
    case 1841: return 9344;
    case -1223: return 29546;
    case 3232: return 29944;
    case -976: return 19647;
    case -1738: return 15925;
    case 1718: return 29481;
    default: return 32000;
  }
}

int sw_rc033(int x){
  switch(x){
    case 133: return 28143;
    case 165: return 15268;
    case 32: return 27402;
    case 50: return 12840;
    case 168: return 20811;
    case 52: return 20238;
    case 51: return 4734;
    case 21: return 9039;
    case 19: return 12745;
    case 147: return 20253;
    case 170: return 19857;
    case 30: return 26637;
    case 83: return 15923;
    case 20: return 14506;
    case 154: return 25530;
    case 23: return 5267;
    case 132: return 22573;
    case 169: return 15765;
    case 82: return 16748;
    case 31: return 2817;
    default: return 32000;
  }
}

int sw_rc034(int x){
  switch(x){
    case -1949: return 2107;
    case 3789: return 26823;
    case 2945: return 9408;
    case 778: return 10859;
    case 2469: return 13592;
    case -578: return 16916;
    case -1375: return 19846;
    case -581: return 28917;
    case 1827: return 22959;
    case -971: return 2454;
    case -1129: return 23594;
    case 995: return 7447;
    case 3997: return 4972;
    case 3756: return 4575;
    case 3602: return 7779;
    case -731: return 10133;
    case 76: return 12341;
    case -2: return 18922;
    default: return 32000;
  }
}

int sw_rc035(int x){
  switch(x){
    case 90: return 27593;
    case 172: return 16209;
    case 142: return 27513;
    case 141: return 5151;
    case 121: return 3472;
    case 186: return 3751;
    case 140: return 14191;
    case 19: return 4840;
    case 171: return 24367;
    case 92: return 6541;
    case 396: return 14804;
    case 185: return 16066;
    case 124: return 21993;
    case 20: return 24988;
    case 187: return 16534;
    case 139: return 25389;
    case 91: return 21824;
    case 125: return 9946;
    case 93: return 29096;
    case 173: return 15422;
    case 122: return 22399;
    case 174: return 3947;
    default: return 32000;
  }
}

int sw_rc036(int x){
  switch(x){
    case 4: return 29675;
    case 171: return 5813;
    case 139: return 16745;
    case 160: return 12008;
    case 168: return 18914;
    case 170: return 18144;
    case 169: return 19453;
    default: return 32000;
  }
}

int sw_rc037(int x){
  switch(x){
    case 147: return 4935;
    case 128: return 24820;
    case 74: return 22622;
    case 106: return 11347;
    case 157: return 5779;
    case 148: return 24002;
    case 200: return 13498;
    case 129: return 25573;
    case 158: return 22285;
    case 394: return 11179;
    case 72: return 18478;
    case 203: return 14971;
    case 73: return 21804;
    case 146: return 17405;
    default: return 32000;
  }
}

int sw_rc038(int x){
  switch(x){
    case 134: return 2919;
    case 192: return 11134;
    case 194: return 13106;
    case 79: return 10145;
    case 36: return 5751;
    case 35: return 7778;
    case 80: return 21029;
    case 133: return 6463;
    case 55: return 2202;
    case 104: return 13704;
    case 193: return 19812;
    default: return 32000;
  }
}

int sw_rc039(int x){
  switch(x){
    case 3505: return 13240;
    case 2108: return 8446;
    case -1077: return 22897;
    case 2562: return 19928;
    case -350: return 9994;
    case 492: return 27139;
    case 1269: return 20915;
    default: return 32000;
  }
}

int sw_rc040(int x){
  switch(x){
    case 54: return 10647;
    case 43: return 7045;
    case 53: return 5809;
    case 31: return 8816;
    case 35: return 23734;
    case 38: return 22537;
    case 33: return 25709;
    case 52: return 17697;
    case 49: return 27223;
    case 40: return 27264;
    case 36: return 18203;
    case 42: return 5223;
    case 46: return 11729;
    case 45: return 12437;
    case 32: return 29344;
    case 41: return 10817;
    case 48: return 6964;
    case 51: return 8970;
    case 50: return 8929;
    case 44: return 18071;
    case 34: return 22749;
    case 37: return 8432;
    case 47: return 17283;
    case 39: return 23338;
    default: return 32000;
  }
}

int sw_rc041(int x){
  switch(x){
    case 11: return 3856;
    case 8: return 25239;
    case 2: return 22695;
    case 15: return 14829;
    case 0: return 3182;
    case 14: return 29923;
    case 4: return 14642;
    case 7: return 12197;
    case 1: return 14295;
    case 5: return 29791;
    case 13: return 6577;
    case 10: return 29852;
    case 16: return 13820;
    case 3: return 24826;
    case -1: return 24332;
    case 9: return 13233;
    case 6: return 7490;
    case 12: return 16240;
    default: return 32000;
  }
}

int sw_rc042(int x){
  switch(x){
    case 1415: return 7829;
    case 3236: return 1679;
    case 3246: return 26073;
    case 3222: return 18887;
    case -768: return 9743;
    case 1273: return 1999;
    case 595: return 4092;
    case 2620: return 4356;
    default: return 32000;
  }
}

int sw_rc043(int x){
  switch(x){
    case 388: return 19302;
    case 293: return 23508;
    case 208: return 5238;
    case 354: return 19721;
    case 106: return 17592;
    case 205: return 6061;
    default: return 32000;
  }
}

int sw_rc044(int x){
  switch(x){
    case 2226: return 12649;
    case -1852: return 5890;
    case -956: return 22036;
    case -1058: return 1760;
    case 3487: return 7128;
    case 3778: return 28810;
    case -1713: return 14112;
    case 3390: return 16073;
    case 2203: return 5820;
    case -222: return 17702;
    case 1081: return 1299;
    case 254: return 15826;
    case -1337: return 2889;
    case -290: return 1071;
    case 2653: return 3460;
    case 1625: return 21621;
    case 805: return 18673;
    case 1948: return 5054;
    case -1554: return 29339;
    default: return 32000;
  }
}

int sw_rc045(int x){
  switch(x){
    case 68: return 13374;
    case 193: return 14185;
    case 96: return 4411;
    case 6: return 4921;
    case 4: return 7733;
    case 3: return 3941;
    case 192: return 10956;
    case 17: return 16583;
    case 142: return 19016;
    case 18: return 29503;
    case 141: return 23724;
    case 189: return 28139;
    case 81: return 22358;
    case 5: return 14918;
    case 69: return 19445;
    case 67: return 17465;
    case 19: return 26810;
    case 20: return 24097;
    default: return 32000;
  }
}

int sw_rc046(int x){
  switch(x){
    case 275: return 9593;
    case 254: return 3182;
    case 295: return 7511;
    case 89: return 22121;
    case 259: return 14763;
    default: return 32000;
  }
}

int sw_rc047(int x){
  switch(x){
    case 182: return 5253;
    case 85: return 3538;
    default: return 32000;
  }
}

int sw_rc048(int x){
  switch(x){
    case 168: return 11641;
    case 169: return 13645;
    default: return 32000;
  }
}

int sw_rc049(int x){
  switch(x){
    case 287: return 18520;
    case 282: return 4313;
    case 34: return 2744;
    case 235: return 15954;
    case 175: return 2040;
    case 111: return 6631;
    case 307: return 21877;
    case 397: return 2782;
    case 30: return 4836;
    case 300: return 8211;
    case 398: return 20169;
    case 283: return 13926;
    case 396: return 7863;
    case 45: return 1393;
    case 64: return 26944;
    case 242: return 24870;
    case 243: return 17665;
    default: return 32000;
  }
}

int sw_rc050(int x){
  switch(x){
    case 178: return 4268;
    case 13: return 15255;
    case 193: return 6430;
    case 191: return 18819;
    case 153: return 28506;
    case 154: return 29623;
    case 194: return 8210;
    case 69: return 8868;
    case 152: return 13344;
    case 192: return 6766;
    case 151: return 29311;
    default: return 32000;
  }
}

int sw_rc051(int x){
  switch(x){
    case 2435: return 29894;
    case 3690: return 15170;
    case 2061: return 24282;
    case 3967: return 17181;
    case 1246: return 4278;
    case 3547: return 24389;
    case 3335: return 15456;
    case 3489: return 14905;
    case 2532: return 20200;
    case -979: return 8311;
    default: return 32000;
  }
}

int sw_rc052(int x){
  switch(x){
    case 4: return 17035;
    case 12: return 18387;
    case -1: return 21008;
    case 6: return 19251;
    case 0: return 9985;
    case 11: return 16890;
    case 7: return 8970;
    case 1: return 21290;
    case 10: return 14545;
    case 2: return 8015;
    case 5: return 16754;
    case 3: return 8538;
    case 8: return 6909;
    case 9: return 16697;
    default: return 32000;
  }
}

int sw_rc053(int x){
  switch(x){
    case 175: return 24176;
    case 133: return 22449;
    case 287: return 20049;
    case 159: return 6288;
    case 388: return 18596;
    default: return 32000;
  }
}

int sw_rc054(int x){
  switch(x){
    case -779: return 11805;
    case 2117: return 12860;
    case -151: return 7610;
    default: return 32000;
  }
}

int sw_rc055(int x){
  switch(x){
    case -1: return 7279;
    case 0: return 21393;
    case 4: return 5718;
    case 2: return 5904;
    case 3: return 19432;
    case 1: return 8564;
    case -3: return 10411;
    case -2: return 15272;
    default: return 32000;
  }
}

int sw_rc056(int x){
  switch(x){
    case 1839: return 27203;
    case 2937: return 4519;
    case -757: return 1876;
    default: return 32000;
  }
}

int sw_rc057(int x){
  switch(x){
    case 60: return 22850;
    case -1809: return 19123;
    case 3501: return 3207;
    case 1150: return 8374;
    case 3986: return 5257;
    case -1344: return 18206;
    case 3085: return 17567;
    case -389: return 19324;
    case -873: return 2478;
    case 1961: return 29037;
    case 1231: return 8310;
    case -1033: return 25242;
    default: return 32000;
  }
}

int sw_rc058(int x){
  switch(x){
    case 228: return 16212;
    case 351: return 16982;
    case 120: return 17343;
    case 250: return 9894;
    case 293: return 26855;
    case 84: return 20867;
    case 325: return 6544;
    case 99: return 21149;
    case 165: return 11314;
    case 200: return 10657;
    case 133: return 2562;
    case 232: return 4710;
    case 352: return 1824;
    case 381: return 1787;
    case 98: return 22333;
    case 353: return 27645;
    case 107: return 12461;
    case 249: return 23551;
    default: return 32000;
  }
}

int sw_rc059(int x){
  switch(x){
    case 20: return 11652;
    case 16: return 22296;
    case 19: return 21216;
    case 14: return 25080;
    case 18: return 28531;
    case 17: return 3552;
    case 15: return 1963;
    default: return 32000;
  }
}

int sw_rc060(int x){
  switch(x){
    case 133: return 5197;
    case 186: return 14649;
    case 335: return 23461;
    case 40: return 1979;
    case 37: return 2306;
    case 181: return 9610;
    case 230: return 3722;
    case 239: return 24528;
    case 235: return 7874;
    default: return 32000;
  }
}

int sw_rc061(int x){
  switch(x){
    case 373: return 23271;
    case 59: return 20638;
    case 364: return 14348;
    case 161: return 26104;
    case 105: return 28530;
    case 154: return 12670;
    case 236: return 10791;
    case 107: return 13787;
    case 245: return 26381;
    case 32: return 29410;
    case 131: return 16827;
    case 176: return 3359;
    case 123: return 8779;
    default: return 32000;
  }
}

int sw_rc062(int x){
  switch(x){
    case 184: return 1140;
    case 181: return 27055;
    case 127: return 21878;
    case 183: return 6867;
    case 182: return 2408;
    case 128: return 12151;
    default: return 32000;
  }
}

int sw_rc063(int x){
  switch(x){
    case 3476: return 11049;
    case -714: return 3030;
    case 1690: return 3941;
    case -1743: return 1584;
    case -1672: return 7704;
    case 1568: return 27384;
    case 3320: return 12883;
    case 1871: return 9994;
    case 2038: return 29983;
    default: return 32000;
  }
}

int sw_rc064(int x){
  switch(x){
    case 23: return 19342;
    case 22: return 22164;
    case 29: return 25450;
    case 33: return 25887;
    case 34: return 21291;
    case 27: return 29779;
    case 28: return 29527;
    case 21: return 7017;
    case 26: return 1306;
    case 25: return 5528;
    case 30: return 21069;
    case 32: return 14107;
    case 31: return 27432;
    case 24: return 17511;
    case 20: return 26528;
    default: return 32000;
  }
}

int sw_rc065(int x){
  switch(x){
    case 173: return 19878;
    case 36: return 8535;
    case 119: return 18577;
    case 37: return 26253;
    case 120: return 2327;
    case 174: return 28838;
    case 52: return 27135;
    case 27: return 5501;
    case 26: return 5937;
    case 175: return 25670;
    case 53: return 6652;
    case 122: return 12859;
    case 32: return 24592;
    case 38: return 5009;
    case 28: return 1374;
    case 29: return 9664;
    case 33: return 24429;
    case 31: return 20183;
    case 121: return 17569;
    default: return 32000;
  }
}

int sw_rc066(int x){
  switch(x){
    case 36: return 15794;
    case 35: return 25976;
    case 39: return 27714;
    case 31: return 16092;
    case 34: return 24607;
    case 33: return 8891;
    case 30: return 11486;
    case 28: return 2437;
    case 26: return 25246;
    case 38: return 8737;
    case 25: return 7140;
    case 29: return 2076;
    case 32: return 29859;
    case 37: return 27569;
    case 27: return 29904;
    default: return 32000;
  }
}

int sw_rc067(int x){
  switch(x){
    case 4: return 20235;
    case 61: return 23035;
    case 63: return 18291;
    case 114: return 1246;
    case 62: return 28543;
    default: return 32000;
  }
}

int sw_rc068(int x){
  switch(x){
    case 3111: return 4910;
    case 3279: return 18808;
    case 1022: return 16554;
    case -410: return 26331;
    case 2961: return 19676;
    case 1253: return 25917;
    case -1938: return 16358;
    case 206: return 7882;
    case 3877: return 14907;
    case -533: return 19814;
    case 1401: return 27193;
    case -530: return 1796;
    case 3202: return 27894;
    case -1228: return 12451;
    default: return 32000;
  }
}

int sw_rc069(int x){
  switch(x){
    case 55: return 26331;
    case 164: return 2572;
    case 156: return 29689;
    case 84: return 19125;
    case 157: return 4311;
    case 190: return 4917;
    case 83: return 3346;
    case 115: return 27265;
    case 114: return 9118;
    case 191: return 21181;
    case 56: return 20803;
    case 126: return 14353;
    case 58: return 4865;
    case 57: return 15452;
    case 163: return 27046;
    case 158: return 25881;
    default: return 32000;
  }
}

int sw_rc070(int x){
  switch(x){
    case 3438: return 29617;
    case 488: return 23257;
    default: return 32000;
  }
}

int sw_rc071(int x){
  switch(x){
    case -333: return 1520;
    case 3543: return 23094;
    case 1171: return 20856;
    case 1861: return 12093;
    case 844: return 1907;
    case 3173: return 6904;
    case -1169: return 13902;
    case -1919: return 14892;
    case -1208: return 25087;
    case 132: return 10126;
    case 1732: return 5281;
    case -1204: return 15156;
    case 1239: return 24263;
    case -485: return 11626;
    case -1833: return 21886;
    case 3634: return 14696;
    case 1059: return 26191;
    case -1620: return 22829;
    case 1028: return 29365;
    case 1875: return 11162;
    case 914: return 1259;
    default: return 32000;
  }
}

int sw_rc072(int x){
  switch(x){
    case 258: return 26111;
    case 19: return 28566;
    case 163: return 8347;
    case 218: return 13075;
    case 65: return 17563;
    case 352: return 10686;
    case 23: return 20793;
    case 12: return 16157;
    case 199: return 9934;
    case 373: return 4881;
    case 248: return 26496;
    default: return 32000;
  }
}

int sw_rc073(int x){
  switch(x){
    case 316: return 11761;
    case 1082: return 29564;
    case -1612: return 18514;
    case 1708: return 15554;
    case 2139: return 2366;
    case 2434: return 23683;
    case -1893: return 12434;
    case 523: return 8052;
    case 3363: return 25414;
    default: return 32000;
  }
}

int sw_rc074(int x){
  switch(x){
    case 1247: return 22416;
    case 2878: return 5882;
    case 2654: return 19376;
    case 2732: return 13332;
    case -1767: return 5008;
    case -834: return 18939;
    case 3187: return 22648;
    case 1445: return 15373;
    case 3983: return 29796;
    case 3313: return 22165;
    case -386: return 4696;
    case 1808: return 17929;
    case 3750: return 27959;
    default: return 32000;
  }
}

int sw_rc075(int x){
  switch(x){
    case 86: return 21742;
    case 44: return 5679;
    case 226: return 1843;
    case 112: return 22143;
    case 206: return 25185;
    case 392: return 15190;
    case 110: return 21943;
    case 362: return 12213;
    case 162: return 17076;
    case 184: return 2779;
    case 45: return 11215;
    case 189: return 13358;
    case 56: return 18703;
    case 283: return 2815;
    case 280: return 10442;
    case 182: return 13720;
    case 163: return 11874;
    case 52: return 22691;
    default: return 32000;
  }
}

int sw_rc076(int x){
  switch(x){
    case 1818: return 12360;
    case 1795: return 11146;
    case 2016: return 14576;
    case 2761: return 27503;
    case -1314: return 11276;
    case 2164: return 19985;
    case 2228: return 28041;
    case -954: return 19536;
    case 1363: return 13324;
    case 2283: return 28050;
    case 896: return 19566;
    case 313: return 18113;
    case 998: return 8701;
    case -50: return 24094;
    case 3682: return 2831;
    case -1588: return 16057;
    default: return 32000;
  }
}

int sw_rc077(int x){
  switch(x){
    case -979: return 22102;
    case 3371: return 7147;
    case 536: return 16210;
    case 3386: return 14366;
    case 2774: return 22266;
    case -613: return 2661;
    case 1317: return 3319;
    case -503: return 23041;
    case 1411: return 13084;
    case 1466: return 1336;
    case -644: return 25593;
    case 3443: return 4639;
    case -772: return 23966;
    case -718: return 4816;
    case -58: return 14408;
    case 675: return 29510;
    case -110: return 7608;
    default: return 32000;
  }
}

int sw_rc078(int x){
  switch(x){
    case 34: return 4655;
    case 35: return 26136;
    case 31: return 16442;
    case 36: return 20308;
    case 32: return 1459;
    case 33: return 3848;
    case 28: return 7219;
    case 29: return 28676;
    case 30: return 19357;
    default: return 32000;
  }
}

int sw_rc079(int x){
  switch(x){
    case 145: return 27834;
    case 144: return 6822;
    case 143: return 1082;
    default: return 32000;
  }
}

int sw_rc080(int x){
  switch(x){
    case 57: return 23780;
    case 197: return 15892;
    case 210: return 22990;
    case 397: return 19515;
    case 396: return 19159;
    case 121: return 28517;
    case 128: return 26792;
    case 109: return 16694;
    case 114: return 1023;
    case 154: return 8474;
    case 38: return 7738;
    case 155: return 9470;
    case 173: return 10129;
    case 338: return 21539;
    case 52: return 18972;
    case 312: return 29533;
    case 303: return 5745;
    case 364: return 20385;
    case 144: return 14292;
    default: return 32000;
  }
}

int sw_rc081(int x){
  switch(x){
    case 28: return 11564;
    case 33: return 20588;
    case 29: return 15642;
    case 25: return 15852;
    case 32: return 21889;
    case 14: return 19458;
    case 21: return 13077;
    case 30: return 2004;
    case 19: return 1668;
    case 26: return 12684;
    case 20: return 24445;
    case 16: return 23015;
    case 17: return 15312;
    case 31: return 26101;
    case 18: return 6609;
    case 13: return 26060;
    case 27: return 15913;
    case 23: return 18596;
    case 15: return 2081;
    case 22: return 20237;
    case 24: return 6834;
    case 12: return 11000;
    default: return 32000;
  }
}

int sw_rc082(int x){
  switch(x){
    case 246: return 23814;
    case 108: return 20518;
    case 228: return 7979;
    case 268: return 17934;
    case 306: return 27775;
    case 101: return 25193;
    case 92: return 14162;
    case 200: return 6941;
    case 90: return 20778;
    case 71: return 27627;
    case 61: return 20115;
    case 202: return 10357;
    case 142: return 21064;
    case 167: return 18142;
    case 396: return 9015;
    default: return 32000;
  }
}

int sw_rc083(int x){
  switch(x){
    case 1979: return 14765;
    case 1956: return 20934;
    case 1074: return 10568;
    case 2474: return 29233;
    case 1105: return 6779;
    case 272: return 14783;
    case 2625: return 29795;
    case 3069: return 16369;
    case -1394: return 14248;
    case 1886: return 14631;
    case -355: return 25248;
    case 1514: return 2687;
    case 1267: return 27188;
    default: return 32000;
  }
}

int sw_rc084(int x){
  switch(x){
    case 245: return 22520;
    case 224: return 27607;
    case 131: return 26435;
    case 395: return 1944;
    case 311: return 13285;
    case 234: return 29008;
    case 182: return 17413;
    case 334: return 17504;
    case 323: return 25277;
    case 390: return 27482;
    case 116: return 1730;
    case 55: return 17788;
    case 244: return 18676;
    case 79: return 5281;
    case 265: return 16033;
    case 292: return 19232;
    default: return 32000;
  }
}

int sw_rc085(int x){
  switch(x){
    case 89: return 19584;
    case 374: return 22943;
    case 120: return 26378;
    case 242: return 1250;
    case 31: return 15009;
    case 189: return 19509;
    case 46: return 18124;
    case 144: return 27321;
    case 326: return 15086;
    case 279: return 5988;
    case 226: return 28964;
    case 58: return 11932;
    case 0: return 24220;
    case 294: return 21728;
    case 352: return 12182;
    case 301: return 21086;
    case 268: return 29218;
    case 392: return 4819;
    case 184: return 4552;
    case 276: return 27738;
    case 102: return 29396;
    case 389: return 21267;
    case 106: return 27106;
    default: return 32000;
  }
}

int sw_rc086(int x){
  switch(x){
    case 3: return 6918;
    case 63: return 26603;
    case 2: return 19708;
    default: return 32000;
  }
}

int sw_rc087(int x){
  switch(x){
    case -919: return 2259;
    case 3703: return 22663;
    case 652: return 10966;
    case 2455: return 24624;
    case -23: return 12341;
    case 3389: return 7164;
    case -336: return 14084;
    default: return 32000;
  }
}

int sw_rc088(int x){
  switch(x){
    case 150: return 1494;
    case 11: return 26004;
    case 25: return 12859;
    case 149: return 15311;
    case 26: return 3038;
    case 24: return 1242;
    case 160: return 25411;
    case 161: return 5273;
    case 148: return 13534;
    case 151: return 4984;
    case 159: return 26288;
    default: return 32000;
  }
}

int sw_rc089(int x){
  switch(x){
    case 3575: return 24893;
    case -977: return 11216;
    case 143: return 11206;
    default: return 32000;
  }
}

int sw_rc090(int x){
  switch(x){
    case 95: return 13900;
    case 121: return 9906;
    case 120: return 22195;
    case 122: return 7496;
    default: return 32000;
  }
}

int sw_rc091(int x){
  switch(x){
    case 69: return 2650;
    case 320: return 20758;
    case 202: return 11084;
    case 3: return 26566;
    case 317: return 21091;
    case 40: return 15063;
    case 108: return 12465;
    case 385: return 29650;
    case 208: return 25392;
    case 383: return 8936;
    case 55: return 21941;
    case 181: return 4885;
    case 221: return 7009;
    case 360: return 20325;
    case 261: return 12616;
    case 12: return 24797;
    case 281: return 20272;
    case 304: return 18520;
    case 163: return 2867;
    case 399: return 24361;
    default: return 32000;
  }
}

int sw_rc092(int x){
  switch(x){
    case 81: return 18295;
    case 350: return 15931;
    case 263: return 1311;
    case 197: return 27441;
    case 308: return 24502;
    case 47: return 15130;
    case 329: return 9083;
    case 295: return 13267;
    case 87: return 19327;
    case 315: return 24330;
    case 311: return 13342;
    case 120: return 9256;
    case 224: return 28054;
    case 380: return 24289;
    case 266: return 25432;
    case 162: return 24028;
    case 244: return 26785;
    case 377: return 28836;
    case 274: return 2640;
    case 343: return 20322;
    case 285: return 5720;
    case 193: return 16240;
    case 154: return 28522;
    default: return 32000;
  }
}

int sw_rc093(int x){
  switch(x){
    case 129: return 12924;
    case 124: return 7582;
    case 149: return 8260;
    case 1: return 26300;
    case 37: return 16743;
    case 169: return 24162;
    case 128: return 3388;
    case 112: return 3102;
    case 110: return 13985;
    case 122: return 7950;
    case 123: return 29790;
    case 147: return 2102;
    case 148: return 25497;
    case 111: return 8883;
    case 130: return 18439;
    case 103: return 6149;
    case 109: return 18520;
    default: return 32000;
  }
}

int sw_rc094(int x){
  switch(x){
    case 373: return 14021;
    case 105: return 1035;
    case 261: return 20154;
    case 16: return 15315;
    case 131: return 9017;
    case 88: return 9010;
    case 100: return 1192;
    case 161: return 2303;
    case 257: return 3396;
    case 311: return 28791;
    case 352: return 23362;
    case 213: return 2879;
    case 38: return 18229;
    case 282: return 4234;
    default: return 32000;
  }
}

int sw_rc095(int x){
  switch(x){
    case 569: return 19693;
    case -1014: return 22834;
    default: return 32000;
  }
}

int sw_rc096(int x){
  switch(x){
    case 571: return 15480;
    case -1279: return 11668;
    case 616: return 12535;
    case 2990: return 17272;
    case -910: return 10552;
    case 2725: return 7167;
    case 1291: return 21537;
    case 3793: return 6108;
    case 2755: return 24154;
    default: return 32000;
  }
}

int sw_rc097(int x){
  switch(x){
    case 20: return 12936;
    case 19: return 17265;
    case 21: return 4785;
    case 23: return 29021;
    case 22: return 9375;
    default: return 32000;
  }
}

int sw_rc098(int x){
  switch(x){
    case 248: return 11442;
    case 349: return 7487;
    case 167: return 23264;
    case 182: return 27241;
    case 138: return 11168;
    default: return 32000;
  }
}

int sw_rc099(int x){
  switch(x){
    case 189: return 4927;
    case 190: return 1889;
    case 116: return 28717;
    case 117: return 10779;
    case 187: return 24404;
    case 188: return 3095;
    case 132: return 16509;
    case 35: return 7560;
    case 131: return 12915;
    default: return 32000;
  }
}

int sw_rc100(int x){
  switch(x){
    case 290: return 22674;
    case 195: return 28888;
    case 90: return 22434;
    case 377: return 16813;
    case 334: return 16464;
    case 99: return 24288;
    case 236: return 1832;
    case 130: return 23993;
    case 321: return 16714;
    case 66: return 14104;
    case 127: return 14809;
    case 148: return 15656;
    case 283: return 15691;
    case 156: return 17485;
    case 201: return 9345;
    case 207: return 14820;
    case 229: return 28990;
    case 111: return 7713;
    case 394: return 26670;
    default: return 32000;
  }
}

int sw_rc101(int x){
  switch(x){
    case 27: return 4568;
    case 40: return 12979;
    case 35: return 17039;
    case 34: return 5919;
    case 30: return 3904;
    case 42: return 12697;
    case 43: return 1952;
    case 32: return 19175;
    case 29: return 5554;
    case 23: return 14061;
    case 33: return 22719;
    case 28: return 23545;
    case 41: return 6547;
    case 22: return 29790;
    case 24: return 29014;
    case 25: return 16762;
    case 36: return 28984;
    case 31: return 15754;
    case 39: return 12626;
    case 26: return 10758;
    case 37: return 27974;
    case 38: return 27897;
    case 21: return 17449;
    default: return 32000;
  }
}

int sw_rc102(int x){
  switch(x){
    case 10: return 8505;
    case 144: return 25001;
    case 334: return 5501;
    case 376: return 10388;
    case 298: return 20598;
    case 356: return 7878;
    case 47: return 6255;
    case 231: return 3939;
    case 8: return 21999;
    case 285: return 21437;
    case 214: return 19660;
    default: return 32000;
  }
}

int sw_rc103(int x){
  switch(x){
    case 33: return 5562;
    case 31: return 17769;
    case 32: return 22080;
    case 30: return 3602;
    default: return 32000;
  }
}

int sw_rc104(int x){
  switch(x){
    case 247: return 1488;
    case 391: return 13564;
    case 7: return 5255;
    case 238: return 18857;
    case 165: return 18589;
    case 52: return 21157;
    case 353: return 7592;
    case 380: return 18143;
    case 86: return 13185;
    case 39: return 21446;
    case 157: return 1208;
    case 266: return 13265;
    case 290: return 28996;
    case 30: return 22091;
    case 287: return 17492;
    default: return 32000;
  }
}

int sw_rc105(int x){
  switch(x){
    case 223: return 10983;
    case 206: return 24763;
    case 182: return 3735;
    case 105: return 2082;
    default: return 32000;
  }
}

int sw_rc106(int x){
  switch(x){
    case 18: return 13099;
    case 11: return 28433;
    case 20: return 11122;
    case 15: return 5705;
    case 16: return 11084;
    case 23: return 2482;
    case 9: return 2059;
    case 25: return 16556;
    case 26: return 24108;
    case 29: return 10225;
    case 10: return 21516;
    case 13: return 2904;
    case 32: return 7967;
    case 31: return 1513;
    case 21: return 3217;
    case 28: return 28306;
    case 12: return 2056;
    case 22: return 22503;
    case 24: return 17579;
    case 27: return 18097;
    case 17: return 4910;
    case 14: return 14536;
    case 30: return 20293;
    case 19: return 9480;
    default: return 32000;
  }
}

int sw_rc107(int x){
  switch(x){
    case 165: return 4321;
    case 191: return 14138;
    case 22: return 29382;
    case 190: return 11420;
    case 164: return 11518;
    case 189: return 10803;
    case 166: return 13084;
    case 120: return 19343;
    default: return 32000;
  }
}

int sw_rc108(int x){
  switch(x){
    case 3961: return 20951;
    case 627: return 26227;
    case -1850: return 28277;
    case -216: return 17013;
    case 231: return 4264;
    case 3874: return 14407;
    case 734: return 28767;
    case 2832: return 1560;
    case -1248: return 14043;
    case -428: return 11780;
    default: return 32000;
  }
}

int sw_rc109(int x){
  switch(x){
    case 25: return 22076;
    case 30: return 23967;
    case 32: return 15709;
    case 34: return 13730;
    case 21: return 29889;
    case 35: return 22472;
    case 36: return 26953;
    case 38: return 26858;
    case 41: return 15006;
    case 33: return 23281;
    case 26: return 28168;
    case 23: return 6205;
    case 40: return 1540;
    case 31: return 26957;
    case 24: return 14960;
    case 39: return 15530;
    case 29: return 9409;
    case 22: return 26239;
    case 28: return 19577;
    case 37: return 28532;
    case 20: return 2878;
    case 27: return 7379;
    default: return 32000;
  }
}

int sw_rc110(int x){
  switch(x){
    case 152: return 16261;
    case 153: return 8764;
    case 66: return 2898;
    case 130: return 29103;
    case 151: return 16673;
    case 154: return 24213;
    case 146: return 18395;
    case 148: return 10795;
    case 131: return 20614;
    case 132: return 12351;
    case 26: return 15722;
    case 133: return 12170;
    case 67: return 11996;
    default: return 32000;
  }
}

int sw_rc111(int x){
  switch(x){
    case 1570: return 7792;
    case 3255: return 5485;
    case 1094: return 9382;
    case -609: return 10217;
    case -615: return 2952;
    case 3860: return 6944;
    case 3701: return 16218;
    case -1137: return 16919;
    case 3647: return 10594;
    case 3446: return 15473;
    case 940: return 7426;
    case 2649: return 6094;
    case -1490: return 5991;
    case -64: return 18944;
    case -356: return 27388;
    case 352: return 20848;
    case -991: return 17664;
    case -730: return 12043;
    case -450: return 22554;
    case -214: return 18259;
    case -200: return 12407;
    case -419: return 21368;
    default: return 32000;
  }
}

int sw_rc112(int x){
  switch(x){
    case 133: return 1307;
    case 216: return 23107;
    case 120: return 2947;
    case 336: return 20120;
    case 71: return 16626;
    case 79: return 13114;
    case 350: return 28729;
    case 179: return 28561;
    case 97: return 15845;
    case 188: return 19710;
    case 393: return 11997;
    case 334: return 22268;
    case 111: return 13247;
    case 247: return 28074;
    case 152: return 29989;
    case 14: return 16913;
    case 6: return 16067;
    case 386: return 6956;
    case 132: return 7121;
    case 129: return 20156;
    case 4: return 5241;
    case 245: return 22145;
    case 236: return 3050;
    case 124: return 13178;
    default: return 32000;
  }
}

int sw_rc113(int x){
  switch(x){
    case -1926: return 23570;
    case -443: return 28108;
    case 625: return 24170;
    case 681: return 17311;
    case 3884: return 16408;
    case 1069: return 10177;
    case 661: return 3010;
    case 3786: return 14895;
    default: return 32000;
  }
}

int sw_rc114(int x){
  switch(x){
    case 17: return 13969;
    case 67: return 20382;
    case 63: return 13396;
    case 50: return 13202;
    case 51: return 29312;
    case 169: return 12326;
    case 35: return 16202;
    case 140: return 10620;
    case 34: return 19950;
    case 66: return 12945;
    case 110: return 25506;
    case 64: return 4009;
    case 168: return 29977;
    case 65: return 18991;
    case 68: return 19802;
    case 111: return 6924;
    case 55: return 2452;
    case 56: return 18654;
    case 57: return 7023;
    case 109: return 4873;
    default: return 32000;
  }
}

int sw_rc115(int x){
  switch(x){
    case 136: return 7355;
    case 280: return 7262;
    default: return 32000;
  }
}

int sw_rc116(int x){
  switch(x){
    case 135: return 8724;
    case 45: return 2408;
    case 134: return 23779;
    default: return 32000;
  }
}

int sw_rc117(int x){
  switch(x){
    case 186: return 12732;
    case 21: return 8942;
    case 18: return 11638;
    case 185: return 19068;
    case 249: return 25432;
    case 116: return 21800;
    case 65: return 26215;
    case 20: return 1761;
    case 149: return 22075;
    case 151: return 6403;
    case 148: return 5096;
    case 22: return 24253;
    case 150: return 22967;
    case 167: return 13321;
    case 19: return 21452;
    default: return 32000;
  }
}

int sw_rc118(int x){
  switch(x){
    case 2645: return 9476;
    case -834: return 20416;
    case -898: return 1441;
    case 3089: return 28412;
    case 3367: return 12930;
    case -65: return 29589;
    default: return 32000;
  }
}

int sw_rc119(int x){
  switch(x){
    case -794: return 13424;
    case 2383: return 17245;
    case 1033: return 14149;
    case 1972: return 29358;
    case 3532: return 11337;
    case 1633: return 26967;
    case 2086: return 5018;
    case 3229: return 5090;
    case 3699: return 26736;
    case -812: return 20702;
    case -978: return 19972;
    default: return 32000;
  }
}

int sw_rc120(int x){
  switch(x){
    case 80: return 16329;
    case 181: return 16053;
    default: return 32000;
  }
}

int sw_rc121(int x){
  switch(x){
    case 12: return 18494;
    case 18: return 5519;
    case -1: return 4262;
    case 3: return 7977;
    case -2: return 1187;
    case 8: return 12502;
    case 6: return 21771;
    case 19: return 16530;
    case 14: return 11903;
    case 9: return 18380;
    case 16: return 3166;
    case 11: return 13375;
    case 10: return 24222;
    case 15: return 27665;
    case 7: return 2432;
    case 5: return 23580;
    case 1: return 18949;
    case 17: return 8233;
    case 2: return 2932;
    case 13: return 21356;
    case 4: return 21207;
    case 0: return 3957;
    default: return 32000;
  }
}

int sw_rc122(int x){
  switch(x){
    case 138: return 9080;
    case 379: return 16548;
    case 53: return 23387;
    case 47: return 25902;
    case 310: return 18767;
    case 390: return 10278;
    case 291: return 27214;
    case 142: return 20274;
    case 45: return 10409;
    case 202: return 1992;
    case 108: return 11061;
    case 317: return 22278;
    case 130: return 13222;
    default: return 32000;
  }
}

int sw_rc123(int x){
  switch(x){
    case 16: return 22788;
    case 5: return 23649;
    case 12: return 11579;
    case 9: return 24257;
    case 7: return 26135;
    case 14: return 24864;
    case 10: return 22594;
    case 8: return 22301;
    case 13: return 11532;
    case 2: return 29790;
    case 11: return 29727;
    case 4: return 25699;
    case 6: return 10460;
    case 17: return 1902;
    case 3: return 15780;
    case 15: return 29369;
    default: return 32000;
  }
}

int sw_rc124(int x){
  switch(x){
    case 43: return 1131;
    case 138: return 24196;
    case 42: return 15041;
    case 117: return 24818;
    case 140: return 9305;
    case 37: return 4325;
    case 184: return 19978;
    case 48: return 18939;
    case 185: return 16632;
    case 76: return 11778;
    case 92: return 1284;
    case 115: return 5443;
    case 118: return 8097;
    case 91: return 9989;
    case 351: return 1335;
    case 139: return 14640;
    case 137: return 21353;
    case 41: return 9804;
    default: return 32000;
  }
}

int sw_rc125(int x){
  switch(x){
    case 366: return 27070;
    case 233: return 13182;
    default: return 32000;
  }
}

int sw_rc126(int x){
  switch(x){
    case -1: return 2841;
    case 11: return 6910;
    case 0: return 13928;
    case 10: return 28663;
    case 7: return 12311;
    case 9: return 9472;
    case -4: return 28103;
    case 2: return 19780;
    case 15: return 18576;
    case 12: return 16183;
    case 8: return 28817;
    case -2: return 13586;
    case 14: return 21717;
    case 6: return 2370;
    case -3: return 29791;
    case 13: return 13448;
    case 1: return 11800;
    case 5: return 9875;
    case 4: return 21574;
    case 3: return 25719;
    default: return 32000;
  }
}

int sw_rc127(int x){
  switch(x){
    case 319: return 17623;
    case 69: return 4581;
    case 18: return 9328;
    case 237: return 14143;
    case 261: return 17057;
    case 50: return 3428;
    case 325: return 21185;
    case 216: return 25325;
    case 276: return 6284;
    case 139: return 4729;
    case 389: return 6013;
    case 272: return 16850;
    case 198: return 18883;
    case 116: return 28966;
    default: return 32000;
  }
}

int sw_rc128(int x){
  switch(x){
    case 179: return 7699;
    case 160: return 10228;
    case 148: return 8999;
    case 5: return 14297;
    case 114: return 7889;
    case 4: return 25634;
    case 177: return 6579;
    case 146: return 16996;
    case 178: return 9336;
    case 161: return 16065;
    case 89: return 9719;
    case 163: return 3898;
    case 7: return 12137;
    case 6: return 12532;
    case 87: return 22767;
    case 176: return 22203;
    case 88: return 7702;
    case 162: return 21985;
    case 147: return 4483;
    default: return 32000;
  }
}

int sw_rc129(int x){
  switch(x){
    case 85: return 4120;
    case 236: return 4134;
    case 16: return 13229;
    default: return 32000;
  }
}

int sw_rc130(int x){
  switch(x){
    case 1041: return 25490;
    case 1447: return 8905;
    case 3834: return 24862;
    case 3945: return 4840;
    case 3807: return 4105;
    case 3411: return 9662;
    case 1519: return 12437;
    case -1467: return 22811;
    case -596: return 18543;
    case -179: return 4814;
    case 3817: return 28410;
    case 3902: return 16758;
    case 714: return 20919;
    case 1839: return 20407;
    case 1742: return 23941;
    case 1624: return 22186;
    case 890: return 15471;
    case 3734: return 27590;
    case -752: return 23232;
    default: return 32000;
  }
}

int sw_rc131(int x){
  switch(x){
    case 160: return 15111;
    case 29: return 27374;
    case 157: return 10354;
    case 129: return 22337;
    case 156: return 17850;
    case 34: return 13751;
    case 159: return 19608;
    case 127: return 20869;
    case 73: return 19780;
    case 162: return 8635;
    case 72: return 22479;
    case 33: return 8992;
    case 155: return 15994;
    case 128: return 27389;
    case 161: return 17825;
    case 28: return 27316;
    case 93: return 29132;
    default: return 32000;
  }
}

int sw_rc132(int x){
  switch(x){
    case -916: return 2012;
    case -1576: return 29068;
    case -95: return 24148;
    case 351: return 4346;
    case 3013: return 3835;
    default: return 32000;
  }
}

int sw_rc133(int x){
  switch(x){
    case 112: return 10404;
    case 49: return 26343;
    case 78: return 16884;
    case 5: return 14969;
    case 46: return 20064;
    case 4: return 11204;
    case 6: return 9812;
    case 147: return 3209;
    case 111: return 12554;
    case 7: return 24801;
    case 124: return 11101;
    case 149: return 12682;
    case 148: return 21505;
    case 58: return 23846;
    case 146: return 12114;
    case 48: return 13357;
    case 45: return 15771;
    case 113: return 6551;
    case 47: return 29182;
    case 77: return 25849;
    case 385: return 26592;
    default: return 32000;
  }
}

int sw_rc134(int x){
  switch(x){
    case 10: return 24341;
    case 17: return 3208;
    case 18: return 24832;
    case 13: return 9593;
    case 9: return 24205;
    case 16: return 17885;
    case 19: return 20945;
    case 20: return 28007;
    case 23: return 4212;
    case 14: return 14595;
    case 21: return 13958;
    case 11: return 26669;
    case 22: return 6991;
    case 12: return 16342;
    case 15: return 12318;
    default: return 32000;
  }
}

int sw_rc135(int x){
  switch(x){
    case 44: return 10693;
    case 38: return 10433;
    case 42: return 21820;
    case 39: return 3982;
    case 47: return 1192;
    case 50: return 15381;
    case 48: return 26618;
    case 40: return 28748;
    case 37: return 26036;
    case 41: return 21058;
    case 51: return 19118;
    case 49: return 22364;
    case 36: return 21536;
    case 46: return 22727;
    case 43: return 20687;
    case 45: return 2811;
    case 52: return 13877;
    default: return 32000;
  }
}

int sw_rc136(int x){
  switch(x){
    case 134: return 25365;
    case 232: return 9244;
    case 256: return 16496;
    default: return 32000;
  }
}

int sw_rc137(int x){
  switch(x){
    case 368: return 19646;
    case 288: return 8625;
    case 253: return 4310;
    case 188: return 28068;
    case 152: return 10939;
    case 388: return 5888;
    case 314: return 16905;
    case 99: return 2280;
    case 313: return 4527;
    case 82: return 26356;
    case 301: return 29053;
    case 335: return 9513;
    case 79: return 17166;
    case 100: return 7048;
    case 219: return 11851;
    case 365: return 8605;
    default: return 32000;
  }
}

int sw_rc138(int x){
  switch(x){
    case 2449: return 3896;
    case 1275: return 22942;
    case 1841: return 17728;
    case -1933: return 11978;
    case -1568: return 29669;
    case 2905: return 15523;
    case 1976: return 13444;
    case 1468: return 23791;
    case 2288: return 6581;
    case 934: return 19248;
    case -1262: return 4802;
    case -963: return 17235;
    default: return 32000;
  }
}

int sw_rc139(int x){
  switch(x){
    case 5: return 2950;
    case 4: return 4756;
    case 2: return 22493;
    case 7: return 11666;
    case 3: return 23178;
    case 6: return 1886;
    case 1: return 16211;
    default: return 32000;
  }
}

int sw_rc140(int x){
  switch(x){
    case 28: return 10644;
    case 142: return 21967;
    case 154: return 29968;
    case 50: return 18582;
    case 172: return 10107;
    case 60: return 2305;
    case 51: return 6537;
    case 61: return 3856;
    case 193: return 12573;
    case 173: return 21939;
    case 30: return 28513;
    case 197: return 22882;
    case 48: return 22765;
    case 62: return 28775;
    case 63: return 8959;
    case 168: return 28369;
    case 153: return 1190;
    case 49: return 2825;
    case 29: return 12261;
    default: return 32000;
  }
}

int sw_rc141(int x){
  switch(x){
    case 1: return 19985;
    case -2: return 5143;
    case 2: return 13793;
    case -1: return 7105;
    case 4: return 8240;
    case -3: return 27772;
    case 0: return 11224;
    case 3: return 25698;
    default: return 32000;
  }
}

int sw_rc142(int x){
  switch(x){
    case 398: return 12630;
    case 126: return 2000;
    case 167: return 16977;
    case 160: return 1058;
    case 149: return 22816;
    case 80: return 20993;
    case 140: return 27349;
    case 389: return 16924;
    case 292: return 22995;
    case 204: return 6746;
    case 334: return 27313;
    case 295: return 28996;
    default: return 32000;
  }
}

int sw_rc143(int x){
  switch(x){
    case 7: return 14997;
    case 8: return 3832;
    default: return 32000;
  }
}

int sw_rc144(int x){
  switch(x){
    case -2: return 6059;
    case -1: return 10944;
    case 2: return 9894;
    case 1: return 20743;
    case 0: return 3567;
    case 3: return 22234;
    default: return 32000;
  }
}

int sw_rc145(int x){
  switch(x){
    case 346: return 23007;
    case 249: return 22374;
    case 300: return 4436;
    case 65: return 21326;
    case 111: return 24461;
    case 94: return 26106;
    case 242: return 3183;
    case 155: return 4779;
    case 179: return 1499;
    case 100: return 15566;
    default: return 32000;
  }
}

int sw_rc146(int x){
  switch(x){
    case 136: return 12151;
    case 71: return 14542;
    case 4: return 2311;
    case 8: return 6741;
    case 72: return 29090;
    case 73: return 20592;
    case 70: return 4672;
    case 107: return 1979;
    case 3: return 26190;
    case 106: return 1362;
    case 7: return 2074;
    default: return 32000;
  }
}

int sw_rc147(int x){
  switch(x){
    case 28: return 5812;
    case 31: return 28760;
    case 36: return 10370;
    case 33: return 29741;
    case 34: return 8119;
    case 27: return 29343;
    case 32: return 11406;
    case 30: return 19820;
    case 35: return 11216;
    case 29: return 8144;
    default: return 32000;
  }
}

int sw_rc148(int x){
  switch(x){
    case 3: return 28191;
    case 106: return 3472;
    case 43: return 4094;
    case 42: return 9456;
    case 92: return 19164;
    case 4: return 11337;
    case 5: return 10787;
    case 6: return 27688;
    case 86: return 24176;
    case 107: return 1722;
    case 91: return 19307;
    case 1: return 1509;
    case 41: return 11867;
    case 7: return 25541;
    case 93: return 8701;
    case 95: return 11663;
    case 2: return 5372;
    case 87: return 8845;
    default: return 32000;
  }
}

int sw_rc149(int x){
  switch(x){
    case 33: return 16752;
    case 29: return 21557;
    case 30: return 1752;
    case 31: return 24647;
    case 34: return 2361;
    case 38: return 29976;
    case 36: return 3993;
    case 25: return 22958;
    case 40: return 16275;
    case 28: return 21145;
    case 32: return 6142;
    case 26: return 9074;
    case 37: return 14066;
    case 35: return 16361;
    case 39: return 5581;
    case 27: return 25257;
    default: return 32000;
  }
}

int sw_rc150(int x){
  switch(x){
    case 179: return 26057;
    case 62: return 3554;
    case 67: return 28652;
    case 91: return 11350;
    case 168: return 1821;
    case 42: return 26973;
    case 18: return 24643;
    case 65: return 22703;
    case 44: return 18814;
    case 166: return 24907;
    case 17: return 13109;
    case 165: return 4192;
    case 66: return 15085;
    case 43: return 9943;
    case 90: return 4331;
    case 167: return 20430;
    case 45: return 26942;
    default: return 32000;
  }
}

int sw_rc151(int x){
  switch(x){
    case 49: return 21213;
    case 9: return 23950;
    case 140: return 15401;
    case 53: return 17745;
    case 195: return 21831;
    case 62: return 3142;
    case 61: return 6999;
    case 63: return 25436;
    case 7: return 5966;
    case 139: return 28450;
    case 8: return 5853;
    case 193: return 21883;
    default: return 32000;
  }
}

int sw_rc152(int x){
  switch(x){
    case 361: return 20830;
    case -1259: return 24586;
    default: return 32000;
  }
}

int sw_rc153(int x){
  switch(x){
    case 44: return 4514;
    case 41: return 28317;
    case 40: return 20355;
    case 32: return 1013;
    case 38: return 12545;
    case 36: return 19847;
    case 35: return 10898;
    case 43: return 5091;
    case 37: return 10266;
    case 39: return 8636;
    case 31: return 1866;
    case 42: return 1060;
    case 34: return 8777;
    case 33: return 7581;
    default: return 32000;
  }
}

int sw_rc154(int x){
  switch(x){
    case 151: return 9986;
    case 375: return 8629;
    case 298: return 13651;
    case 69: return 7173;
    case 299: return 9026;
    case 94: return 17699;
    case 133: return 1004;
    case 222: return 12346;
    default: return 32000;
  }
}

int sw_rc155(int x){
  switch(x){
    case 27: return 28581;
    case 19: return 16531;
    case 29: return 27409;
    case 20: return 22592;
    case 21: return 20374;
    case 22: return 14906;
    case 16: return 20794;
    case 30: return 11154;
    case 18: return 5845;
    case 23: return 26193;
    case 26: return 4024;
    case 25: return 28849;
    case 24: return 6510;
    case 28: return 4563;
    case 17: return 27620;
    default: return 32000;
  }
}

int sw_rc156(int x){
  switch(x){
    case 183: return 25417;
    case 161: return 7344;
    case 153: return 25991;
    case 188: return 25216;
    case 44: return 16882;
    case 163: return 28213;
    case 107: return 5396;
    case 106: return 7671;
    case 124: return 13287;
    case 125: return 8563;
    case 141: return 22033;
    case 123: return 2566;
    case 45: return 27455;
    case 181: return 26283;
    case 43: return 29543;
    case 184: return 25225;
    case 46: return 2761;
    case 182: return 20597;
    case 105: return 7198;
    case 162: return 4746;
    default: return 32000;
  }
}

int sw_rc157(int x){
  switch(x){
    case 201: return 4167;
    case 378: return 16917;
    default: return 32000;
  }
}

int sw_rc158(int x){
  switch(x){
    case 34: return 8597;
    case 38: return 7647;
    case 39: return 1308;
    case 35: return 7286;
    case 33: return 14668;
    case 44: return 16177;
    case 30: return 9840;
    case 31: return 16039;
    case 40: return 25307;
    case 45: return 13784;
    case 36: return 25953;
    case 42: return 2160;
    case 37: return 14323;
    case 32: return 19227;
    case 41: return 3717;
    case 43: return 29940;
    default: return 32000;
  }
}

int sw_rc159(int x){
  switch(x){
    case 3458: return 4578;
    case -994: return 5604;
    case -213: return 16672;
    case 940: return 22878;
    case 1830: return 26976;
    case -490: return 9501;
    case 817: return 23848;
    case -141: return 8213;
    case -1797: return 24995;
    case 1588: return 21331;
    case -1839: return 21072;
    case -37: return 4994;
    default: return 32000;
  }
}

int sw_rc160(int x){
  switch(x){
    case 18: return 26212;
    case 24: return 13733;
    case 20: return 11050;
    case 23: return 15971;
    case 12: return 2651;
    case 22: return 7839;
    case 8: return 22892;
    case 21: return 14945;
    case 16: return 28093;
    case 19: return 24105;
    case 26: return 7393;
    case 10: return 5251;
    case 15: return 25670;
    case 9: return 29636;
    case 14: return 20221;
    case 17: return 5673;
    case 13: return 22269;
    case 11: return 12267;
    case 25: return 6848;
    default: return 32000;
  }
}

int sw_rc161(int x){
  switch(x){
    case 5: return 6074;
    case 14: return 10854;
    case 2: return 5371;
    case 17: return 1655;
    case 6: return 3942;
    case 7: return 5435;
    case 16: return 4754;
    case 4: return 29604;
    case 12: return 17603;
    case 3: return 14903;
    case 13: return 5333;
    case 8: return 15274;
    case 1: return 29620;
    case 10: return 9303;
    case 15: return 2947;
    case 11: return 10467;
    case 9: return 17262;
    default: return 32000;
  }
}

int sw_rc162(int x){
  switch(x){
    case 6: return 27736;
    case 7: return 6909;
    case 3: return 6680;
    case 2: return 24952;
    case 1: return 21979;
    case 9: return 15637;
    case 5: return 16654;
    case 8: return 3295;
    case 4: return 5912;
    case 10: return 20169;
    default: return 32000;
  }
}

int sw_rc163(int x){
  switch(x){
    case 94: return 22952;
    case 284: return 9088;
    case 365: return 26561;
    case 121: return 14244;
    case 214: return 7827;
    case 315: return 3062;
    case 190: return 6767;
    case 31: return 22782;
    case 59: return 28470;
    case 212: return 17777;
    case 289: return 2695;
    case 266: return 5425;
    case 213: return 23358;
    case 283: return 7985;
    case 240: return 27246;
    case 223: return 13892;
    case 245: return 12152;
    case 353: return 14995;
    case 185: return 25966;
    case 57: return 19723;
    default: return 32000;
  }
}

int sw_rc164(int x){
  switch(x){
    case 12: return 8232;
    case -1910: return 9462;
    case -796: return 11933;
    case 809: return 4453;
    case 1269: return 29356;
    case 895: return 17907;
    case 918: return 17263;
    case -1649: return 9405;
    default: return 32000;
  }
}

int sw_rc165(int x){
  switch(x){
    case -1269: return 16239;
    case 1507: return 16701;
    case 537: return 16584;
    case 3660: return 19643;
    case 3713: return 10164;
    case 2050: return 7849;
    case 2486: return 29435;
    case 1302: return 3877;
    case 3507: return 16941;
    case -874: return 3688;
    case -1811: return 29457;
    case 1358: return 13987;
    case -525: return 21491;
    case 1577: return 4484;
    case 3291: return 9381;
    case 1792: return 17391;
    case 2907: return 29015;
    case 624: return 22170;
    case 1528: return 22453;
    case 3153: return 7129;
    default: return 32000;
  }
}

int sw_rc166(int x){
  switch(x){
    case 149: return 22316;
    case 135: return 15950;
    case 84: return 12489;
    case 133: return 14671;
    case 60: return 21403;
    case 59: return 7193;
    case 11: return 8974;
    case 27: return 19889;
    case 132: return 22045;
    case 13: return 14717;
    case 28: return 23938;
    case 134: return 15562;
    case 83: return 15261;
    case 12: return 14100;
    default: return 32000;
  }
}

int sw_rc167(int x){
  switch(x){
    case 122: return 14376;
    case 19: return 1929;
    default: return 32000;
  }
}

int sw_rc168(int x){
  switch(x){
    case 24: return 13688;
    case -931: return 8610;
    case 3957: return 11795;
    case 680: return 4722;
    case 499: return 5894;
    case 774: return 1451;
    case -1407: return 14633;
    case 255: return 16203;
    case 3752: return 9799;
    case 3842: return 2380;
    case -1010: return 18753;
    case 2127: return 25805;
    case 2196: return 15498;
    case 2243: return 5888;
    case 1240: return 13736;
    default: return 32000;
  }
}

int sw_rc169(int x){
  switch(x){
    case 576: return 8860;
    case 1237: return 25076;
    case 973: return 1216;
    case -1121: return 11082;
    case 3074: return 18352;
    case 3395: return 1848;
    case -561: return 5257;
    default: return 32000;
  }
}

int sw_rc170(int x){
  switch(x){
    case 98: return 14912;
    case 124: return 15860;
    case 169: return 21584;
    case 121: return 6965;
    case 17: return 12230;
    case 16: return 11549;
    case 168: return 15835;
    case 14: return 1465;
    case 122: return 12383;
    case 15: return 12525;
    case 123: return 25347;
    default: return 32000;
  }
}

int sw_rc171(int x){
  switch(x){
    case 308: return 2858;
    case 192: return 16353;
    case 0: return 6294;
    case 248: return 20585;
    case 225: return 4159;
    case 96: return 21957;
    case 314: return 17017;
    case 362: return 3898;
    case 157: return 18189;
    case 125: return 26324;
    case 249: return 13991;
    case 69: return 27748;
    case 189: return 18206;
    case 393: return 2202;
    case 378: return 23820;
    case 15: return 4011;
    case 45: return 18239;
    case 89: return 13297;
    case 121: return 22845;
    case 284: return 13663;
    case 296: return 17412;
    case 399: return 9708;
    default: return 32000;
  }
}

int sw_rc172(int x){
  switch(x){
    case 1397: return 10188;
    case 1603: return 14794;
    case 1437: return 9128;
    case -123: return 19914;
    case -238: return 5363;
    case -1242: return 1811;
    case -920: return 20644;
    case 2208: return 29028;
    case -1651: return 5607;
    default: return 32000;
  }
}

int sw_rc173(int x){
  switch(x){
    case 45: return 16463;
    case 147: return 11897;
    case 37: return 9687;
    case 65: return 8414;
    case 121: return 8785;
    case 150: return 4007;
    case 46: return 4308;
    case 38: return 23248;
    case 55: return 2237;
    case 64: return 21580;
    case 75: return 8761;
    case 54: return 4037;
    case 36: return 6809;
    case 148: return 16034;
    case 56: return 19569;
    case 165: return 13088;
    case 63: return 7885;
    case 74: return 23434;
    case 149: return 16491;
    default: return 32000;
  }
}

int sw_rc174(int x){
  switch(x){
    case 0: return 27198;
    case 240: return 5851;
    case 357: return 10914;
    case 363: return 10691;
    case 298: return 9960;
    case 255: return 29259;
    case 152: return 17642;
    case 80: return 21122;
    case 393: return 11521;
    case 119: return 9624;
    case 11: return 27451;
    case 384: return 7826;
    case 366: return 12181;
    case 293: return 17060;
    case 355: return 14500;
    case 77: return 18302;
    default: return 32000;
  }
}

int sw_rc175(int x){
  switch(x){
    case 3619: return 18112;
    case -1175: return 17845;
    case -1871: return 9091;
    case 995: return 22797;
    case -1767: return 16769;
    case -1598: return 26407;
    case 268: return 24779;
    case -985: return 9657;
    case 3379: return 23029;
    case -437: return 17876;
    case 2446: return 17190;
    case 433: return 21630;
    case 1496: return 1912;
    case 2091: return 5923;
    case -435: return 21111;
    case 3182: return 2948;
    case 2289: return 17681;
    case 626: return 17311;
    case 2556: return 10043;
    case 3205: return 1963;
    case 1178: return 13039;
    case 3854: return 24462;
    default: return 32000;
  }
}

int sw_rc176(int x){
  switch(x){
    case 128: return 26854;
    case 21: return 19552;
    case 62: return 13406;
    case 49: return 20445;
    case 196: return 12960;
    case 166: return 13974;
    case 195: return 28359;
    case 23: return 2188;
    case 50: return 17917;
    case 28: return 18269;
    case 168: return 23338;
    case 16: return 6752;
    case 165: return 4748;
    case 197: return 16263;
    case 22: return 6528;
    case 29: return 20457;
    case 63: return 27513;
    case 20: return 18373;
    case 129: return 20893;
    case 127: return 17227;
    case 64: return 10227;
    default: return 32000;
  }
}

int sw_rc177(int x){
  switch(x){
    case 2489: return 17779;
    case 941: return 24319;
    case 3149: return 18936;
    case -1888: return 29464;
    case 611: return 13356;
    case 3568: return 2396;
    case 661: return 6614;
    case -1023: return 11739;
    case 2207: return 11902;
    case 2020: return 5419;
    case 3533: return 8390;
    case 3842: return 5430;
    case -704: return 19680;
    case 2896: return 26894;
    default: return 32000;
  }
}

int sw_rc178(int x){
  switch(x){
    case 47: return 28392;
    case 36: return 28653;
    case 45: return 7688;
    case 42: return 14442;
    case 40: return 22056;
    case 35: return 2702;
    case 46: return 24408;
    case 48: return 8940;
    case 41: return 9510;
    case 38: return 27133;
    case 44: return 20278;
    case 34: return 19871;
    case 43: return 25429;
    case 39: return 9970;
    case 37: return 2571;
    default: return 32000;
  }
}

int sw_rc179(int x){
  switch(x){
    case 6: return 20094;
    case 20: return 9982;
    case 12: return 11174;
    case 3: return 22289;
    case 2: return 14334;
    case 15: return 29533;
    case 7: return 25158;
    case 14: return 18404;
    case 17: return 24846;
    case 4: return 26862;
    case 11: return 13403;
    case 9: return 7558;
    case 13: return 19511;
    case 10: return 12895;
    case 18: return 28407;
    case 8: return 25743;
    case 19: return 11069;
    case 5: return 17086;
    case 16: return 20506;
    case 1: return 26845;
    default: return 32000;
  }
}

int sw_rc180(int x){
  switch(x){
    case 75: return 25073;
    case 160: return 22927;
    case 238: return 25527;
    case 74: return 9502;
    case 152: return 21011;
    case 321: return 24672;
    case 43: return 17474;
    default: return 32000;
  }
}

int sw_rc181(int x){
  switch(x){
    case 434: return 25254;
    case -1754: return 2293;
    case -1232: return 11050;
    case 1481: return 13799;
    case 1361: return 14854;
    case 901: return 13725;
    case -1870: return 12396;
    case 3842: return 26325;
    case 936: return 9691;
    case 315: return 5107;
    case 2398: return 6540;
    case -222: return 24242;
    case 1574: return 23845;
    case -1101: return 2874;
    case 2628: return 12767;
    case 1301: return 28492;
    case 3740: return 17114;
    case -1538: return 25701;
    case 2718: return 5276;
    case 1494: return 9973;
    case -1572: return 1218;
    default: return 32000;
  }
}

int sw_rc182(int x){
  switch(x){
    case 7: return 17115;
    case 14: return 9576;
    case 5: return 28955;
    case 12: return 11767;
    case 13: return 27702;
    case 9: return 5212;
    case 4: return 6085;
    case 10: return 18333;
    case 8: return 29917;
    case 11: return 14520;
    case 3: return 22347;
    case 6: return 3065;
    default: return 32000;
  }
}

int sw_rc183(int x){
  switch(x){
    case 165: return 11362;
    case 166: return 20830;
    default: return 32000;
  }
}

int sw_rc184(int x){
  switch(x){
    case 826: return 28856;
    case 845: return 22143;
    case -1288: return 12569;
    case -901: return 28857;
    case 171: return 19845;
    case 1784: return 2946;
    case -924: return 14747;
    case 39: return 11915;
    case 93: return 13638;
    case 3113: return 12759;
    case -424: return 6323;
    case 2171: return 9592;
    case 3305: return 6587;
    case 688: return 18253;
    case 460: return 28400;
    default: return 32000;
  }
}

int sw_rc185(int x){
  switch(x){
    case 10: return 8779;
    case 6: return 23560;
    case 15: return 17341;
    case 9: return 27372;
    case 13: return 15669;
    case 4: return 16541;
    case 17: return 11412;
    case 11: return 28143;
    case 7: return 27275;
    case 5: return 21615;
    case 16: return 28870;
    case 14: return 6373;
    case 12: return 22520;
    case 19: return 26271;
    case 18: return 7386;
    case 8: return 13208;
    default: return 32000;
  }
}

int sw_rc186(int x){
  switch(x){
    case 73: return 3923;
    case 28: return 8075;
    case 27: return 28133;
    case 71: return 5925;
    case 30: return 14845;
    case 72: return 21456;
    case 29: return 24168;
    case 74: return 5640;
    case 163: return 12762;
    case 164: return 26534;
    case 165: return 7259;
    case 115: return 6803;
    default: return 32000;
  }
}

int sw_rc187(int x){
  switch(x){
    case 65: return 12374;
    case 66: return 20884;
    default: return 32000;
  }
}

int sw_rc188(int x){
  switch(x){
    case 32: return 18600;
    case 33: return 23139;
    case 29: return 2035;
    case 30: return 9927;
    case 34: return 24404;
    case 37: return 8999;
    case 35: return 1897;
    case 31: return 18686;
    case 36: return 6183;
    case 38: return 16987;
    default: return 32000;
  }
}

int sw_rc189(int x){
  switch(x){
    case 30: return 28536;
    case 31: return 17771;
    default: return 32000;
  }
}

int sw_rc190(int x){
  switch(x){
    case 24: return 28318;
    case 21: return 10576;
    case 14: return 11100;
    case 16: return 22205;
    case 19: return 20568;
    case 20: return 10129;
    case 15: return 11349;
    case 22: return 15137;
    case 23: return 10473;
    case 17: return 8397;
    case 25: return 17103;
    case 18: return 8230;
    default: return 32000;
  }
}

int sw_rc191(int x){
  switch(x){
    case 373: return 22803;
    case 399: return 1226;
    case 70: return 28237;
    case 3: return 18310;
    case 338: return 19026;
    case 93: return 16472;
    case 398: return 10426;
    case 92: return 14923;
    case 64: return 17362;
    case 267: return 6198;
    case 79: return 7861;
    case 264: return 17994;
    case 197: return 4640;
    case 273: return 24539;
    case 271: return 26552;
    case 327: return 22381;
    case 119: return 9893;
    case 259: return 24671;
    case 238: return 4097;
    case 100: return 11418;
    case 169: return 4296;
    default: return 32000;
  }
}

int sw_rc192(int x){
  switch(x){
    case 11: return 16175;
    case 17: return 28373;
    case 13: return 6315;
    case 20: return 22181;
    case 14: return 2940;
    case 9: return 13510;
    case 12: return 24058;
    case 19: return 25785;
    case 21: return 24926;
    case 15: return 4604;
    case 10: return 16480;
    case 16: return 14917;
    case 22: return 27447;
    case 24: return 2045;
    case 23: return 23333;
    case 18: return 24758;
    case 25: return 26762;
    default: return 32000;
  }
}

int sw_rc193(int x){
  switch(x){
    case 20: return 19145;
    case 24: return 2378;
    case 25: return 8501;
    case 21: return 27780;
    case 22: return 26663;
    case 23: return 6905;
    default: return 32000;
  }
}

int sw_rc194(int x){
  switch(x){
    case 130: return 21287;
    case 239: return 9396;
    case 315: return 11657;
    case 342: return 28265;
    case 60: return 29793;
    case 303: return 19393;
    case 250: return 17091;
    case 153: return 16284;
    case 119: return 18716;
    case 4: return 20935;
    case 272: return 28604;
    case 190: return 4218;
    case 211: return 14648;
    case 29: return 16040;
    default: return 32000;
  }
}

int sw_rc195(int x){
  switch(x){
    case -1913: return 5599;
    case 3134: return 24895;
    default: return 32000;
  }
}

int sw_rc196(int x){
  switch(x){
    case 99: return 10701;
    case 161: return 6907;
    case 52: return 12561;
    case 156: return 15859;
    case 98: return 20939;
    case 51: return 26135;
    case 162: return 18078;
    case 195: return 8612;
    case 13: return 6011;
    case 172: return 13683;
    case 137: return 23645;
    case 9: return 2806;
    case 29: return 27923;
    case 8: return 27905;
    case 97: return 18658;
    case 173: return 9409;
    case 100: return 13317;
    case 14: return 14841;
    case 155: return 7958;
    default: return 32000;
  }
}

int sw_rc197(int x){
  switch(x){
    case 98: return 17049;
    case 136: return 28656;
    case 99: return 8777;
    case 29: return 15641;
    case 137: return 25491;
    case 28: return 27294;
    case 43: return 26187;
    case 44: return 22682;
    case 27: return 16750;
    case 138: return 16326;
    case 176: return 8278;
    case 42: return 2420;
    case 175: return 1714;
    case 41: return 20487;
    default: return 32000;
  }
}

int sw_rc198(int x){
  switch(x){
    case -140: return 25282;
    case 3349: return 21741;
    case -98: return 7742;
    case 2577: return 1855;
    default: return 32000;
  }
}

int sw_rc199(int x){
  switch(x){
    case 17: return 9712;
    case 16: return 7809;
    case 18: return 26371;
    case 15: return 15900;
    default: return 32000;
  }
}

int sw_rc200(int x){
  switch(x){
    case 16: return 1462;
    case 14: return 20522;
    case 12: return 1884;
    case 13: return 14219;
    case 11: return 12653;
    case 15: return 12581;
    case 17: return 10290;
    default: return 32000;
  }
}

int sw_rc201(int x){
  switch(x){
    case 188: return 18241;
    case 7: return 21644;
    case 277: return 19238;
    case 356: return 8290;
    case 366: return 28501;
    case 173: return 25691;
    case 65: return 12800;
    case 30: return 18723;
    case 357: return 29052;
    case 245: return 19952;
    case 36: return 11524;
    case 191: return 18164;
    case 121: return 1459;
    default: return 32000;
  }
}

int sw_rc202(int x){
  switch(x){
    case 161: return 21816;
    case 182: return 18843;
    case 75: return 22684;
    case 77: return 15796;
    case 134: return 1967;
    case 164: return 16055;
    case 132: return 28770;
    case 199: return 22404;
    case 163: return 5493;
    case 133: return 20483;
    case 162: return 8501;
    case 74: return 10004;
    case 76: return 14844;
    default: return 32000;
  }
}

int sw_rc203(int x){
  switch(x){
    case 5: return 9390;
    case 7: return 24149;
    case 4: return 20177;
    case 9: return 20347;
    case 6: return 7741;
    case 8: return 13240;
    default: return 32000;
  }
}

int sw_rc204(int x){
  switch(x){
    case 79: return 21417;
    case 123: return 4888;
    case 6: return 4218;
    case 124: return 6566;
    case 167: return 25172;
    case 166: return 4835;
    case 39: return 29006;
    case 5: return 15356;
    case 40: return 13254;
    case 10: return 29793;
    case 122: return 17522;
    case 125: return 28052;
    case 151: return 27830;
    case 152: return 20144;
    default: return 32000;
  }
}

int sw_rc205(int x){
  switch(x){
    case 307: return 16403;
    case 41: return 19786;
    case 127: return 4267;
    case 205: return 1589;
    case 244: return 28412;
    default: return 32000;
  }
}

int sw_rc206(int x){
  switch(x){
    case -1708: return 9158;
    case 2657: return 28271;
    case 2558: return 9841;
    case -1289: return 6686;
    case -525: return 24658;
    case -1925: return 21289;
    case 1158: return 26431;
    case 1040: return 4606;
    case -954: return 6115;
    case 1885: return 7942;
    case 149: return 11542;
    case 2191: return 28428;
    case -1920: return 8665;
    case 1843: return 9368;
    case -11: return 5836;
    case -1406: return 10719;
    case -1890: return 13481;
    default: return 32000;
  }
}

int sw_rc207(int x){
  switch(x){
    case 3726: return 17571;
    case 3052: return 12203;
    case 1703: return 23869;
    case 3643: return 14403;
    case 1613: return 12744;
    case 2499: return 10973;
    case 1623: return 28673;
    case 464: return 10197;
    case 702: return 4056;
    case 384: return 11428;
    case 3909: return 12101;
    case -1182: return 19717;
    case 3902: return 14426;
    case 3191: return 22152;
    case 1271: return 5284;
    case 1903: return 6333;
    case 1918: return 13863;
    case 1152: return 26352;
    case 2878: return 19331;
    case 2755: return 28008;
    case 813: return 11392;
    case -1725: return 22617;
    case 3889: return 2206;
    default: return 32000;
  }
}

int sw_rc208(int x){
  switch(x){
    case 210: return 10402;
    case 53: return 1866;
    case 303: return 27442;
    case 188: return 14346;
    case 286: return 5812;
    case 142: return 13221;
    case 261: return 20527;
    case 269: return 11976;
    case 307: return 11279;
    case 138: return 10620;
    case 353: return 20439;
    case 265: return 28626;
    case 49: return 24953;
    case 6: return 10338;
    case 391: return 27238;
    case 86: return 6982;
    case 311: return 8594;
    case 329: return 7120;
    case 258: return 28866;
    case 125: return 23613;
    case 335: return 4987;
    default: return 32000;
  }
}

int sw_rc209(int x){
  switch(x){
    case 363: return 10202;
    case 344: return 6588;
    case 95: return 24852;
    case 87: return 26384;
    case 108: return 8339;
    case 52: return 25157;
    case 243: return 26226;
    case 354: return 6387;
    case 279: return 25397;
    case 218: return 27198;
    case 199: return 16147;
    case 215: return 13246;
    case 245: return 6565;
    case 356: return 22809;
    case 73: return 24770;
    case 186: return 9488;
    case 237: return 18178;
    default: return 32000;
  }
}

int sw_rc210(int x){
  switch(x){
    case -374: return 11508;
    case 3148: return 19752;
    case 500: return 18361;
    case 3461: return 2757;
    case 1335: return 27189;
    default: return 32000;
  }
}

int sw_rc211(int x){
  switch(x){
    case 3924: return 16636;
    case -1200: return 26563;
    case 608: return 10873;
    case 780: return 3337;
    case 41: return 7727;
    case -1875: return 17150;
    case 2380: return 13579;
    case -407: return 10411;
    case 1977: return 22692;
    case 1079: return 11644;
    case -1061: return 27094;
    case -1139: return 26910;
    case 936: return 21339;
    case 2663: return 3943;
    case 743: return 10115;
    case 1082: return 14937;
    case 692: return 6718;
    case 3450: return 1321;
    case -1600: return 19013;
    case 1488: return 17488;
    default: return 32000;
  }
}

int sw_rc212(int x){
  switch(x){
    case 1395: return 25365;
    case 2617: return 23314;
    case 2520: return 28168;
    case 1190: return 3852;
    case -942: return 19825;
    default: return 32000;
  }
}

int sw_rc213(int x){
  switch(x){
    case 168: return 6711;
    case 327: return 10124;
    case 183: return 22043;
    case 164: return 16028;
    case 11: return 27505;
    case 178: return 9162;
    case 90: return 25844;
    case 144: return 14006;
    case 25: return 21291;
    case 252: return 7186;
    case 210: return 6699;
    case 264: return 1438;
    case 176: return 14349;
    case 375: return 6706;
    case 34: return 8465;
    case 224: return 21013;
    case 287: return 8486;
    case 180: return 2824;
    default: return 32000;
  }
}

int sw_rc214(int x){
  switch(x){
    case -1637: return 2443;
    case 2608: return 11851;
    case 3117: return 5090;
    case 23: return 20487;
    case 3141: return 25486;
    case 3296: return 9937;
    case 746: return 13168;
    case -1842: return 17616;
    case -7: return 19177;
    case 824: return 25935;
    case -974: return 12148;
    case 2116: return 7625;
    case 3968: return 4103;
    case -1241: return 27633;
    case 1016: return 22510;
    case 930: return 26346;
    case 3410: return 29782;
    case 2467: return 3863;
    case -1949: return 14346;
    case 2818: return 10880;
    case 1871: return 13087;
    default: return 32000;
  }
}

int sw_rc215(int x){
  switch(x){
    case 48: return 26348;
    case 59: return 3353;
    case 45: return 22078;
    case 61: return 25921;
    case 60: return 17080;
    case 132: return 4732;
    case 62: return 10489;
    default: return 32000;
  }
}

int sw_rc216(int x){
  switch(x){
    case -1043: return 9705;
    case 1805: return 18149;
    default: return 32000;
  }
}

int sw_rc217(int x){
  switch(x){
    case 15: return 22284;
    case 4: return 29169;
    case 3: return 29578;
    case 5: return 1209;
    case 13: return 28959;
    case 22: return 24578;
    case 9: return 29036;
    case 10: return 26502;
    case 0: return 26637;
    case 20: return 16175;
    case 18: return 13744;
    case 17: return 22401;
    case -1: return 1239;
    case 16: return 25745;
    case 14: return 17810;
    case 12: return 14186;
    case 21: return 1263;
    case 2: return 6349;
    case 7: return 3469;
    case 8: return 8493;
    case 19: return 17934;
    case 1: return 10371;
    case 6: return 17621;
    case 11: return 17423;
    default: return 32000;
  }
}

int sw_rc218(int x){
  switch(x){
    case 272: return 8745;
    case 245: return 9040;
    case 131: return 8046;
    case 281: return 3584;
    default: return 32000;
  }
}

int sw_rc219(int x){
  switch(x){
    case 4: return 5220;
    case 63: return 25974;
    case 119: return 14497;
    case 320: return 21788;
    case 380: return 11988;
    case 299: return 18509;
    case 48: return 17866;
    case 79: return 16769;
    case 173: return 11829;
    case 223: return 7247;
    case 144: return 11125;
    case 71: return 9606;
    case 274: return 22040;
    case 17: return 19767;
    case 357: return 19367;
    case 59: return 16622;
    case 242: return 15595;
    case 359: return 11236;
    case 172: return 25249;
    case 284: return 3581;
    case 99: return 5065;
    case 126: return 25928;
    default: return 32000;
  }
}

int sw_rc220(int x){
  switch(x){
    case 276: return 16435;
    case 116: return 14649;
    case 125: return 13218;
    case 39: return 3108;
    case 181: return 6228;
    case 321: return 5807;
    case 75: return 6828;
    case 236: return 17214;
    case 269: return 18441;
    case 71: return 4922;
    case 207: return 1894;
    case 260: return 28406;
    case 272: return 2050;
    default: return 32000;
  }
}

int sw_rc221(int x){
  switch(x){
    case 79: return 2096;
    case 14: return 5512;
    case 102: return 11062;
    default: return 32000;
  }
}

int sw_rc222(int x){
  switch(x){
    case 200: return 12839;
    case 119: return 15833;
    case 131: return 15130;
    case 130: return 11562;
    case 42: return 7285;
    case 132: return 16838;
    case 18: return 10784;
    case 17: return 29182;
    case 43: return 13529;
    case 202: return 27158;
    case 201: return 23919;
    case 41: return 6938;
    default: return 32000;
  }
}

int sw_rc223(int x){
  switch(x){
    case 145: return 12137;
    case 358: return 19315;
    case 399: return 29911;
    case 123: return 23924;
    case 226: return 26839;
    case 129: return 2528;
    case 207: return 16009;
    case 113: return 24928;
    case 167: return 25572;
    case 84: return 19692;
    case 306: return 25853;
    case 137: return 5237;
    case 318: return 2412;
    case 144: return 11656;
    case 335: return 21206;
    case 190: return 10290;
    case 44: return 16097;
    case 49: return 8909;
    case 191: return 11469;
    case 186: return 12223;
    case 12: return 20197;
    case 82: return 13269;
    case 262: return 29783;
    default: return 32000;
  }
}

int sw_rc224(int x){
  switch(x){
    case -941: return 11991;
    case 506: return 16537;
    case 1725: return 7429;
    case -1393: return 20188;
    case -638: return 12552;
    case 1027: return 15481;
    case -1336: return 14602;
    case 947: return 13325;
    case 283: return 9963;
    case 913: return 20570;
    case 1278: return 26430;
    case 1722: return 11743;
    case 3115: return 17551;
    case 1099: return 11213;
    case 2705: return 9041;
    case 1776: return 20429;
    case 1072: return 16298;
    case 3331: return 2855;
    case -437: return 2878;
    case 498: return 11358;
    case 2619: return 13241;
    case -962: return 8208;
    case 3424: return 7295;
    case 1353: return 13202;
    default: return 32000;
  }
}

int sw_rc225(int x){
  switch(x){
    case 230: return 21256;
    case 342: return 23874;
    case 262: return 10277;
    case 292: return 4930;
    case 133: return 3630;
    case 384: return 3013;
    case 43: return 25242;
    case 54: return 21591;
    case 275: return 6638;
    case 25: return 2850;
    case 313: return 15756;
    case 141: return 28312;
    case 367: return 23383;
    case 265: return 9561;
    case 124: return 8808;
    case 121: return 27688;
    case 51: return 22574;
    case 72: return 5634;
    case 19: return 20655;
    case 355: return 19140;
    case 125: return 27405;
    case 56: return 28324;
    default: return 32000;
  }
}

int sw_rc226(int x){
  switch(x){
    case 26: return 16561;
    case 31: return 15484;
    case 28: return 1486;
    case 34: return 18356;
    case 33: return 21697;
    case 27: return 7050;
    case 25: return 24294;
    case 29: return 1973;
    case 30: return 25261;
    case 32: return 6171;
    default: return 32000;
  }
}

int sw_rc227(int x){
  switch(x){
    case 19: return 10734;
    case 16: return 7790;
    case 15: return 16614;
    case 156: return 3925;
    case 134: return 4853;
    case 14: return 6807;
    case 129: return 4459;
    case 132: return 27709;
    case 144: return 28343;
    case 13: return 29820;
    case 143: return 1937;
    case 135: return 18068;
    case 118: return 29033;
    case 246: return 27680;
    case 160: return 19485;
    case 130: return 7332;
    case 159: return 12519;
    case 136: return 3938;
    case 131: return 11343;
    case 161: return 5218;
    default: return 32000;
  }
}

int sw_rc228(int x){
  switch(x){
    case 51: return 7742;
    case 39: return 9290;
    case 41: return 10269;
    case 45: return 6662;
    case 54: return 12054;
    case 43: return 17934;
    case 47: return 8990;
    case 58: return 21611;
    case 55: return 3792;
    case 44: return 29879;
    case 52: return 13099;
    case 50: return 29711;
    case 49: return 11987;
    case 57: return 23163;
    case 59: return 9705;
    case 48: return 18816;
    case 42: return 26333;
    case 46: return 26043;
    case 56: return 5308;
    case 38: return 28572;
    case 40: return 12712;
    case 60: return 22599;
    case 53: return 6042;
    default: return 32000;
  }
}

int sw_rc229(int x){
  switch(x){
    case 3357: return 17257;
    case 1998: return 21616;
    case 3461: return 28342;
    case 2238: return 29797;
    case 3983: return 14458;
    case 3530: return 21585;
    case -304: return 19819;
    case 3807: return 23115;
    case -627: return 2691;
    case 2761: return 19768;
    case 2834: return 21896;
    case 278: return 26192;
    case 1624: return 7076;
    case 1049: return 7703;
    case 3018: return 2846;
    case 3616: return 9976;
    case 70: return 23851;
    case -36: return 28008;
    case 3974: return 27360;
    case 1960: return 1341;
    case 3196: return 19442;
    case -1629: return 29719;
    case 2810: return 26350;
    default: return 32000;
  }
}

int sw_rc230(int x){
  switch(x){
    case 1862: return 12977;
    case 595: return 2210;
    case 1045: return 27132;
    case -1100: return 10083;
    case 1677: return 4441;
    case -197: return 11271;
    case 2869: return 20273;
    case 2848: return 10176;
    case -1745: return 20840;
    case -1944: return 29561;
    case -590: return 26820;
    case 2375: return 18599;
    case -505: return 8322;
    case -1001: return 21989;
    case -1118: return 20821;
    case -1350: return 11219;
    case -112: return 20773;
    case 3536: return 12674;
    case 711: return 21415;
    case 110: return 21650;
    default: return 32000;
  }
}

int sw_rc231(int x){
  switch(x){
    case 3: return 23489;
    case 13: return 25282;
    case -3: return 29453;
    case 5: return 9785;
    case 9: return 23609;
    case 11: return 10449;
    case -2: return 22015;
    case 10: return 24666;
    case -1: return 14567;
    case 2: return 6185;
    case 12: return 4511;
    case 4: return 13881;
    case 6: return 5121;
    case 8: return 27332;
    case 1: return 14497;
    case 0: return 11595;
    case 7: return 9511;
    default: return 32000;
  }
}

int sw_rc232(int x){
  switch(x){
    case 19: return 24659;
    case 20: return 16569;
    case 22: return 14877;
    case 25: return 24149;
    case 27: return 6009;
    case 28: return 14539;
    case 31: return 2151;
    case 30: return 22743;
    case 29: return 15659;
    case 35: return 16565;
    case 24: return 18996;
    case 33: return 7011;
    case 32: return 21582;
    case 23: return 6059;
    case 34: return 16629;
    case 21: return 15397;
    case 26: return 22844;
    default: return 32000;
  }
}

int sw_rc233(int x){
  switch(x){
    case 105: return 23238;
    case 106: return 4040;
    case 117: return 9308;
    case 57: return 4871;
    case 157: return 20138;
    case 104: return 27433;
    case 116: return 24523;
    case 56: return 16642;
    default: return 32000;
  }
}

int sw_rc234(int x){
  switch(x){
    case 306: return 20945;
    case 3360: return 23902;
    case -213: return 14075;
    case 3462: return 23940;
    case 405: return 28332;
    case -1538: return 9064;
    case 1491: return 18296;
    case 1223: return 16830;
    case 2300: return 27144;
    case -340: return 2978;
    case 556: return 19766;
    case -641: return 18857;
    case 917: return 22130;
    case 299: return 21108;
    case -337: return 8187;
    case 2869: return 6218;
    case 1576: return 8131;
    case 2319: return 7324;
    default: return 32000;
  }
}

int sw_rc235(int x){
  switch(x){
    case -1222: return 10654;
    case 809: return 26501;
    case -1485: return 3374;
    case 1790: return 9512;
    case 131: return 19565;
    case 3016: return 4943;
    case 3960: return 9695;
    case 875: return 4885;
    case 1746: return 20279;
    case -2: return 29977;
    case 3196: return 9578;
    case 3355: return 21329;
    case 1353: return 29884;
    case 883: return 3588;
    case 1332: return 6131;
    case 3539: return 17494;
    case 821: return 3426;
    default: return 32000;
  }
}

int sw_rc236(int x){
  switch(x){
    case 9: return 8899;
    case 11: return 13057;
    case 12: return 2968;
    case 16: return 28818;
    case 18: return 9526;
    case 14: return 9796;
    case 17: return 7149;
    case 13: return 20814;
    case 20: return 21229;
    case 21: return 11963;
    case 15: return 13696;
    case 19: return 17863;
    case 10: return 7775;
    default: return 32000;
  }
}

int sw_rc237(int x){
  switch(x){
    case 10: return 9969;
    case 9: return 15615;
    case 8: return 26251;
    case 7: return 11019;
    default: return 32000;
  }
}

int sw_rc238(int x){
  switch(x){
    case 198: return 16466;
    case 70: return 25171;
    case 172: return 8675;
    case 197: return 22094;
    case 69: return 9812;
    case 24: return 15934;
    case 200: return 12589;
    case 80: return 23314;
    case 199: return 8653;
    default: return 32000;
  }
}

int sw_rc239(int x){
  switch(x){
    case 33: return 21323;
    case 35: return 10913;
    case 36: return 7327;
    case 32: return 17373;
    case 30: return 19084;
    case 28: return 17410;
    case 31: return 4173;
    case 29: return 14626;
    case 34: return 11300;
    default: return 32000;
  }
}
