/* wb-blockorder grid -- GENERATED by gen_grid.py, do not hand-edit. */

/* lane w-read-r8, read R8 (block emission order). */



int sw_dense02(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    default: return 997;
  }
}

int sw_dense03(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    case 2: return 149;
    default: return 997;
  }
}

int sw_dense04(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    case 2: return 149;
    case 3: return 307;
    default: return 997;
  }
}

int sw_dense05(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    case 2: return 149;
    case 3: return 307;
    case 4: return 163;
    default: return 997;
  }
}

int sw_dense06(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    case 2: return 149;
    case 3: return 307;
    case 4: return 163;
    case 5: return 281;
    default: return 997;
  }
}

int sw_dense07(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    case 2: return 149;
    case 3: return 307;
    case 4: return 163;
    case 5: return 281;
    case 6: return 199;
    default: return 997;
  }
}

int sw_dense08(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    case 2: return 149;
    case 3: return 307;
    case 4: return 163;
    case 5: return 281;
    case 6: return 199;
    case 7: return 353;
    default: return 997;
  }
}

int sw_dense09(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    case 2: return 149;
    case 3: return 307;
    case 4: return 163;
    case 5: return 281;
    case 6: return 199;
    case 7: return 353;
    case 8: return 173;
    default: return 997;
  }
}

int sw_dense10(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    case 2: return 149;
    case 3: return 307;
    case 4: return 163;
    case 5: return 281;
    case 6: return 199;
    case 7: return 353;
    case 8: return 173;
    case 9: return 269;
    default: return 997;
  }
}

int sw_dense11(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    case 2: return 149;
    case 3: return 307;
    case 4: return 163;
    case 5: return 281;
    case 6: return 199;
    case 7: return 353;
    case 8: return 173;
    case 9: return 269;
    case 10: return 191;
    default: return 997;
  }
}

int sw_dense12(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    case 2: return 149;
    case 3: return 307;
    case 4: return 163;
    case 5: return 281;
    case 6: return 199;
    case 7: return 353;
    case 8: return 173;
    case 9: return 269;
    case 10: return 191;
    case 11: return 331;
    default: return 997;
  }
}

int sw_dense13(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    case 2: return 149;
    case 3: return 307;
    case 4: return 163;
    case 5: return 281;
    case 6: return 199;
    case 7: return 353;
    case 8: return 173;
    case 9: return 269;
    case 10: return 191;
    case 11: return 331;
    case 12: return 157;
    default: return 997;
  }
}

int sw_dense14(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    case 2: return 149;
    case 3: return 307;
    case 4: return 163;
    case 5: return 281;
    case 6: return 199;
    case 7: return 353;
    case 8: return 173;
    case 9: return 269;
    case 10: return 191;
    case 11: return 331;
    case 12: return 157;
    case 13: return 293;
    default: return 997;
  }
}

int sw_dense15(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    case 2: return 149;
    case 3: return 307;
    case 4: return 163;
    case 5: return 281;
    case 6: return 199;
    case 7: return 353;
    case 8: return 173;
    case 9: return 269;
    case 10: return 191;
    case 11: return 331;
    case 12: return 157;
    case 13: return 293;
    case 14: return 179;
    default: return 997;
  }
}

int sw_dense16(int x){
  switch(x){
    case 0: return 137;
    case 1: return 211;
    case 2: return 149;
    case 3: return 307;
    case 4: return 163;
    case 5: return 281;
    case 6: return 199;
    case 7: return 353;
    case 8: return 173;
    case 9: return 269;
    case 10: return 191;
    case 11: return 331;
    case 12: return 157;
    case 13: return 293;
    case 14: return 179;
    case 15: return 317;
    default: return 997;
  }
}

int sw_scram04(int x){
  switch(x){
    case 1: return 211;
    case 3: return 307;
    case 2: return 149;
    case 0: return 137;
    default: return 997;
  }
}

int sw_scram05(int x){
  switch(x){
    case 1: return 211;
    case 3: return 307;
    case 4: return 163;
    case 2: return 149;
    case 0: return 137;
    default: return 997;
  }
}

int sw_scram06(int x){
  switch(x){
    case 1: return 211;
    case 3: return 307;
    case 5: return 281;
    case 4: return 163;
    case 2: return 149;
    case 0: return 137;
    default: return 997;
  }
}

int sw_scram07(int x){
  switch(x){
    case 1: return 211;
    case 3: return 307;
    case 5: return 281;
    case 6: return 199;
    case 4: return 163;
    case 2: return 149;
    case 0: return 137;
    default: return 997;
  }
}

int sw_scram08(int x){
  switch(x){
    case 1: return 211;
    case 3: return 307;
    case 5: return 281;
    case 7: return 353;
    case 6: return 199;
    case 4: return 163;
    case 2: return 149;
    case 0: return 137;
    default: return 997;
  }
}

int sw_scram12(int x){
  switch(x){
    case 1: return 211;
    case 3: return 307;
    case 5: return 281;
    case 7: return 353;
    case 9: return 269;
    case 11: return 331;
    case 10: return 191;
    case 8: return 173;
    case 6: return 199;
    case 4: return 163;
    case 2: return 149;
    case 0: return 137;
    default: return 997;
  }
}

int sw_scram13(int x){
  switch(x){
    case 1: return 211;
    case 3: return 307;
    case 5: return 281;
    case 7: return 353;
    case 9: return 269;
    case 11: return 331;
    case 12: return 157;
    case 10: return 191;
    case 8: return 173;
    case 6: return 199;
    case 4: return 163;
    case 2: return 149;
    case 0: return 137;
    default: return 997;
  }
}

int sw_scram16(int x){
  switch(x){
    case 1: return 211;
    case 3: return 307;
    case 5: return 281;
    case 7: return 353;
    case 9: return 269;
    case 11: return 331;
    case 13: return 293;
    case 15: return 317;
    case 14: return 179;
    case 12: return 157;
    case 10: return 191;
    case 8: return 173;
    case 6: return 199;
    case 4: return 163;
    case 2: return 149;
    case 0: return 137;
    default: return 997;
  }
}

int sw_sparse04(int x){
  switch(x){
    case 3: return 137;
    case 9: return 211;
    case 14: return 149;
    case 21: return 307;
    default: return 997;
  }
}

int sw_sparse06(int x){
  switch(x){
    case 3: return 137;
    case 9: return 211;
    case 14: return 149;
    case 21: return 307;
    case 30: return 163;
    case 44: return 281;
    default: return 997;
  }
}

int sw_sparse08(int x){
  switch(x){
    case 3: return 137;
    case 9: return 211;
    case 14: return 149;
    case 21: return 307;
    case 30: return 163;
    case 44: return 281;
    case 57: return 199;
    case 68: return 353;
    default: return 997;
  }
}

int sw_sparse12(int x){
  switch(x){
    case 3: return 137;
    case 9: return 211;
    case 14: return 149;
    case 21: return 307;
    case 30: return 163;
    case 44: return 281;
    case 57: return 199;
    case 68: return 353;
    case 79: return 173;
    case 91: return 269;
    case 104: return 191;
    case 120: return 331;
    default: return 997;
  }
}

int sw_spscram06(int x){
  switch(x){
    case 9: return 211;
    case 21: return 307;
    case 44: return 281;
    case 30: return 163;
    case 14: return 149;
    case 3: return 137;
    default: return 997;
  }
}

int sw_spscram12(int x){
  switch(x){
    case 9: return 211;
    case 21: return 307;
    case 44: return 281;
    case 68: return 353;
    case 91: return 269;
    case 120: return 331;
    case 104: return 191;
    case 79: return 173;
    case 57: return 199;
    case 30: return 163;
    case 14: return 149;
    case 3: return 137;
    default: return 997;
  }
}
