#!/usr/bin/env python3
"""predict.py — freeze `rule.py`'s answer for the HELD-OUT k, before compiling.

Lane **w-magic**. P3 on this project (`floor((N-1)/2)` fitting three published
cells exactly and dying at N=5) is why this file exists: a rule validated on the
cells it was fitted to is not validated. `rule.py` was written against the FIT
set only; this writes down what it says about `K_HELD`, `K_HUNT`, `K_UHUNT` and
the workload's own divisors, and that file is committed **before** any of those
cells reaches the compiler.

    work/w-magic/predict.py > work/w-magic/predictions.txt
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import kgrid  # noqa: E402
import rule  # noqa: E402


def main():
    print("# w-magic HELD-OUT PREDICTIONS, at /O1 /GS- /c")
    print("# Generated by work/w-magic/rule.py from `k` ALONE, and committed")
    print("# BEFORE any of these cells was compiled. Columns:")
    print("# sign  op  k  regime  words")
    n = 0
    for tag, ks in (("HELD", kgrid.K_HELD), ("HUNT", kgrid.K_HUNT),
                    ("UHUNT", kgrid.K_UHUNT), ("WORKLOAD", kgrid.K_WORKLOAD),
                    ("HUNT2-S", kgrid.K_HUNT2_S),
                    ("HUNT2-U", kgrid.K_HUNT2_U)):
        print("#--- %s" % tag)
        for k in ks:
            for signed in (True, False):
                if signed and k > 2147483647:
                    continue
                if not signed and k < 0:
                    continue
                for is_mod in (False, True):
                    b = rule.body(signed, is_mod, k)
                    print("%s\t%s\t%d\t%s\t%s"
                          % ("s" if signed else "u",
                             "mod" if is_mod else "div", k,
                             rule.regime(signed, is_mod, k),
                             " ".join("%08x" % w for w in b) if b else "REFUSED"))
                    n += 1
    print("# %d predicted cells" % n)


if __name__ == "__main__":
    main()
