// f3_a3_c0_dthis_fretcall — w-heap GRID F3, generated by gridgen.py. DO NOT EDIT.
struct BE { BE* mNext; BE* mPrev; };
struct H {
    BE* m(unsigned int a, unsigned int b);
    BE* Alloc(unsigned int);
    H* mFreeHead; H* mUsedHead; BE mListHead; unsigned int mSize; unsigned int mCount;
};
BE* H::m(unsigned int initSize, unsigned int size) {
    mSize = size;
    mFreeHead = this;
    mUsedHead = this;
    return Alloc(initSize);
}
