// f2_g8_hdirect_iotherobj_j2 — w-heap GRID F2, generated by gridgen.py. DO NOT EDIT.
struct BE { BE* mNext; BE* mPrev; };
struct H {
    H(unsigned int a, unsigned int b, BE* q);
    H* mFreeHead; H* mUsedHead; BE mListHead; unsigned int mSize; unsigned int mCount;
    BE mSecond;
};
H::H(unsigned int initSize, unsigned int size, BE* q) {
    mSize = size;
    q->mNext = &mListHead;
    q->mPrev = &mListHead;
}
