; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.11886.00 

	TITLE	Z:\home\free\code\milohax\c2-rs\.claude\worktrees\w-dagorder2\work\w-dagorder\ref\ox\g.cpp
	.PPC
	.MODEL FLAT
PUBLIC	__C2_11886
PUBLIC	__C1_11886
;	COMDAT __C1_11886
.XBLD$W	SEGMENT
__C1_11886 DW	04331H
	DW	00H
	DW	00H
	DW	00H
	DW	010H
	DW	00H
	DW	02e6eH
	DW	04400H
;	COMDAT __C2_11886
.XBLD$W	SEGMENT
__C2_11886 DB	'C2', 00H, 00H, 00H, 00H, 00H, 00H, 00H, 010H, 00H, 00H, '.'
	DB	'nD', 00H
PUBLIC	cnd_a1
EXTRN	cnd_void:PROC
	.pdata
$T2663	DD	cnd_a1
	DD	040000d04H
; Function compile flags: /Ogtu
; File z:\home\free\code\milohax\c2-rs\.claude\worktrees\w-dagorder2\work\w-dagorder\ref\ox\g.cpp

	.code

cnd_a1 PROC NEAR

; Begin code for function: cnd_a1

; 31   : { cnd_void(0); return a; }

  00000	7d8802a6	 mflr         r12
  00004	9181fff8	 stw          r12,-8(r1)
  00008	fbe1fff0	 std          r31,-10h(r1)
  0000c	9421ffa0	 stwu         r1,-60h(r1)
.endprolog
$M2661:
  00010	7c7f1b78	 mr           r31,r3
  00014	38600000	 li           r3,0
  00018	48000001	 bl           cnd_void
  0001c	7fe3fb78	 mr           r3,r31
  00020	38210060	 addi         r1,r1,96		; 60h
  00024	8181fff8	 lwz          r12,-8(r1)
  00028	7d8803a6	 mtlr         r12
  0002c	ebe1fff0	 ld           r31,-10h(r1)
  00030	4e800020	 blr
$M2662:
; End code for function: cnd_a1
cnd_a1	ENDP

PUBLIC	cnd_a2
	.pdata
$T2667	DD	cnd_a2
	DD	040001005H
; Function compile flags: /Ogtu

	.code

cnd_a2 PROC NEAR

; Begin code for function: cnd_a2

; 34   : { cnd_void(0); return a + b; }

  00038	7d8802a6	 mflr         r12
  0003c	9181fff8	 stw          r12,-8(r1)
  00040	fbc1ffe8	 std          r30,-18h(r1)
  00044	fbe1fff0	 std          r31,-10h(r1)
  00048	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2665:
  0004c	7c7e1b78	 mr           r30,r3
  00050	38600000	 li           r3,0
  00054	7c9f2378	 mr           r31,r4
  00058	48000001	 bl           cnd_void
  0005c	7c7efa14	 add          r3,r30,r31
  00060	38210070	 addi         r1,r1,112		; 70h
  00064	8181fff8	 lwz          r12,-8(r1)
  00068	7d8803a6	 mtlr         r12
  0006c	ebc1ffe8	 ld           r30,-18h(r1)
  00070	ebe1fff0	 ld           r31,-10h(r1)
  00074	4e800020	 blr
$M2666:
; End code for function: cnd_a2
cnd_a2	ENDP

PUBLIC	cnd_a3
EXTRN	__restgprlr_29:PROC
EXTRN	__savegprlr_29:PROC
	.pdata
$T2673	DD	cnd_a3
	DD	040000c03H
; Function compile flags: /Ogtu

	.code

cnd_a3 PROC NEAR

; Begin code for function: cnd_a3

; 37   : { cnd_void(0); return a + b + c; }

  00078	7d8802a6	 mflr         r12
  0007c	48000001	 bl           __savegprlr_29
  00080	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2671:
  00084	7c7e1b78	 mr           r30,r3
  00088	38600000	 li           r3,0
  0008c	7c9f2378	 mr           r31,r4
  00090	7cbd2b78	 mr           r29,r5
  00094	48000001	 bl           cnd_void
  00098	7d7efa14	 add          r11,r30,r31
  0009c	7c6bea14	 add          r3,r11,r29
  000a0	38210070	 addi         r1,r1,112		; 70h
  000a4	48000000	 b            __restgprlr_29
$M2672:
; End code for function: cnd_a3
cnd_a3	ENDP

PUBLIC	cnd_a4
EXTRN	__restgprlr_28:PROC
EXTRN	__savegprlr_28:PROC
	.pdata
$T2679	DD	cnd_a4
	DD	040000e03H
; Function compile flags: /Ogtu

	.code

cnd_a4 PROC NEAR

; Begin code for function: cnd_a4

; 40   : { cnd_void(0); return a + b + c + d; }

  000a8	7d8802a6	 mflr         r12
  000ac	48000001	 bl           __savegprlr_28
  000b0	9421ff80	 stwu         r1,-80h(r1)
.endprolog
$M2677:
  000b4	7c7d1b78	 mr           r29,r3
  000b8	38600000	 li           r3,0
  000bc	7c9e2378	 mr           r30,r4
  000c0	7cbc2b78	 mr           r28,r5
  000c4	7cdf3378	 mr           r31,r6
  000c8	48000001	 bl           cnd_void
  000cc	7d7df214	 add          r11,r29,r30
  000d0	7d6be214	 add          r11,r11,r28
  000d4	7c6bfa14	 add          r3,r11,r31
  000d8	38210080	 addi         r1,r1,128		; 80h
  000dc	48000000	 b            __restgprlr_28
$M2678:
; End code for function: cnd_a4
cnd_a4	ENDP

PUBLIC	cnd_a5
EXTRN	__restgprlr_27:PROC
EXTRN	__savegprlr_27:PROC
	.pdata
$T2685	DD	cnd_a5
	DD	040001003H
; Function compile flags: /Ogtu

	.code

cnd_a5 PROC NEAR

; Begin code for function: cnd_a5

; 43   : { cnd_void(0); return a + b + c + d + e; }

  000e0	7d8802a6	 mflr         r12
  000e4	48000001	 bl           __savegprlr_27
  000e8	9421ff80	 stwu         r1,-80h(r1)
.endprolog
$M2683:
  000ec	7c7d1b78	 mr           r29,r3
  000f0	38600000	 li           r3,0
  000f4	7c9e2378	 mr           r30,r4
  000f8	7cbc2b78	 mr           r28,r5
  000fc	7cdb3378	 mr           r27,r6
  00100	7cff3b78	 mr           r31,r7
  00104	48000001	 bl           cnd_void
  00108	7d7df214	 add          r11,r29,r30
  0010c	7d6be214	 add          r11,r11,r28
  00110	7d6bda14	 add          r11,r11,r27
  00114	7c6bfa14	 add          r3,r11,r31
  00118	38210080	 addi         r1,r1,128		; 80h
  0011c	48000000	 b            __restgprlr_27
$M2684:
; End code for function: cnd_a5
cnd_a5	ENDP

PUBLIC	cnd_a6
EXTRN	__restgprlr_26:PROC
EXTRN	__savegprlr_26:PROC
	.pdata
$T2691	DD	cnd_a6
	DD	040001203H
; Function compile flags: /Ogtu

	.code

cnd_a6 PROC NEAR

; Begin code for function: cnd_a6

; 46   : { cnd_void(0); return a + b + c + d + e + f; }

  00120	7d8802a6	 mflr         r12
  00124	48000001	 bl           __savegprlr_26
  00128	9421ff70	 stwu         r1,-90h(r1)
.endprolog
$M2689:
  0012c	7c7c1b78	 mr           r28,r3
  00130	38600000	 li           r3,0
  00134	7c9d2378	 mr           r29,r4
  00138	7cbb2b78	 mr           r27,r5
  0013c	7cda3378	 mr           r26,r6
  00140	7cfe3b78	 mr           r30,r7
  00144	7d1f4378	 mr           r31,r8
  00148	48000001	 bl           cnd_void
  0014c	7d7cea14	 add          r11,r28,r29
  00150	7d6bda14	 add          r11,r11,r27
  00154	7d6bd214	 add          r11,r11,r26
  00158	7d6bf214	 add          r11,r11,r30
  0015c	7c6bfa14	 add          r3,r11,r31
  00160	38210090	 addi         r1,r1,144		; 90h
  00164	48000000	 b            __restgprlr_26
$M2690:
; End code for function: cnd_a6
cnd_a6	ENDP

PUBLIC	cnd_a7
EXTRN	__restgprlr_25:PROC
EXTRN	__savegprlr_25:PROC
	.pdata
$T2697	DD	cnd_a7
	DD	040001403H
; Function compile flags: /Ogtu

	.code

cnd_a7 PROC NEAR

; Begin code for function: cnd_a7

; 49   : { cnd_void(0); return a + b + c + d + e + f + g; }

  00168	7d8802a6	 mflr         r12
  0016c	48000001	 bl           __savegprlr_25
  00170	9421ff70	 stwu         r1,-90h(r1)
.endprolog
$M2695:
  00174	7c7c1b78	 mr           r28,r3
  00178	38600000	 li           r3,0
  0017c	7c9d2378	 mr           r29,r4
  00180	7cbb2b78	 mr           r27,r5
  00184	7cda3378	 mr           r26,r6
  00188	7cf93b78	 mr           r25,r7
  0018c	7d1e4378	 mr           r30,r8
  00190	7d3f4b78	 mr           r31,r9
  00194	48000001	 bl           cnd_void
  00198	7d7cea14	 add          r11,r28,r29
  0019c	7d6bda14	 add          r11,r11,r27
  001a0	7d6bd214	 add          r11,r11,r26
  001a4	7d6bca14	 add          r11,r11,r25
  001a8	7d6bf214	 add          r11,r11,r30
  001ac	7c6bfa14	 add          r3,r11,r31
  001b0	38210090	 addi         r1,r1,144		; 90h
  001b4	48000000	 b            __restgprlr_25
$M2696:
; End code for function: cnd_a7
cnd_a7	ENDP

PUBLIC	cnd_a8
EXTRN	__restgprlr_24:PROC
EXTRN	__savegprlr_24:PROC
	.pdata
$T2703	DD	cnd_a8
	DD	040001603H
; Function compile flags: /Ogtu

	.code

cnd_a8 PROC NEAR

; Begin code for function: cnd_a8

; 52   : { cnd_void(0); return a + b + c + d + e + f + g + h; }

  001b8	7d8802a6	 mflr         r12
  001bc	48000001	 bl           __savegprlr_24
  001c0	9421ff60	 stwu         r1,-0A0h(r1)
.endprolog
$M2701:
  001c4	7c7b1b78	 mr           r27,r3
  001c8	38600000	 li           r3,0
  001cc	7c9c2378	 mr           r28,r4
  001d0	7cba2b78	 mr           r26,r5
  001d4	7cd93378	 mr           r25,r6
  001d8	7cf83b78	 mr           r24,r7
  001dc	7d1d4378	 mr           r29,r8
  001e0	7d3e4b78	 mr           r30,r9
  001e4	7d5f5378	 mr           r31,r10
  001e8	48000001	 bl           cnd_void
  001ec	7d7be214	 add          r11,r27,r28
  001f0	7d6bd214	 add          r11,r11,r26
  001f4	7d6bca14	 add          r11,r11,r25
  001f8	7d6bc214	 add          r11,r11,r24
  001fc	7d6bea14	 add          r11,r11,r29
  00200	7d6bf214	 add          r11,r11,r30
  00204	7c6bfa14	 add          r3,r11,r31
  00208	382100a0	 addi         r1,r1,160		; 0A0h
  0020c	48000000	 b            __restgprlr_24
$M2702:
; End code for function: cnd_a8
cnd_a8	ENDP

PUBLIC	cnd_x2
	.pdata
$T2707	DD	cnd_x2
	DD	040001005H
; Function compile flags: /Ogtu

	.code

cnd_x2 PROC NEAR

; Begin code for function: cnd_x2

; 64   : { cnd_void(0); return a + b; }            // == wbl_x2, byte for byte

  00210	7d8802a6	 mflr         r12
  00214	9181fff8	 stw          r12,-8(r1)
  00218	fbc1ffe8	 std          r30,-18h(r1)
  0021c	fbe1fff0	 std          r31,-10h(r1)
  00220	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2705:
  00224	7c7e1b78	 mr           r30,r3
  00228	38600000	 li           r3,0
  0022c	7c9f2378	 mr           r31,r4
  00230	48000001	 bl           cnd_void
  00234	7c7efa14	 add          r3,r30,r31
  00238	38210070	 addi         r1,r1,112		; 70h
  0023c	8181fff8	 lwz          r12,-8(r1)
  00240	7d8803a6	 mtlr         r12
  00244	ebc1ffe8	 ld           r30,-18h(r1)
  00248	ebe1fff0	 ld           r31,-10h(r1)
  0024c	4e800020	 blr
$M2706:
; End code for function: cnd_x2
cnd_x2	ENDP

PUBLIC	cnd_x2r
	.pdata
$T2711	DD	cnd_x2r
	DD	040001005H
; Function compile flags: /Ogtu

	.code

cnd_x2r	PROC NEAR

; Begin code for function: cnd_x2r

; 67   : { cnd_void(0); return b + a; }

  00250	7d8802a6	 mflr         r12
  00254	9181fff8	 stw          r12,-8(r1)
  00258	fbc1ffe8	 std          r30,-18h(r1)
  0025c	fbe1fff0	 std          r31,-10h(r1)
  00260	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2709:
  00264	7c7e1b78	 mr           r30,r3
  00268	38600000	 li           r3,0
  0026c	7c9f2378	 mr           r31,r4
  00270	48000001	 bl           cnd_void
  00274	7c7efa14	 add          r3,r30,r31
  00278	38210070	 addi         r1,r1,112		; 70h
  0027c	8181fff8	 lwz          r12,-8(r1)
  00280	7d8803a6	 mtlr         r12
  00284	ebc1ffe8	 ld           r30,-18h(r1)
  00288	ebe1fff0	 ld           r31,-10h(r1)
  0028c	4e800020	 blr
$M2710:
; End code for function: cnd_x2r
cnd_x2r	ENDP

PUBLIC	cnd_x3
	.pdata
$T2715	DD	cnd_x3
	DD	040000c03H
; Function compile flags: /Ogtu

	.code

cnd_x3 PROC NEAR

; Begin code for function: cnd_x3

; 70   : { cnd_void(0); return a + b + c; }

  00290	7d8802a6	 mflr         r12
  00294	48000001	 bl           __savegprlr_29
  00298	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2713:
  0029c	7c7e1b78	 mr           r30,r3
  002a0	38600000	 li           r3,0
  002a4	7c9f2378	 mr           r31,r4
  002a8	7cbd2b78	 mr           r29,r5
  002ac	48000001	 bl           cnd_void
  002b0	7d7efa14	 add          r11,r30,r31
  002b4	7c6bea14	 add          r3,r11,r29
  002b8	38210070	 addi         r1,r1,112		; 70h
  002bc	48000000	 b            __restgprlr_29
$M2714:
; End code for function: cnd_x3
cnd_x3	ENDP

PUBLIC	cnd_x3r
	.pdata
$T2719	DD	cnd_x3r
	DD	040000c03H
; Function compile flags: /Ogtu

	.code

cnd_x3r	PROC NEAR

; Begin code for function: cnd_x3r

; 73   : { cnd_void(0); return c + b + a; }

  002c0	7d8802a6	 mflr         r12
  002c4	48000001	 bl           __savegprlr_29
  002c8	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2717:
  002cc	7c7e1b78	 mr           r30,r3
  002d0	38600000	 li           r3,0
  002d4	7c9f2378	 mr           r31,r4
  002d8	7cbd2b78	 mr           r29,r5
  002dc	48000001	 bl           cnd_void
  002e0	7d7efa14	 add          r11,r30,r31
  002e4	7c6bea14	 add          r3,r11,r29
  002e8	38210070	 addi         r1,r1,112		; 70h
  002ec	48000000	 b            __restgprlr_29
$M2718:
; End code for function: cnd_x3r
cnd_x3r	ENDP

PUBLIC	cnd_s2
	.pdata
$T2723	DD	cnd_s2
	DD	040001005H
; Function compile flags: /Ogtu

	.code

cnd_s2 PROC NEAR

; Begin code for function: cnd_s2

; 80   : { cnd_void(0); return a - b; }

  002f0	7d8802a6	 mflr         r12
  002f4	9181fff8	 stw          r12,-8(r1)
  002f8	fbc1ffe8	 std          r30,-18h(r1)
  002fc	fbe1fff0	 std          r31,-10h(r1)
  00300	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2721:
  00304	7c7f1b78	 mr           r31,r3
  00308	38600000	 li           r3,0
  0030c	7c9e2378	 mr           r30,r4
  00310	48000001	 bl           cnd_void
  00314	7c7ef850	 subf         r3,r30,r31
  00318	38210070	 addi         r1,r1,112		; 70h
  0031c	8181fff8	 lwz          r12,-8(r1)
  00320	7d8803a6	 mtlr         r12
  00324	ebc1ffe8	 ld           r30,-18h(r1)
  00328	ebe1fff0	 ld           r31,-10h(r1)
  0032c	4e800020	 blr
$M2722:
; End code for function: cnd_s2
cnd_s2	ENDP

PUBLIC	cnd_s2r
	.pdata
$T2727	DD	cnd_s2r
	DD	040001005H
; Function compile flags: /Ogtu

	.code

cnd_s2r	PROC NEAR

; Begin code for function: cnd_s2r

; 83   : { cnd_void(0); return b - a; }

  00330	7d8802a6	 mflr         r12
  00334	9181fff8	 stw          r12,-8(r1)
  00338	fbc1ffe8	 std          r30,-18h(r1)
  0033c	fbe1fff0	 std          r31,-10h(r1)
  00340	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2725:
  00344	7c7f1b78	 mr           r31,r3
  00348	38600000	 li           r3,0
  0034c	7c9e2378	 mr           r30,r4
  00350	48000001	 bl           cnd_void
  00354	7c7ff050	 subf         r3,r31,r30
  00358	38210070	 addi         r1,r1,112		; 70h
  0035c	8181fff8	 lwz          r12,-8(r1)
  00360	7d8803a6	 mtlr         r12
  00364	ebc1ffe8	 ld           r30,-18h(r1)
  00368	ebe1fff0	 ld           r31,-10h(r1)
  0036c	4e800020	 blr
$M2726:
; End code for function: cnd_s2r
cnd_s2r	ENDP

PUBLIC	cnd_h2
	.pdata
$T2731	DD	cnd_h2
	DD	040001305H
; Function compile flags: /Ogtu

	.code

cnd_h2 PROC NEAR

; Begin code for function: cnd_h2

; 98   : {

  00370	7d8802a6	 mflr         r12
  00374	9181fff8	 stw          r12,-8(r1)
  00378	fbc1ffe8	 std          r30,-18h(r1)
  0037c	fbe1fff0	 std          r31,-10h(r1)
  00380	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2729:
  00384	7c7f1b78	 mr           r31,r3

; 99   :     int x = a * 3 + 7;        // taller producer
; 100  :     int y = b;                // trivial producer
; 101  :     cnd_void(0);

  00388	38600000	 li           r3,0
  0038c	7c9e2378	 mr           r30,r4
  00390	48000001	 bl           cnd_void
  00394	57eb083c	 slwi         r11,r31,1
  00398	7d7f5a14	 add          r11,r31,r11

; 102  :     return x + y;

  0039c	7d6bf214	 add          r11,r11,r30
  003a0	386b0007	 addi         r3,r11,7

; 103  : }

  003a4	38210070	 addi         r1,r1,112		; 70h
  003a8	8181fff8	 lwz          r12,-8(r1)
  003ac	7d8803a6	 mtlr         r12
  003b0	ebc1ffe8	 ld           r30,-18h(r1)
  003b4	ebe1fff0	 ld           r31,-10h(r1)
  003b8	4e800020	 blr
$M2730:
; End code for function: cnd_h2
cnd_h2	ENDP

PUBLIC	cnd_h2r
	.pdata
$T2735	DD	cnd_h2r
	DD	040001305H
; Function compile flags: /Ogtu

	.code

cnd_h2r	PROC NEAR

; Begin code for function: cnd_h2r

; 106  : {

  003c0	7d8802a6	 mflr         r12
  003c4	9181fff8	 stw          r12,-8(r1)
  003c8	fbc1ffe8	 std          r30,-18h(r1)
  003cc	fbe1fff0	 std          r31,-10h(r1)
  003d0	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2733:
  003d4	7c7e1b78	 mr           r30,r3

; 107  :     int x = a;                // trivial producer
; 108  :     int y = b * 3 + 7;        // taller producer  -- the ONLY difference
; 109  :     cnd_void(0);

  003d8	38600000	 li           r3,0
  003dc	7c9f2378	 mr           r31,r4
  003e0	48000001	 bl           cnd_void
  003e4	57eb083c	 slwi         r11,r31,1
  003e8	7d7f5a14	 add          r11,r31,r11

; 110  :     return x + y;

  003ec	7d6bf214	 add          r11,r11,r30
  003f0	386b0007	 addi         r3,r11,7

; 111  : }

  003f4	38210070	 addi         r1,r1,112		; 70h
  003f8	8181fff8	 lwz          r12,-8(r1)
  003fc	7d8803a6	 mtlr         r12
  00400	ebc1ffe8	 ld           r30,-18h(r1)
  00404	ebe1fff0	 ld           r31,-10h(r1)
  00408	4e800020	 blr
$M2734:
; End code for function: cnd_h2r
cnd_h2r	ENDP

PUBLIC	cnd_h3
	.pdata
$T2739	DD	cnd_h3
	DD	040000f03H
; Function compile flags: /Ogtu

	.code

cnd_h3 PROC NEAR

; Begin code for function: cnd_h3

; 114  : {

  00410	7d8802a6	 mflr         r12
  00414	48000001	 bl           __savegprlr_29
  00418	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2737:
  0041c	7c7f1b78	 mr           r31,r3

; 115  :     int x = a * 3 + 7;
; 116  :     int y = b;
; 117  :     int z = c;
; 118  :     cnd_void(0);

  00420	38600000	 li           r3,0
  00424	7c9d2378	 mr           r29,r4
  00428	7cbe2b78	 mr           r30,r5
  0042c	48000001	 bl           cnd_void
  00430	57eb083c	 slwi         r11,r31,1
  00434	7d7f5a14	 add          r11,r31,r11

; 119  :     return x + y + z;

  00438	7d6bea14	 add          r11,r11,r29
  0043c	7d6bf214	 add          r11,r11,r30
  00440	386b0007	 addi         r3,r11,7

; 120  : }

  00444	38210070	 addi         r1,r1,112		; 70h
  00448	48000000	 b            __restgprlr_29
$M2738:
; End code for function: cnd_h3
cnd_h3	ENDP

PUBLIC	cnd_h3r
	.pdata
$T2743	DD	cnd_h3r
	DD	040000f03H
; Function compile flags: /Ogtu

	.code

cnd_h3r	PROC NEAR

; Begin code for function: cnd_h3r

; 123  : {

  00450	7d8802a6	 mflr         r12
  00454	48000001	 bl           __savegprlr_29
  00458	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2741:
  0045c	7c7d1b78	 mr           r29,r3

; 124  :     int x = a;
; 125  :     int y = b;
; 126  :     int z = c * 3 + 7;
; 127  :     cnd_void(0);

  00460	38600000	 li           r3,0
  00464	7c9e2378	 mr           r30,r4
  00468	7cbf2b78	 mr           r31,r5
  0046c	48000001	 bl           cnd_void
  00470	57eb083c	 slwi         r11,r31,1
  00474	7d7f5a14	 add          r11,r31,r11

; 128  :     return x + y + z;

  00478	7d6bea14	 add          r11,r11,r29
  0047c	7d6bf214	 add          r11,r11,r30
  00480	386b0007	 addi         r3,r11,7

; 129  : }

  00484	38210070	 addi         r1,r1,112		; 70h
  00488	48000000	 b            __restgprlr_29
$M2742:
; End code for function: cnd_h3r
cnd_h3r	ENDP

PUBLIC	cnd_u2
	.pdata
$T2747	DD	cnd_u2
	DD	040001205H
; Function compile flags: /Ogtu

	.code

cnd_u2 PROC NEAR

; Begin code for function: cnd_u2

; 140  : { cnd_void(0); return a + b + b + b; }    // b used 3x, a once

  00490	7d8802a6	 mflr         r12
  00494	9181fff8	 stw          r12,-8(r1)
  00498	fbc1ffe8	 std          r30,-18h(r1)
  0049c	fbe1fff0	 std          r31,-10h(r1)
  004a0	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2745:
  004a4	7c7e1b78	 mr           r30,r3
  004a8	38600000	 li           r3,0
  004ac	7c9f2378	 mr           r31,r4
  004b0	48000001	 bl           cnd_void
  004b4	57eb083c	 slwi         r11,r31,1
  004b8	7d7f5a14	 add          r11,r31,r11
  004bc	7c6bf214	 add          r3,r11,r30
  004c0	38210070	 addi         r1,r1,112		; 70h
  004c4	8181fff8	 lwz          r12,-8(r1)
  004c8	7d8803a6	 mtlr         r12
  004cc	ebc1ffe8	 ld           r30,-18h(r1)
  004d0	ebe1fff0	 ld           r31,-10h(r1)
  004d4	4e800020	 blr
$M2746:
; End code for function: cnd_u2
cnd_u2	ENDP

PUBLIC	cnd_u2r
	.pdata
$T2751	DD	cnd_u2r
	DD	040001205H
; Function compile flags: /Ogtu

	.code

cnd_u2r	PROC NEAR

; Begin code for function: cnd_u2r

; 143  : { cnd_void(0); return a + a + a + b; }    // a used 3x, b once

  004d8	7d8802a6	 mflr         r12
  004dc	9181fff8	 stw          r12,-8(r1)
  004e0	fbc1ffe8	 std          r30,-18h(r1)
  004e4	fbe1fff0	 std          r31,-10h(r1)
  004e8	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2749:
  004ec	7c7f1b78	 mr           r31,r3
  004f0	38600000	 li           r3,0
  004f4	7c9e2378	 mr           r30,r4
  004f8	48000001	 bl           cnd_void
  004fc	57eb083c	 slwi         r11,r31,1
  00500	7d7f5a14	 add          r11,r31,r11
  00504	7c6bf214	 add          r3,r11,r30
  00508	38210070	 addi         r1,r1,112		; 70h
  0050c	8181fff8	 lwz          r12,-8(r1)
  00510	7d8803a6	 mtlr         r12
  00514	ebc1ffe8	 ld           r30,-18h(r1)
  00518	ebe1fff0	 ld           r31,-10h(r1)
  0051c	4e800020	 blr
$M2750:
; End code for function: cnd_u2r
cnd_u2r	ENDP

PUBLIC	cnd_c0
EXTRN	cnd_val:PROC
	.pdata
$T2755	DD	cnd_c0
	DD	040000a03H
; Function compile flags: /Ogtu

	.code

cnd_c0 PROC NEAR

; Begin code for function: cnd_c0

; 152  : { cnd_void(a + 1); return cnd_val(); }

  00520	7d8802a6	 mflr         r12
  00524	9181fff8	 stw          r12,-8(r1)
  00528	9421ffa0	 stwu         r1,-60h(r1)
.endprolog
$M2753:
  0052c	38630001	 addi         r3,r3,1
  00530	48000001	 bl           cnd_void
  00534	48000001	 bl           cnd_val
  00538	38210060	 addi         r1,r1,96		; 60h
  0053c	8181fff8	 lwz          r12,-8(r1)
  00540	7d8803a6	 mtlr         r12
  00544	4e800020	 blr
$M2754:
; End code for function: cnd_c0
cnd_c0	ENDP

END
