; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.11886.00 

	TITLE	Z:<repo>\.claude\worktrees\w-dagorder2\work\w-dagorder\ref\o1\g.cpp
	.PPC
	.MODEL FLAT
PUBLIC	__C2_11886
PUBLIC	__C1_11886
;	COMDAT __C1_11886
.XBLD$W	SEGMENT
__C1_11886 DW	04331H
	DW	00H
	DW	00H
	DW	00H
	DW	010H
	DW	00H
	DW	02e6eH
	DW	04400H
;	COMDAT __C2_11886
.XBLD$W	SEGMENT
__C2_11886 DB	'C2', 00H, 00H, 00H, 00H, 00H, 00H, 00H, 010H, 00H, 00H, '.'
	DB	'nD', 00H
PUBLIC	cnd_a1
EXTRN	cnd_void:PROC
;	COMDAT .pdata
; File z:<repo>\.claude\worktrees\w-dagorder2\work\w-dagorder\ref\o1\g.cpp
.pdata	SEGMENT
$T2726	DD	cnd_a1
	DD	040000d04H
; Function compile flags: /Ogsu

	.code

cnd_a1 PROC NEAR						; COMDAT

; Begin code for function: cnd_a1

; 31   : { cnd_void(0); return a; }

  00000	7d8802a6	 mflr         r12
  00004	9181fff8	 stw          r12,-8(r1)
  00008	fbe1fff0	 std          r31,-10h(r1)
  0000c	9421ffa0	 stwu         r1,-60h(r1)
.endprolog
$M2724:
  00010	7c7f1b78	 mr           r31,r3
  00014	38600000	 li           r3,0
  00018	48000001	 bl           cnd_void
  0001c	7fe3fb78	 mr           r3,r31
  00020	38210060	 addi         r1,r1,96		; 60h
  00024	8181fff8	 lwz          r12,-8(r1)
  00028	7d8803a6	 mtlr         r12
  0002c	ebe1fff0	 ld           r31,-10h(r1)
  00030	4e800020	 blr
$M2725:
; End code for function: cnd_a1
cnd_a1	ENDP

PUBLIC	cnd_a2
;	COMDAT .pdata
.pdata	SEGMENT
$T2731	DD	cnd_a2
	DD	040001005H
; Function compile flags: /Ogsu

	.code

cnd_a2 PROC NEAR						; COMDAT

; Begin code for function: cnd_a2

; 34   : { cnd_void(0); return a + b; }

  00000	7d8802a6	 mflr         r12
  00004	9181fff8	 stw          r12,-8(r1)
  00008	fbc1ffe8	 std          r30,-18h(r1)
  0000c	fbe1fff0	 std          r31,-10h(r1)
  00010	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2729:
  00014	7c7e1b78	 mr           r30,r3
  00018	38600000	 li           r3,0
  0001c	7c9f2378	 mr           r31,r4
  00020	48000001	 bl           cnd_void
  00024	7c7efa14	 add          r3,r30,r31
  00028	38210070	 addi         r1,r1,112		; 70h
  0002c	8181fff8	 lwz          r12,-8(r1)
  00030	7d8803a6	 mtlr         r12
  00034	ebc1ffe8	 ld           r30,-18h(r1)
  00038	ebe1fff0	 ld           r31,-10h(r1)
  0003c	4e800020	 blr
$M2730:
; End code for function: cnd_a2
cnd_a2	ENDP

PUBLIC	cnd_a3
EXTRN	__restgprlr_29:PROC
EXTRN	__savegprlr_29:PROC
;	COMDAT .pdata
.pdata	SEGMENT
$T2738	DD	cnd_a3
	DD	040000c03H
; Function compile flags: /Ogsu

	.code

cnd_a3 PROC NEAR						; COMDAT

; Begin code for function: cnd_a3

; 37   : { cnd_void(0); return a + b + c; }

  00000	7d8802a6	 mflr         r12
  00004	48000001	 bl           __savegprlr_29
  00008	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2736:
  0000c	7c7e1b78	 mr           r30,r3
  00010	38600000	 li           r3,0
  00014	7c9f2378	 mr           r31,r4
  00018	7cbd2b78	 mr           r29,r5
  0001c	48000001	 bl           cnd_void
  00020	7d7efa14	 add          r11,r30,r31
  00024	7c6bea14	 add          r3,r11,r29
  00028	38210070	 addi         r1,r1,112		; 70h
  0002c	48000000	 b            __restgprlr_29
$M2737:
; End code for function: cnd_a3
cnd_a3	ENDP

PUBLIC	cnd_a4
EXTRN	__restgprlr_28:PROC
EXTRN	__savegprlr_28:PROC
;	COMDAT .pdata
.pdata	SEGMENT
$T2745	DD	cnd_a4
	DD	040000e03H
; Function compile flags: /Ogsu

	.code

cnd_a4 PROC NEAR						; COMDAT

; Begin code for function: cnd_a4

; 40   : { cnd_void(0); return a + b + c + d; }

  00000	7d8802a6	 mflr         r12
  00004	48000001	 bl           __savegprlr_28
  00008	9421ff80	 stwu         r1,-80h(r1)
.endprolog
$M2743:
  0000c	7c7d1b78	 mr           r29,r3
  00010	38600000	 li           r3,0
  00014	7c9e2378	 mr           r30,r4
  00018	7cbc2b78	 mr           r28,r5
  0001c	7cdf3378	 mr           r31,r6
  00020	48000001	 bl           cnd_void
  00024	7d7df214	 add          r11,r29,r30
  00028	7d6be214	 add          r11,r11,r28
  0002c	7c6bfa14	 add          r3,r11,r31
  00030	38210080	 addi         r1,r1,128		; 80h
  00034	48000000	 b            __restgprlr_28
$M2744:
; End code for function: cnd_a4
cnd_a4	ENDP

PUBLIC	cnd_a5
EXTRN	__restgprlr_27:PROC
EXTRN	__savegprlr_27:PROC
;	COMDAT .pdata
.pdata	SEGMENT
$T2752	DD	cnd_a5
	DD	040001003H
; Function compile flags: /Ogsu

	.code

cnd_a5 PROC NEAR						; COMDAT

; Begin code for function: cnd_a5

; 43   : { cnd_void(0); return a + b + c + d + e; }

  00000	7d8802a6	 mflr         r12
  00004	48000001	 bl           __savegprlr_27
  00008	9421ff80	 stwu         r1,-80h(r1)
.endprolog
$M2750:
  0000c	7c7d1b78	 mr           r29,r3
  00010	38600000	 li           r3,0
  00014	7c9e2378	 mr           r30,r4
  00018	7cbc2b78	 mr           r28,r5
  0001c	7cdb3378	 mr           r27,r6
  00020	7cff3b78	 mr           r31,r7
  00024	48000001	 bl           cnd_void
  00028	7d7df214	 add          r11,r29,r30
  0002c	7d6be214	 add          r11,r11,r28
  00030	7d6bda14	 add          r11,r11,r27
  00034	7c6bfa14	 add          r3,r11,r31
  00038	38210080	 addi         r1,r1,128		; 80h
  0003c	48000000	 b            __restgprlr_27
$M2751:
; End code for function: cnd_a5
cnd_a5	ENDP

PUBLIC	cnd_a6
EXTRN	__restgprlr_26:PROC
EXTRN	__savegprlr_26:PROC
;	COMDAT .pdata
.pdata	SEGMENT
$T2759	DD	cnd_a6
	DD	040001203H
; Function compile flags: /Ogsu

	.code

cnd_a6 PROC NEAR						; COMDAT

; Begin code for function: cnd_a6

; 46   : { cnd_void(0); return a + b + c + d + e + f; }

  00000	7d8802a6	 mflr         r12
  00004	48000001	 bl           __savegprlr_26
  00008	9421ff70	 stwu         r1,-90h(r1)
.endprolog
$M2757:
  0000c	7c7c1b78	 mr           r28,r3
  00010	38600000	 li           r3,0
  00014	7c9d2378	 mr           r29,r4
  00018	7cbb2b78	 mr           r27,r5
  0001c	7cda3378	 mr           r26,r6
  00020	7cfe3b78	 mr           r30,r7
  00024	7d1f4378	 mr           r31,r8
  00028	48000001	 bl           cnd_void
  0002c	7d7cea14	 add          r11,r28,r29
  00030	7d6bda14	 add          r11,r11,r27
  00034	7d6bd214	 add          r11,r11,r26
  00038	7d6bf214	 add          r11,r11,r30
  0003c	7c6bfa14	 add          r3,r11,r31
  00040	38210090	 addi         r1,r1,144		; 90h
  00044	48000000	 b            __restgprlr_26
$M2758:
; End code for function: cnd_a6
cnd_a6	ENDP

PUBLIC	cnd_a7
EXTRN	__restgprlr_25:PROC
EXTRN	__savegprlr_25:PROC
;	COMDAT .pdata
.pdata	SEGMENT
$T2766	DD	cnd_a7
	DD	040001403H
; Function compile flags: /Ogsu

	.code

cnd_a7 PROC NEAR						; COMDAT

; Begin code for function: cnd_a7

; 49   : { cnd_void(0); return a + b + c + d + e + f + g; }

  00000	7d8802a6	 mflr         r12
  00004	48000001	 bl           __savegprlr_25
  00008	9421ff70	 stwu         r1,-90h(r1)
.endprolog
$M2764:
  0000c	7c7c1b78	 mr           r28,r3
  00010	38600000	 li           r3,0
  00014	7c9d2378	 mr           r29,r4
  00018	7cbb2b78	 mr           r27,r5
  0001c	7cda3378	 mr           r26,r6
  00020	7cf93b78	 mr           r25,r7
  00024	7d1e4378	 mr           r30,r8
  00028	7d3f4b78	 mr           r31,r9
  0002c	48000001	 bl           cnd_void
  00030	7d7cea14	 add          r11,r28,r29
  00034	7d6bda14	 add          r11,r11,r27
  00038	7d6bd214	 add          r11,r11,r26
  0003c	7d6bca14	 add          r11,r11,r25
  00040	7d6bf214	 add          r11,r11,r30
  00044	7c6bfa14	 add          r3,r11,r31
  00048	38210090	 addi         r1,r1,144		; 90h
  0004c	48000000	 b            __restgprlr_25
$M2765:
; End code for function: cnd_a7
cnd_a7	ENDP

PUBLIC	cnd_a8
EXTRN	__restgprlr_24:PROC
EXTRN	__savegprlr_24:PROC
;	COMDAT .pdata
.pdata	SEGMENT
$T2773	DD	cnd_a8
	DD	040001603H
; Function compile flags: /Ogsu

	.code

cnd_a8 PROC NEAR						; COMDAT

; Begin code for function: cnd_a8

; 52   : { cnd_void(0); return a + b + c + d + e + f + g + h; }

  00000	7d8802a6	 mflr         r12
  00004	48000001	 bl           __savegprlr_24
  00008	9421ff60	 stwu         r1,-0A0h(r1)
.endprolog
$M2771:
  0000c	7c7b1b78	 mr           r27,r3
  00010	38600000	 li           r3,0
  00014	7c9c2378	 mr           r28,r4
  00018	7cba2b78	 mr           r26,r5
  0001c	7cd93378	 mr           r25,r6
  00020	7cf83b78	 mr           r24,r7
  00024	7d1d4378	 mr           r29,r8
  00028	7d3e4b78	 mr           r30,r9
  0002c	7d5f5378	 mr           r31,r10
  00030	48000001	 bl           cnd_void
  00034	7d7be214	 add          r11,r27,r28
  00038	7d6bd214	 add          r11,r11,r26
  0003c	7d6bca14	 add          r11,r11,r25
  00040	7d6bc214	 add          r11,r11,r24
  00044	7d6bea14	 add          r11,r11,r29
  00048	7d6bf214	 add          r11,r11,r30
  0004c	7c6bfa14	 add          r3,r11,r31
  00050	382100a0	 addi         r1,r1,160		; 0A0h
  00054	48000000	 b            __restgprlr_24
$M2772:
; End code for function: cnd_a8
cnd_a8	ENDP

PUBLIC	cnd_x2
;	COMDAT .pdata
.pdata	SEGMENT
$T2778	DD	cnd_x2
	DD	040001005H
; Function compile flags: /Ogsu

	.code

cnd_x2 PROC NEAR						; COMDAT

; Begin code for function: cnd_x2

; 64   : { cnd_void(0); return a + b; }            // == wbl_x2, byte for byte

  00000	7d8802a6	 mflr         r12
  00004	9181fff8	 stw          r12,-8(r1)
  00008	fbc1ffe8	 std          r30,-18h(r1)
  0000c	fbe1fff0	 std          r31,-10h(r1)
  00010	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2776:
  00014	7c7e1b78	 mr           r30,r3
  00018	38600000	 li           r3,0
  0001c	7c9f2378	 mr           r31,r4
  00020	48000001	 bl           cnd_void
  00024	7c7efa14	 add          r3,r30,r31
  00028	38210070	 addi         r1,r1,112		; 70h
  0002c	8181fff8	 lwz          r12,-8(r1)
  00030	7d8803a6	 mtlr         r12
  00034	ebc1ffe8	 ld           r30,-18h(r1)
  00038	ebe1fff0	 ld           r31,-10h(r1)
  0003c	4e800020	 blr
$M2777:
; End code for function: cnd_x2
cnd_x2	ENDP

PUBLIC	cnd_x2r
;	COMDAT .pdata
.pdata	SEGMENT
$T2783	DD	cnd_x2r
	DD	040001005H
; Function compile flags: /Ogsu

	.code

cnd_x2r	PROC NEAR					; COMDAT

; Begin code for function: cnd_x2r

; 67   : { cnd_void(0); return b + a; }

  00000	7d8802a6	 mflr         r12
  00004	9181fff8	 stw          r12,-8(r1)
  00008	fbc1ffe8	 std          r30,-18h(r1)
  0000c	fbe1fff0	 std          r31,-10h(r1)
  00010	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2781:
  00014	7c7e1b78	 mr           r30,r3
  00018	38600000	 li           r3,0
  0001c	7c9f2378	 mr           r31,r4
  00020	48000001	 bl           cnd_void
  00024	7c7efa14	 add          r3,r30,r31
  00028	38210070	 addi         r1,r1,112		; 70h
  0002c	8181fff8	 lwz          r12,-8(r1)
  00030	7d8803a6	 mtlr         r12
  00034	ebc1ffe8	 ld           r30,-18h(r1)
  00038	ebe1fff0	 ld           r31,-10h(r1)
  0003c	4e800020	 blr
$M2782:
; End code for function: cnd_x2r
cnd_x2r	ENDP

PUBLIC	cnd_x3
;	COMDAT .pdata
.pdata	SEGMENT
$T2788	DD	cnd_x3
	DD	040000c03H
; Function compile flags: /Ogsu

	.code

cnd_x3 PROC NEAR						; COMDAT

; Begin code for function: cnd_x3

; 70   : { cnd_void(0); return a + b + c; }

  00000	7d8802a6	 mflr         r12
  00004	48000001	 bl           __savegprlr_29
  00008	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2786:
  0000c	7c7e1b78	 mr           r30,r3
  00010	38600000	 li           r3,0
  00014	7c9f2378	 mr           r31,r4
  00018	7cbd2b78	 mr           r29,r5
  0001c	48000001	 bl           cnd_void
  00020	7d7efa14	 add          r11,r30,r31
  00024	7c6bea14	 add          r3,r11,r29
  00028	38210070	 addi         r1,r1,112		; 70h
  0002c	48000000	 b            __restgprlr_29
$M2787:
; End code for function: cnd_x3
cnd_x3	ENDP

PUBLIC	cnd_x3r
;	COMDAT .pdata
.pdata	SEGMENT
$T2793	DD	cnd_x3r
	DD	040000c03H
; Function compile flags: /Ogsu

	.code

cnd_x3r	PROC NEAR					; COMDAT

; Begin code for function: cnd_x3r

; 73   : { cnd_void(0); return c + b + a; }

  00000	7d8802a6	 mflr         r12
  00004	48000001	 bl           __savegprlr_29
  00008	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2791:
  0000c	7c7e1b78	 mr           r30,r3
  00010	38600000	 li           r3,0
  00014	7c9f2378	 mr           r31,r4
  00018	7cbd2b78	 mr           r29,r5
  0001c	48000001	 bl           cnd_void
  00020	7d7efa14	 add          r11,r30,r31
  00024	7c6bea14	 add          r3,r11,r29
  00028	38210070	 addi         r1,r1,112		; 70h
  0002c	48000000	 b            __restgprlr_29
$M2792:
; End code for function: cnd_x3r
cnd_x3r	ENDP

PUBLIC	cnd_s2
;	COMDAT .pdata
.pdata	SEGMENT
$T2798	DD	cnd_s2
	DD	040001005H
; Function compile flags: /Ogsu

	.code

cnd_s2 PROC NEAR						; COMDAT

; Begin code for function: cnd_s2

; 80   : { cnd_void(0); return a - b; }

  00000	7d8802a6	 mflr         r12
  00004	9181fff8	 stw          r12,-8(r1)
  00008	fbc1ffe8	 std          r30,-18h(r1)
  0000c	fbe1fff0	 std          r31,-10h(r1)
  00010	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2796:
  00014	7c7f1b78	 mr           r31,r3
  00018	38600000	 li           r3,0
  0001c	7c9e2378	 mr           r30,r4
  00020	48000001	 bl           cnd_void
  00024	7c7ef850	 subf         r3,r30,r31
  00028	38210070	 addi         r1,r1,112		; 70h
  0002c	8181fff8	 lwz          r12,-8(r1)
  00030	7d8803a6	 mtlr         r12
  00034	ebc1ffe8	 ld           r30,-18h(r1)
  00038	ebe1fff0	 ld           r31,-10h(r1)
  0003c	4e800020	 blr
$M2797:
; End code for function: cnd_s2
cnd_s2	ENDP

PUBLIC	cnd_s2r
;	COMDAT .pdata
.pdata	SEGMENT
$T2803	DD	cnd_s2r
	DD	040001005H
; Function compile flags: /Ogsu

	.code

cnd_s2r	PROC NEAR					; COMDAT

; Begin code for function: cnd_s2r

; 83   : { cnd_void(0); return b - a; }

  00000	7d8802a6	 mflr         r12
  00004	9181fff8	 stw          r12,-8(r1)
  00008	fbc1ffe8	 std          r30,-18h(r1)
  0000c	fbe1fff0	 std          r31,-10h(r1)
  00010	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2801:
  00014	7c7f1b78	 mr           r31,r3
  00018	38600000	 li           r3,0
  0001c	7c9e2378	 mr           r30,r4
  00020	48000001	 bl           cnd_void
  00024	7c7ff050	 subf         r3,r31,r30
  00028	38210070	 addi         r1,r1,112		; 70h
  0002c	8181fff8	 lwz          r12,-8(r1)
  00030	7d8803a6	 mtlr         r12
  00034	ebc1ffe8	 ld           r30,-18h(r1)
  00038	ebe1fff0	 ld           r31,-10h(r1)
  0003c	4e800020	 blr
$M2802:
; End code for function: cnd_s2r
cnd_s2r	ENDP

PUBLIC	cnd_h2
;	COMDAT .pdata
.pdata	SEGMENT
$T2808	DD	cnd_h2
	DD	040001205H
; Function compile flags: /Ogsu

	.code

cnd_h2 PROC NEAR						; COMDAT

; Begin code for function: cnd_h2

; 98   : {

  00000	7d8802a6	 mflr         r12
  00004	9181fff8	 stw          r12,-8(r1)
  00008	fbc1ffe8	 std          r30,-18h(r1)
  0000c	fbe1fff0	 std          r31,-10h(r1)
  00010	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2806:
  00014	7c7e1b78	 mr           r30,r3

; 99   :     int x = a * 3 + 7;        // taller producer
; 100  :     int y = b;                // trivial producer
; 101  :     cnd_void(0);

  00018	38600000	 li           r3,0
  0001c	7c9f2378	 mr           r31,r4
  00020	48000001	 bl           cnd_void
  00024	1d7e0003	 mulli        r11,r30,3

; 102  :     return x + y;

  00028	7d6bfa14	 add          r11,r11,r31
  0002c	386b0007	 addi         r3,r11,7

; 103  : }

  00030	38210070	 addi         r1,r1,112		; 70h
  00034	8181fff8	 lwz          r12,-8(r1)
  00038	7d8803a6	 mtlr         r12
  0003c	ebc1ffe8	 ld           r30,-18h(r1)
  00040	ebe1fff0	 ld           r31,-10h(r1)
  00044	4e800020	 blr
$M2807:
; End code for function: cnd_h2
cnd_h2	ENDP

PUBLIC	cnd_h2r
;	COMDAT .pdata
.pdata	SEGMENT
$T2813	DD	cnd_h2r
	DD	040001205H
; Function compile flags: /Ogsu

	.code

cnd_h2r	PROC NEAR					; COMDAT

; Begin code for function: cnd_h2r

; 106  : {

  00000	7d8802a6	 mflr         r12
  00004	9181fff8	 stw          r12,-8(r1)
  00008	fbc1ffe8	 std          r30,-18h(r1)
  0000c	fbe1fff0	 std          r31,-10h(r1)
  00010	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2811:
  00014	7c7f1b78	 mr           r31,r3

; 107  :     int x = a;                // trivial producer
; 108  :     int y = b * 3 + 7;        // taller producer  -- the ONLY difference
; 109  :     cnd_void(0);

  00018	38600000	 li           r3,0
  0001c	7c9e2378	 mr           r30,r4
  00020	48000001	 bl           cnd_void
  00024	1d7e0003	 mulli        r11,r30,3

; 110  :     return x + y;

  00028	7d6bfa14	 add          r11,r11,r31
  0002c	386b0007	 addi         r3,r11,7

; 111  : }

  00030	38210070	 addi         r1,r1,112		; 70h
  00034	8181fff8	 lwz          r12,-8(r1)
  00038	7d8803a6	 mtlr         r12
  0003c	ebc1ffe8	 ld           r30,-18h(r1)
  00040	ebe1fff0	 ld           r31,-10h(r1)
  00044	4e800020	 blr
$M2812:
; End code for function: cnd_h2r
cnd_h2r	ENDP

PUBLIC	cnd_h3
;	COMDAT .pdata
.pdata	SEGMENT
$T2818	DD	cnd_h3
	DD	040000e03H
; Function compile flags: /Ogsu

	.code

cnd_h3 PROC NEAR						; COMDAT

; Begin code for function: cnd_h3

; 114  : {

  00000	7d8802a6	 mflr         r12
  00004	48000001	 bl           __savegprlr_29
  00008	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2816:
  0000c	7c7d1b78	 mr           r29,r3

; 115  :     int x = a * 3 + 7;
; 116  :     int y = b;
; 117  :     int z = c;
; 118  :     cnd_void(0);

  00010	38600000	 li           r3,0
  00014	7c9f2378	 mr           r31,r4
  00018	7cbe2b78	 mr           r30,r5
  0001c	48000001	 bl           cnd_void
  00020	1d7d0003	 mulli        r11,r29,3

; 119  :     return x + y + z;

  00024	7d6bfa14	 add          r11,r11,r31
  00028	7d6bf214	 add          r11,r11,r30
  0002c	386b0007	 addi         r3,r11,7

; 120  : }

  00030	38210070	 addi         r1,r1,112		; 70h
  00034	48000000	 b            __restgprlr_29
$M2817:
; End code for function: cnd_h3
cnd_h3	ENDP

PUBLIC	cnd_h3r
;	COMDAT .pdata
.pdata	SEGMENT
$T2823	DD	cnd_h3r
	DD	040000e03H
; Function compile flags: /Ogsu

	.code

cnd_h3r	PROC NEAR					; COMDAT

; Begin code for function: cnd_h3r

; 123  : {

  00000	7d8802a6	 mflr         r12
  00004	48000001	 bl           __savegprlr_29
  00008	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2821:
  0000c	7c7f1b78	 mr           r31,r3

; 124  :     int x = a;
; 125  :     int y = b;
; 126  :     int z = c * 3 + 7;
; 127  :     cnd_void(0);

  00010	38600000	 li           r3,0
  00014	7c9e2378	 mr           r30,r4
  00018	7cbd2b78	 mr           r29,r5
  0001c	48000001	 bl           cnd_void
  00020	1d7d0003	 mulli        r11,r29,3

; 128  :     return x + y + z;

  00024	7d6bfa14	 add          r11,r11,r31
  00028	7d6bf214	 add          r11,r11,r30
  0002c	386b0007	 addi         r3,r11,7

; 129  : }

  00030	38210070	 addi         r1,r1,112		; 70h
  00034	48000000	 b            __restgprlr_29
$M2822:
; End code for function: cnd_h3r
cnd_h3r	ENDP

PUBLIC	cnd_u2
;	COMDAT .pdata
.pdata	SEGMENT
$T2828	DD	cnd_u2
	DD	040001105H
; Function compile flags: /Ogsu

	.code

cnd_u2 PROC NEAR						; COMDAT

; Begin code for function: cnd_u2

; 140  : { cnd_void(0); return a + b + b + b; }    // b used 3x, a once

  00000	7d8802a6	 mflr         r12
  00004	9181fff8	 stw          r12,-8(r1)
  00008	fbc1ffe8	 std          r30,-18h(r1)
  0000c	fbe1fff0	 std          r31,-10h(r1)
  00010	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2826:
  00014	7c7f1b78	 mr           r31,r3
  00018	38600000	 li           r3,0
  0001c	7c9e2378	 mr           r30,r4
  00020	48000001	 bl           cnd_void
  00024	1d7e0003	 mulli        r11,r30,3
  00028	7c6bfa14	 add          r3,r11,r31
  0002c	38210070	 addi         r1,r1,112		; 70h
  00030	8181fff8	 lwz          r12,-8(r1)
  00034	7d8803a6	 mtlr         r12
  00038	ebc1ffe8	 ld           r30,-18h(r1)
  0003c	ebe1fff0	 ld           r31,-10h(r1)
  00040	4e800020	 blr
$M2827:
; End code for function: cnd_u2
cnd_u2	ENDP

PUBLIC	cnd_u2r
;	COMDAT .pdata
.pdata	SEGMENT
$T2833	DD	cnd_u2r
	DD	040001105H
; Function compile flags: /Ogsu

	.code

cnd_u2r	PROC NEAR					; COMDAT

; Begin code for function: cnd_u2r

; 143  : { cnd_void(0); return a + a + a + b; }    // a used 3x, b once

  00000	7d8802a6	 mflr         r12
  00004	9181fff8	 stw          r12,-8(r1)
  00008	fbc1ffe8	 std          r30,-18h(r1)
  0000c	fbe1fff0	 std          r31,-10h(r1)
  00010	9421ff90	 stwu         r1,-70h(r1)
.endprolog
$M2831:
  00014	7c7e1b78	 mr           r30,r3
  00018	38600000	 li           r3,0
  0001c	7c9f2378	 mr           r31,r4
  00020	48000001	 bl           cnd_void
  00024	1d7e0003	 mulli        r11,r30,3
  00028	7c6bfa14	 add          r3,r11,r31
  0002c	38210070	 addi         r1,r1,112		; 70h
  00030	8181fff8	 lwz          r12,-8(r1)
  00034	7d8803a6	 mtlr         r12
  00038	ebc1ffe8	 ld           r30,-18h(r1)
  0003c	ebe1fff0	 ld           r31,-10h(r1)
  00040	4e800020	 blr
$M2832:
; End code for function: cnd_u2r
cnd_u2r	ENDP

PUBLIC	cnd_c0
EXTRN	cnd_val:PROC
;	COMDAT .pdata
.pdata	SEGMENT
$T2838	DD	cnd_c0
	DD	040000a03H
; Function compile flags: /Ogsu

	.code

cnd_c0 PROC NEAR						; COMDAT

; Begin code for function: cnd_c0

; 152  : { cnd_void(a + 1); return cnd_val(); }

  00000	7d8802a6	 mflr         r12
  00004	9181fff8	 stw          r12,-8(r1)
  00008	9421ffa0	 stwu         r1,-60h(r1)
.endprolog
$M2836:
  0000c	38630001	 addi         r3,r3,1
  00010	48000001	 bl           cnd_void
  00014	48000001	 bl           cnd_val
  00018	38210060	 addi         r1,r1,96		; 60h
  0001c	8181fff8	 lwz          r12,-8(r1)
  00020	7d8803a6	 mtlr         r12
  00024	4e800020	 blr
$M2837:
; End code for function: cnd_c0
cnd_c0	ENDP

END
