// f3_a3_c1_dfree_fctor — w-heap GRID F3, generated by gridgen.py. DO NOT EDIT.
struct BE { BE* mNext; BE* mPrev; };
extern void g1(unsigned int);
struct H {
    H(unsigned int a, unsigned int b);
    H* mFreeHead; H* mUsedHead; BE mListHead; unsigned int mSize; unsigned int mCount;
};
H::H(unsigned int initSize, unsigned int size) {
    mSize = size;
    mFreeHead = this;
    mUsedHead = this;
    g1(initSize);
}
