// f2_g0_hdirect_iself_j2 — w-heap GRID F2, generated by gridgen.py. DO NOT EDIT.
struct BE { BE* mNext; BE* mPrev; };
struct H {
    H(unsigned int a, unsigned int b);
    H* mFreeHead; H* mUsedHead; BE mListHead; unsigned int mSize; unsigned int mCount;
    BE mSecond;
};
H::H(unsigned int initSize, unsigned int size) {
    mSize = size;
    mFreeHead = (H*)this;
    mListHead.mNext = (BE*)this;
    mListHead.mPrev = (BE*)this;
}
