#!/bin/sh
# Regenerate docs/rungs/INDEX.md from the rung docs' header blocks.
#
# Tooling, like scripts/plot_perf.py — outside the std-only workspace. The index
# is GENERATED; never hand-edit it. `crates/c2-harness/tests/rung_registry.rs`
# fails if the file on disk differs from what this script produces, so a rung
# that forgets to run it is caught in the portable lane.
#
# Usage:  scripts/gen_rung_index.sh          # rewrite docs/rungs/INDEX.md
#         scripts/gen_rung_index.sh -        # print to stdout instead
set -eu

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
rungs="$repo_root/docs/rungs"

gen() {
    cat <<'HDR'
# Rung index

Generated by `scripts/gen_rung_index.sh` — do not hand-edit. One line per rung
doc in this directory; see `README.md` for the convention and `_TEMPLATE.md` for
the header block this table is read from.

| date | tag | slug | fixtures | census |
|---|---|---|---|---|
HDR
    for f in "$rungs"/*.md; do
        base="${f##*/}"
        case "$base" in
            _*|INDEX.md|README.md) continue ;;
        esac
        date="${base%%-*}-$(echo "$base" | cut -d- -f2)-$(echo "$base" | cut -d- -f3)"
        tag=$(sed -n 's/^    Tag: *//p' "$f" | head -1)
        slug=$(sed -n 's/^    Slug: *//p' "$f" | head -1)
        fixtures=$(sed -n 's/^    Fixtures: *//p' "$f" | head -1)
        census=$(sed -n 's/^    Census: *//p' "$f" | head -1)
        nfix=$(printf '%s\n' "$fixtures" | wc -w | tr -d ' ')
        printf '| %s | %s | [%s](%s) | %s | %s |\n' \
            "$date" "$tag" "$slug" "$base" "$nfix" "$census"
    done
}

if [ "${1:-}" = "-" ]; then
    gen
else
    gen > "$rungs/INDEX.md"
    echo "wrote $rungs/INDEX.md"
fi
