#!/usr/bin/env python3
"""W-SLOTARG capture grid — the ordering rule for a COMPUTED ADDRESS in a call slot.

Board #149's grid is §9.13.1's with one axis added. §9.13.1's ALARM is that the
address-last rule and the address-second rule AGREE at walk length <= 1, so a
wrong rule ships green; the grid must therefore cross

  * walk length      0..4  (how many OTHER arguments need a setup word)
  * address slot     0 / a middle slot / last
  * offset value     0 / small / >= 0x8000 / negative
  * designator steps 1 (`&t->k`) / 2 (`&t->s.k`)
  * caller kind      free function / member call (receiver occupies slot 0)

and it must not SAMPLE them.  Emits one .cpp; `c2rs listing` prints c2's own
account of every function in it.
"""
import itertools, sys

# --- offsets, by the axis the brief names -------------------------------------
# k is the BYTE offset of the addressed member. `addi` takes a signed 16-bit
# immediate, so >= 0x8000 is the interesting one (c2 must do something else).
OFFSETS = [0, 8, 0x8000, 0x10000]

HDR = r'''// W-SLOTARG capture grid (generated by work/grid_gen.py) — DO NOT EDIT.
// A byte-offset add in a call ARGUMENT slot: `f(&t->s.k)`.
struct T0 { int k; };                       // k at 0
struct T8 { int pad[2]; int k; };           // k at 8
struct T32768 { int pad[8192]; int k; };    // k at 0x8000
struct T65536 { int pad[16384]; int k; };   // k at 0x10000
// two designator steps: `&t->s.k`
struct U0 { struct { int k; } s; };
struct U8 { int pad[2]; struct { int k; } s; };
struct U32768 { int pad[8192]; struct { int k; } s; };
struct U65536 { int pad[16384]; struct { int k; } s; };

struct R {   // member-call callees: receiver takes slot 0
'''


def sig(nargs, addr_slot):
    """C++ parameter list for a callee with `nargs` args, address at addr_slot."""
    return ', '.join('int*' if i == addr_slot else 'int' for i in range(nargs))


def main():
    out = [HDR]
    callees = set()
    # member callees
    for nargs in range(1, 6):
        for addr_slot in range(nargs):
            callees.add((nargs, addr_slot))
    for nargs, addr_slot in sorted(callees):
        out.append(f'    void m{nargs}_{addr_slot}({sig(nargs, addr_slot)});\n')
    out.append('};\n')
    for nargs, addr_slot in sorted(callees):
        out.append(f'void f{nargs}_{addr_slot}({sig(nargs, addr_slot)});\n')
    out.append('\n')

    cells = []
    for steps, off, (nargs, addr_slot), kind in itertools.product(
            (1, 2), OFFSETS, sorted(callees), ('free', 'memb')):
        ty = ('T' if steps == 1 else 'U') + str(off)
        desig = 'k' if steps == 1 else 's.k'
        # the non-address arguments are LITERALS -> each needs one setup word,
        # so `nargs - 1` is exactly the walk length the rule is about.
        args = []
        for i in range(nargs):
            args.append(f'&t->{desig}' if i == addr_slot else str(10 + i))
        arglist = ', '.join(args)
        name = f'g_{kind}_{steps}s_{off}_{nargs}a_{addr_slot}'
        if kind == 'free':
            out.append(f'void {name}({ty}* t) {{ f{nargs}_{addr_slot}({arglist}); }}\n')
        else:
            out.append(f'void {name}(R* r, {ty}* t) {{ r->m{nargs}_{addr_slot}({arglist}); }}\n')
        cells.append(name)

    sys.stderr.write(f'{len(cells)} cells\n')
    open(sys.argv[1], 'w').writelines(out)


if __name__ == '__main__':
    main()
