#!/usr/bin/env python3
"""W-SLOTARG grid 3 — the OUT-OF-SAMPLE test.

The rule in work/rule.py was refined FOUR times against grids 1 and 2 (360
cells) until it agreed on all of them.  A rule refined against the data it is
scored on is fitted, not measured, so grid 3 varies axes neither earlier grid
contains, and its predictions are committed BEFORE it is captured:

  * the base formal clobbered by a MIDDLE walk word, not the last one
    (grids 1-2 always put the base at the lowest slot, so the clobbering `li`
    was always the final walk word);
  * offsets that straddle the signed-16-bit boundary from both sides
    (0x7ffc, 0x8000, 0x8004, 0xfffc, 0x10004) rather than only 0/8/0x8000/0x10000;
  * arities 6, 7 and 8 — past the 5 both earlier grids stop at;
  * a two-step designator whose steps STRADDLE the boundary (0x7ffc + 8), which
    no single-step cell can produce.
"""
import itertools, sys

OFFSETS = [0x7ffc, 0x8000, 0x8004, 0xfffc, 0x10004]

HDR = '// W-SLOTARG grid 3 (generated by work/grid3_gen.py) — DO NOT EDIT.\n'


def sig(nargs, addr_slot):
    return ', '.join('int*' if i == addr_slot else 'int' for i in range(nargs))


def main():
    out = [HDR]
    # structs: k at each offset (one designator step)
    for off in OFFSETS:
        assert off % 4 == 0, off
        out.append(f'struct T{off} {{ int pad[{off // 4}]; int k; }};\n')
    # a two-step designator straddling the boundary: outer pad 0x7ffc, inner 8
    out.append('struct U { int pad[8191]; struct { int pad2[2]; int k; } s; };\n')

    callees = sorted({(n, s) for n in range(1, 9) for s in range(n)})
    for nargs, addr_slot in callees:
        out.append(f'void f{nargs}_{addr_slot}({sig(nargs, addr_slot)});\n')
    out.append('\n')

    n = 0
    # (a) base parked in a MIDDLE register: `mid` dummy params before t, and
    #     enough after it that t's register is inside the call's slot range.
    for off, (nargs, addr_slot) in itertools.product(OFFSETS, callees):
        if nargs < 3:
            continue
        for mid in (1, 2):
            if mid >= nargs:
                continue
            pre = ', '.join(f'int d{i}' for i in range(mid))
            params = f'{pre}, T{off}* t'
            args = ', '.join('&t->k' if i == addr_slot else str(10 + i)
                             for i in range(nargs))
            name = f'w_{off}_{nargs}a_{addr_slot}_m{mid}'
            out.append(f'void {name}({params}) {{ f{nargs}_{addr_slot}({args}); }}\n')
            n += 1
    # (b) the straddling two-step designator, base at slot 0 and parked high
    for nargs, addr_slot in callees:
        args = ', '.join('&t->s.k' if i == addr_slot else str(10 + i)
                         for i in range(nargs))
        out.append(f'void v_lo_{nargs}a_{addr_slot}(U* t) '
                   f'{{ f{nargs}_{addr_slot}({args}); }}\n')
        pre = ', '.join(f'int d{i}' for i in range(nargs))
        out.append(f'void v_hi_{nargs}a_{addr_slot}({pre}, U* t) '
                   f'{{ f{nargs}_{addr_slot}({args}); }}\n')
        n += 2
    sys.stderr.write(f'{n} cells\n')
    open(sys.argv[1], 'w').writelines(out)


if __name__ == '__main__':
    main()
