#!/usr/bin/env python3
"""W-SLOTARG grid 2 — the DISCRIMINATING arrangement grid 1 could not reach.

In grid 1 the address's base formal always lives in r3 (free) or r4 (member),
which is the lowest call slot; so whenever the address is NOT at the lowest slot,
a literal lands on the base register and the base is clobbered.  Grid 1 therefore
never separates

    "the address sits at its own position in the descending walk"
from
    "the address is emitted FIRST"
from
    "the address is emitted SECOND"   (§9.13.1's SymAddr rule)

when the base is *not* clobbered.  That is §9.13.1's blind spot in a new costume:
an axis the generator does not vary is exactly as invisible as a fixture that
does not arrange the case.

Fix: park the base formal in a register ABOVE every slot the call writes, by
giving the caller leading dummy int parameters.  Then the base survives the whole
walk and the address's position is a free choice c2 has to make.
"""
import itertools, sys

OFFSETS = [0, 8, 0x8000, 0x10000]

HDR = r'''// W-SLOTARG grid 2 (generated by work/grid2_gen.py) — DO NOT EDIT.
// The address's base formal is parked ABOVE every slot the call writes, so the
// base is NOT clobbered by the walk and the address's position is a free choice.
struct T0 { int k; };
struct T8 { int pad[2]; int k; };
struct T32768 { int pad[8192]; int k; };
struct T65536 { int pad[16384]; int k; };
'''


def sig(nargs, addr_slot):
    return ', '.join('int*' if i == addr_slot else 'int' for i in range(nargs))


def main():
    out = [HDR]
    callees = sorted({(n, s) for n in range(1, 6) for s in range(n)})
    for nargs, addr_slot in callees:
        out.append(f'void f{nargs}_{addr_slot}({sig(nargs, addr_slot)});\n')
    out.append('\n')

    n = 0
    for off, (nargs, addr_slot) in itertools.product(OFFSETS, callees):
        ty = f'T{off}'
        # `pad` leading dummy params push the base formal past the call's slots.
        # The call writes slots 0..nargs-1 => registers r3..r(2+nargs).
        # Base must land at r(3+pad) > r(2+nargs)  =>  pad >= nargs.
        for pad in (nargs, nargs + 1):
            params = ', '.join([f'int d{i}' for i in range(pad)] + [f'{ty}* t'])
            args = ', '.join('&t->k' if i == addr_slot else str(10 + i)
                             for i in range(nargs))
            name = f'h_{off}_{nargs}a_{addr_slot}_p{pad}'
            out.append(f'void {name}({params}) {{ f{nargs}_{addr_slot}({args}); }}\n')
            n += 1
    sys.stderr.write(f'{n} cells\n')
    open(sys.argv[1], 'w').writelines(out)


if __name__ == '__main__':
    main()
