#!/usr/bin/env python3
"""addrows.py — append this lane's BOARD.md rows to the right three sections.

One-shot; kept in the lane's scratch so the edit is reproducible rather than
hand-applied. `docs/BOARD.md` is hand-maintained (its own header says so), so
this only appends to the end of an existing table and never rewrites a row.
"""
import sys

P = "docs/BOARD.md"
lines = open(P).read().split("\n")

OPEN_ROWS = [
    "| **931**<sub>w-rtti</sub> | **`.in` ELEMENT TAG `02` IS THE WHOLE RTTI READER GAP — and the three \"irreducible\" layout integers are literally in the stream** | **MEASURED, and it re-shapes #160's rung three rather than sizing it.** `OBJ_RDATA_R_SHAPE.md` §4 scored a synthesizer that rebuilds records from mangled names at **3,337 of 3,570** and named `??_R4.offset`, `??_R4.cdOffset` and `??_R3.attributes` as the residue — *\"not recoverable from a mangled symbol, which is why they are the reader's job\"*. They do not have to be recovered: `.in` spells every record's contents element by element, `??_R3.numBaseClasses` and `??_R1`'s `pdisp = -1` and `attributes = 0x40` included. Element tags `01` (scalar) and `03` (byte string) are **already read** by `ininit.rs`/`inlit.rs`; the one missing tag is **`02` — `<token> 00 <n>`, the address of another symbol** — which `InInitResidue::SymbolAddress` refuses by design, citing `OBJ_DATA_BSS_SHAPE.md` §8.6's *\"unexercised\"* | The same tag blocks a **plain** `.data` object today: `struct A{virtual void f();int a;}; A g;` statically initializes `?g@@3UA@@A` with a vfptr **relocation**, and the `.gl` data reader returns **1 of 12** records on that TU — the `$initializer$`, not the object | rungs/2026-08-07-w-rtti.md §4.2; docs/OBJ_RDATA_R_SHAPE.md §8.1; `crates/c2-il/src/func/ininit.rs` `InInitResidue::SymbolAddress` | **This does not lower #926's count of seven** — a cheaper fact is still a fact — but it changes which lane can pay it. `w-rdata` reported item 2 to `w-vocab` as *\"a reader for the `??_R*` record graph\"*, i.e. a derivation engine; it is ordinary element-tag work with a graded consumer (`emit_data_obj`) already in the tree. **Tag `02` is worth measuring on its own**, before any RTTI: it is the gap between the `.data` writer that exists and every initializer that names a symbol |",
]

DECLINED_ROWS = [
    "| **926**<sub>w-rtti</sub> | **THE `.rdata$r` WRITER — re-priced at a new master by a lane BRIEFED TO SHIP IT, and declined a second time** | **DECLINED. The price re-derives at seven and NOT ONE of the seven has been paid** since `w-rdata` measured them 2026-08-04, across 20+ commits and several `c2-il` widenings. Two were re-measured directly rather than inherited: `c2rs census` on the minimal source reads **`0/1 functions in class`** at `expr-op-0x27`, and `c2rs diff` reads `ReferenceReplay=ByteExact (ref=1033B replay=1033B) Port=NotImplemented`; and `c2-il`'s `.gl` data-record reader returns **0 of the 6 data records** in that 11-section obj, against **2 of 2** on a `.data` positive control — so the zero is a reading, not a broken probe. The lane's `PREREG.md` P9 registered the decline floor (a `Section` literal **plus** a caller reachable from `PortC2::build` **plus** one byte-exact graded obj) before any probe existed, and it fired | `factor-c` **169 → 169**; `b-and-c` 151, `a-and-b-and-c` 27, `frontier` 17, `writer-sections` 10, `ladder-head .rdata$r → 590`. **All 77 `gap-metric` lines byte-identical before and after**, `match 10 / mismatch 0 / capture-fail 7`, FBM partition `exact 34466 · differs 4711 · partition-broken 0 · match-tu-differs 0` | rungs/2026-08-07-w-rtti.md §4; `work/w-rtti/PREREG.md` §1.3; docs/OBJ_RDATA_R_SHAPE.md §8.1 | **The brief asked for +421 of factor C and the honest answer is that the port's content model reaches ZERO `.rdata$r` records**, so *\"emit it byte-exactly where the content model reaches\"* emits nothing. What shipped instead is the guard that makes the decline enforceable (#927) rather than a matter of lane discipline, plus a re-verified spec (#928–#930, #933). **`w-joint2`'s reading stands and this lane reproduced its inputs**: `A∧B` = 27 all inside C, `|D∨E|` = 10, 0 of the 676 `.rdata$r` TUs in `D∨E` — so the step is worth **+0** TU match whenever it is paid |",
    "| **929**<sub>w-rtti</sub> | **A VFTABLE'S `Selection 6` / symbol `Value 4` IS A `/GR` PROPERTY, not a vftable property** | **REFUTED as unconditional — 0 of 27 at `/GR-`.** `OBJ_RDATA_R_SHAPE.md` §3 states it flatly. At `/GR-` the same 27 `??_7` vftables over the same 18 sources read Selection **2** and `Value` **0**: the complete-object locator that occupies `vftable[-1]` is what displaces the symbol and earns LARGEST, and without RTTI there is none. It holds **27/27** at `/GR` | 72 objs at four profiles; the `/GR-` column also confirms §10.20's *\"it dies at `/GR-`\"* at **0 `.rdata$r` sections and 0 `??_R0` COMDATs on all 18 cells** | rungs/2026-08-07-w-rtti.md §3; docs/OBJ_RDATA_R_SHAPE.md §3.1(b); `work/w-rtti/verify_GRminus.txt` | **Not a live hazard** — the workload is 100 % `/GR`. It is a *keying* hazard: a writer that treats Selection 6 as a fact about vftables has hidden a `/GR` dependency inside a section emitter, which is the shape §7's `/Od` divergence already takes one level up |",
]

DONE_ROWS = [
    "| **927**<sub>w-rtti</sub> | **BOARD #301 IS CLOSED — the second half of the writer-vocabulary guard** | **DONE, and measured by a two-break counterfactual rather than asserted.** `coff::tests::every_production_emitter_has_a_lib_rs_caller` asserts every `pub fn emit_*` present in a **non-test** build is named by `lib.rs`. `emit_mvp_obj` — #301's named live instance, whose only caller was `coff/tests.rs` — is `#[cfg(test)]` rather than exempted, because an allow-list is the thing that goes stale. `work/w-rtti/counterfactual.sh`: **BREAK 1** (the constant alone) → vocabulary test **FAILED**, this one ok; **BREAK 2** (the constant **plus** an uncalled emitter carrying a real `.rdata$r` `Section` literal) → vocabulary test **ok**, this one **FAILED**; RESTORE → `git status --porcelain crates/` = **0 path(s)**, both ok. BREAK 2 is #301's hole, reproduced on demand and then caught | rungs/2026-08-07-w-rtti.md §5; `work/w-rtti/counterfactual_out.txt`; `crates/c2-core/src/coff/tests.rs`, `function.rs` `PORT_WRITER_SECTIONS` doc |",
    "| **928**<sub>w-rtti</sub> | **`??_8` IS NOT `??_7` — a vbtable is Selection 2 and `Value` 0, and the spec states one rule for both** | **REFUTED 0 of 4, inside a spec that re-verified at 21 of 23 claims over 72 FRESH objs.** `OBJ_RDATA_R_SHAPE.md` §6 calls it *\"the vftable/vbtable block\"* and §3 gives the block Selection **6** and `Value` **4**. That is the **vftable's** rule: `??_7` holds 27/27, and all four `??_8` vbtables in the fresh grid (the virtual-inheritance cells) read Selection **2**, `Value` **0**, Characteristics `0x40301040` 4/4 — so the two records differ in exactly the two fields a writer sets. Everything else held: chars 139/139, sel-2 139/139, ADDR32 268/268, `coff_checksum` **174/174**, `??_R0` size/name/spare 35/35 each, `??_R1`'s four fields spelled in its own name 42/42, `??_R2` size `== 4*(n+1)` 35/35 | 18 sources frozen in `work/w-rtti/grid_list.txt` **before** any capture, × 4 profiles = **72 objs**; 139 `.rdata$r` + 35 `??_R0` = **174 records** at `/O1` | rungs/2026-08-07-w-rtti.md §3; docs/OBJ_RDATA_R_SHAPE.md §0.1, §3.1(a); `work/w-rtti/verify.py`, `verify_O1.txt` |",
    "| **930**<sub>w-rtti</sub> | **THE RTTI GROUP IS CUT AT THE VFTABLE RUN, NOT AT THE `.text` COMDAT — and the two are not in bijection** | **CORRECTED, and the corrected rule is exact at all three optimization modes.** §5's DFS pre-order and §6's non-interleave are individually right and compose wrongly. One global walk rooted at every vftable is **16 of 18** objs; cutting a group at each `.text` COMDAT is **21/21** at `/O1` but **17/19** at `/Od` and **16/18** at `/Ox`; cutting at each **vftable run** is **21/21 · 22/22 · 21/21**. The `.text` cut fails because the `.text` is not always there: `f11_three_classes` has three constructors and three vftable+RTTI blocks, and at `/Od` and `/Ox` it carries **ONE** `.text` COMDAT and still three blocks — block order unchanged and equal to the order the constructors are **defined** in | §2's *\"a `.rdata$r` TU always has at least one `.text` COMDAT\"* SURVIVES — true on all 72 objs, and four probes in `work/w-rtti/probe/` looked for a zero-`.text` counterexample and found none (a namespace-scope object of a polymorphic class is **statically** initialized, vfptr relocation and all, and still drags the ctor COMDAT in) | rungs/2026-08-07-w-rtti.md §3.2; docs/OBJ_RDATA_R_SHAPE.md §6.1 |",
    "| **932**<sub>w-rtti</sub> | **THE NEW GUARD CAUGHT ITS OWN AUTHOR FIRST — a name-suffix filter is an allow-list wearing a different hat** | **DONE, and the failure is kept in the record.** #927's test read `pub fn emit_*_obj` for one commit. The counterfactual's BREAK 2 emitter was named `emit_rtti_obj_counterfactual`, which does not **end** in `_obj`, so the population excluded it and **BREAK 2 passed both tests on the first run** — the exact inflation the test exists to catch, waved through by the test's own naming convention. It reads every `pub fn emit_*` now, and the population count (**5**) is asserted so a run that checks nothing cannot read like a run that checks everything | rungs/2026-08-07-w-rtti.md §5.1; `crates/c2-core/src/coff/tests.rs` `every_production_emitter_has_a_lib_rs_caller` |",
    "| **933**<sub>w-rtti</sub> | **§7's `/Od` TWO-VFTABLE DIVERGENCE REPRODUCES ON A FRESH CELL — and the shape it needs is narrower than \"base and derived\"** | **CONFIRMED, and narrowed.** `OBJ_RDATA_R_SHAPE.md` §7 records board **#295**'s divergence and notes it did *not* reproduce on `w-rdata`'s simpler grid. `f14_vdtor_derived.cpp` — virtual destructors on base **and** derived — reads **4 records / 1 vftable at `/O1` and `/Ox`** and **8 records / 2 vftables at `/Od`**, and is the **only one of the eighteen** sources whose record count moves with the optimization mode. So the shape needs the virtual **destructor** on both levels, not merely a base and a derived | 18 sources × `/O1` `/Od` `/Ox`: record counts fixed on 17 of 18; `f08` and `f11` move their **section** counts (#930) with their record counts fixed | rungs/2026-08-07-w-rtti.md §3.3; docs/OBJ_RDATA_R_SHAPE.md §7 |",
]


def insert_after_last_row(lines, heading, rows):
    i = next(k for k, L in enumerate(lines) if L.strip() == heading)
    j, last = i + 1, None
    while j < len(lines) and not lines[j].startswith("## "):
        if lines[j].startswith("| "):
            last = j
        j += 1
    assert last is not None, heading
    return lines[: last + 1] + rows + lines[last + 1:]


lines = insert_after_last_row(lines, "## Open", OPEN_ROWS)
lines = insert_after_last_row(
    lines, "## Declined and refuted — the rows that saved work", DECLINED_ROWS
)
lines = insert_after_last_row(lines, "## Done", DONE_ROWS)
open(P, "w").write("\n".join(lines))
print("rows added:", len(OPEN_ROWS) + len(DECLINED_ROWS) + len(DONE_ROWS))
sys.exit(0)
