// w-counted — the /Ox ACCEPTED-SET CROSS. Generated by work/w-counted/gen_cells.py.
// One function per TU, every cell inside counted_accum_loop's closed recognizer.
// The axes crossed: accumulate opcode (7) x counter signedness (2), plus the
// simm16 init edges and the braced body on BOTH signednesses. wbdnz_ctr.cpp
// grades the signed column and exactly ONE unsigned cell; this file is the rest.

int c_sar_u(unsigned n, int k) { int s = 1; for (unsigned i = 0; i < n; ++i) s >>= k; return s; }
