#!/usr/bin/env python3
"""gen_isa_table.py -- regenerate `tools/vmx/vmx128_isa.py` from powerpc-rs'
`isa.yaml`.

This is the ONLY script here that needs PyYAML and a network fetch. Its output
(`vmx128_isa.py`) is committed, so every other script in `tools/vmx/` is pure
stdlib and works offline -- the same shape as `crates/c2-obj/src/reloc.rs`,
which carries a hand-ported `IMAGE_REL_PPC_*` table rather than a dependency.

SOURCE, cited the way `reloc.rs` cites its own:

  encounter/powerpc-rs, `isa.yaml`
  https://github.com/encounter/powerpc-rs/blob/main/isa.yaml
  last commit touching that path: 4643ee0fd3275e3a89dee709185c37968acca83b
                                 (2025-07-07)
  sha256 of the fetched file:
      5c3a3a7f8447b0b812f8012e422b941a8be095233a9634c906263dd95cb5e170

  `isa.yaml` is also the source the dc3 workload's own
  `src/xdk/LIBCMT/vectorintrinsics.h` points a reader at, by URL, in its
  comments. It is a community reverse-engineering artifact, not a Microsoft
  document, and it is NOT independent evidence on its own -- see
  `docs/VMX128_DECODE.md` §2. Everything in the generated table is graded
  against the real `cl.exe`'s own `/FAcs` listing by `tools/vmx/vmxcheck.py`.

Nothing here is derived from disassembling `c2.dll`; no `docs/whitebox/`
DISCLOSURE row is required. Decoding the Xbox 360 ISA from public tables and
from the compiler's own published listing output is black-box observation.

Usage:
    tools/vmx/gen_isa_table.py [--isa <path-to-isa.yaml>] [-o <out.py>]

With no --isa it fetches the file over the network into a temp path.
"""
import argparse
import hashlib
import os
import subprocess
import sys
import tempfile

ISA_URL = "https://raw.githubusercontent.com/encounter/powerpc-rs/main/isa.yaml"
ISA_COMMIT = "4643ee0fd3275e3a89dee709185c37968acca83b"
ISA_SHA256 = "5c3a3a7f8447b0b812f8012e422b941a8be095233a9634c906263dd95cb5e170"

HEADER = '''\
#!/usr/bin/env python3
"""vmx128_isa.py -- the VMX128 and opcode-4/5/6 PowerPC encoding tables.

GENERATED by `tools/vmx/gen_isa_table.py`. Do not hand-edit; regenerate.

Transcribed from encounter/powerpc-rs `isa.yaml`
(https://github.com/encounter/powerpc-rs/blob/main/isa.yaml), commit
{commit}, file sha256 {sha}.

That file is a community reverse-engineering artifact, not a Microsoft
document. It is not independent evidence about what `c2.dll` emits; it is a
hypothesis. `tools/vmx/vmxcheck.py` grades it against the real `cl.exe`'s own
`/FAcs` assembly listing, which is the oracle. See `docs/VMX128_DECODE.md`.

Nothing here comes from disassembling `c2.dll`. No `docs/whitebox/DISCLOSURE.md`
row is required for this table.

Bit numbering below is IBM PowerPC convention: bit 0 is the MOST significant
bit of the 32-bit instruction word, bit 31 the least. A field spec
`"28..30,6..11"` is a list of half-open ranges, concatenated most-significant
part first: bits 28,29 supply the top 2 bits and bits 6..10 the bottom 5.
"""

# (name, bitmask, pattern, args-tuple)
VMX128 = [
'''


def esc(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--isa")
    ap.add_argument("-o", "--out", default=os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "vmx128_isa.py"))
    a = ap.parse_args()

    try:
        import yaml
    except ImportError:
        print("SKIP: PyYAML absent -- vmx128_isa.py is committed; "
              "regeneration is optional", file=sys.stderr)
        return 0

    path = a.isa
    if not path:
        path = os.path.join(tempfile.mkdtemp(), "isa.yaml")
        rc = subprocess.call(["curl", "-sS", "-L", "-o", path, ISA_URL])
        if rc != 0 or not os.path.exists(path):
            print("SKIP: could not fetch isa.yaml (no network?)", file=sys.stderr)
            return 0

    raw = open(path, "rb").read()
    got = hashlib.sha256(raw).hexdigest()
    if got != ISA_SHA256:
        print("WARNING: isa.yaml sha256 %s != pinned %s -- upstream moved. "
              "Re-verify against the /FAcs oracle before trusting the table."
              % (got, ISA_SHA256), file=sys.stderr)

    d = yaml.safe_load(raw)
    vmx = d["extensions"]["Vmx128"]

    # Everything that shares primary opcode 4, 5 or 6 with VMX128 -- these are
    # the only base/AltiVec encodings that can possibly collide.
    others = []
    for op in d["opcodes"]:
        if (op["pattern"] >> 26) in (4, 5, 6):
            others.append((op["name"], op["bitmask"], op["pattern"], "base",
                           op.get("args", [])))
    for extname, ext in d["extensions"].items():
        if extname == "Vmx128":
            continue
        for op in ext["opcodes"]:
            if (op["pattern"] >> 26) in (4, 5, 6):
                others.append((op["name"], op["bitmask"], op["pattern"], extname,
                               op.get("args", [])))

    out = [HEADER.format(commit=ISA_COMMIT, sha=got)]
    for op in vmx["opcodes"]:
        out.append("    (%-16s 0x%08x, 0x%08x, (%s)),\n" % (
            esc(op["name"]) + ",", op["bitmask"], op["pattern"],
            "".join(esc(x) + ", " for x in op.get("args", []))))
    out.append("]\n\n")

    out.append("# Field bit specs, IBM bit numbering, half-open ranges,\n"
               "# most-significant part first. name -> (bits, arg-kind, signed)\n")
    out.append("FIELDS = {\n")
    seen = set()

    def emit_field(f):
        if "bits" not in f or f["name"] in seen:
            return
        seen.add(f["name"])
        out.append("    %-12s (%s, %s, %s),\n" % (
            esc(f["name"]) + ":", esc(f["bits"]), esc(f.get("arg") or ""),
            "True" if f.get("signed") else "False"))

    for f in vmx["fields"]:
        emit_field(f)
    for f in d["fields"]:
        emit_field(f)
    for extname, ext in d["extensions"].items():
        for f in ext.get("fields", []):
            emit_field(f)
    out.append("}\n\n")
    mods = vmx.get("modifiers") or []
    out.append("VMX128_MODIFIERS = [\n")
    for m in mods:
        out.append("    (%s, %s, %d),\n" % (esc(m["name"]), esc(m["suffix"]), m["bit"]))
    out.append("]\n\n")

    out.append("# Every non-VMX128 encoding in the same primary opcodes (4/5/6).\n"
               "# (name, bitmask, pattern, source-extension, args-tuple)\n")
    out.append("OPCODE456_OTHER = [\n")
    for name, mask, pat, src, args in sorted(others, key=lambda x: (x[2], x[0])):
        out.append("    (%-16s 0x%08x, 0x%08x, %-10s (%s)),\n" % (
            esc(name) + ",", mask, pat, esc(src) + ",",
            "".join(esc(x) + ", " for x in args)))
    out.append("]\n")

    with open(a.out, "w") as fh:
        fh.write("".join(out))
    print("wrote %s: %d VMX128 opcodes, %d other opcode-4/5/6 encodings"
          % (a.out, len(vmx["opcodes"]), len(others)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
