#!/usr/bin/env python3
"""genprobe.py -- emit a C++ translation unit that tries to make the real
`cl.exe` emit every VMX128 opcode, so `vmxcheck.py` has something to verify
beyond the 8 mnemonics the dc3 workload happens to contain.

Pure stdlib. Tooling, outside the std-only Rust workspace.

HOW THIS WORKS, AND ITS ONE LIMIT
---------------------------------
The Xbox 360 compiler has no PPC inline assembler, so an instruction can only
be requested through a *named compiler intrinsic*. The workload's own
`src/xdk/LIBCMT/vectorintrinsics.h` documents the trick: declare
`XMVECTOR __vmaddfp(XMVECTOR, XMVECTOR, XMVECTOR);` and the compiler recognises
the name and emits the instruction -- no definition needed.

So this generator guesses `__` + the isa.yaml mnemonic with `128` stripped, for
all 77 rows. **Guessing the name is not the same as knowing it**, and a name
the compiler does NOT recognise produces a `bl` to an unresolved symbol instead
of a vector instruction -- which is *visible* (no opcode-4/5/6 word appears)
and is reported as such rather than silently counted as coverage. The generated
TU is compiled, never linked.

Usage:
    tools/vmx/genprobe.py > work/w-vmx/probe/probe.cpp
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vmx128_isa as ISA          # noqa: E402

PROLOGUE = '''\
// GENERATED by tools/vmx/genprobe.py -- do not hand-edit.
//
// A probe TU whose only purpose is to make the real cl.exe emit as much of the
// VMX128 opcode space as it can be persuaded to emit, so that tools/vmx's
// decoder can be graded against the compiler's own /FAcs listing on more than
// the 8 mnemonics the dc3 workload contains. Compiled, never linked.
//
// The __vector4 typedef is the workload's own, from
// src/xdk/LIBCMT/vectorintrinsics.h, reproduced so this file needs no include
// path into the dc3 tree.

typedef struct __declspec(intrin_type) __declspec(align(16)) __vector4 {
    union {
        float vector4_f32[4];
        unsigned int vector4_u32[4];
        float v[4];
        unsigned int u[4];
    };
} __vector4;
typedef __vector4 XMVECTOR;

extern "C" {
'''

EPILOGUE_HEAD = '''\
}

// Each probe is its own function so that every instruction lands in its own
// COMDAT and cannot be folded with another. `volatile` sinks stop the
// optimiser from deleting the whole body at /O1.
extern XMVECTOR g_sink;
extern void *g_mem;

'''


# Arities MEASURED, not guessed: cl.exe answers a wrong declaration with
#
#   warning C4392: 'XMVECTOR __vmaddfp(XMVECTOR,XMVECTOR)' : incorrect number
#   of arguments for intrinsic function, expected '3' arguments
#
# so the compiler itself names the shape. Every row below was read off a
# C4392 from `tools/vmx/listing.sh` on an earlier draft of this file.
# `"D"` marks the operand that is the destination register used as a source --
# isa.yaml's `args` omits it, cl.exe's intrinsic requires it, and cl's own
# listing prints it. That is the discrepancy `vmx128.py:DEST_IS_ALSO_SOURCE`
# encodes.
ARITY_OVERRIDE = {
    "vmaddfp128":   ["D", "VA128", "VB128"],
    "vmaddcfp128":  ["D", "VA128", "VB128"],
    "vnmsubfp128":  ["D", "VA128", "VB128"],
    "vsel128":      ["D", "VA128", "VB128"],
    "vpkd3d128":    ["D", "VB128", "imm", "imm", "imm"],
    "vrlimi128":    ["D", "VB128", "imm", "imm"],
    "vspltisw128":  ["imm"],
    "vmsum3fp128":  ["VA128", "VB128"],
    "vmsum4fp128":  ["VA128", "VB128"],
    "vupkd3d128":   ["VB128", "imm"],
    "vpermwi128":   ["VB128", "imm"],
    "vsldoi128":    ["VA128", "VB128", "imm"],
}


def sig_for(name, args):
    ov = ARITY_OVERRIDE.get(name)
    if ov is not None:
        params, callargs, i = [], [], 0
        for k in ov:
            if k == "imm":
                i += 1
                params.append("unsigned int")
                callargs.append(str(i))
            else:
                params.append("XMVECTOR")
                callargs.append("abc"[len(callargs) % 3])
        base = "__" + name.replace("128", "")
        return ("XMVECTOR %s(%s);" % (base, ", ".join(params)),
                lambda: "%s(%s)" % (base, ", ".join(callargs)), "XMVECTOR")
    return _sig_default(name, args)


def _sig_default(name, args):
    """Return (decl, call-expr-builder) or None if we do not know a shape."""
    base = "__" + name.replace("128", "")
    a = list(args)
    if a[:1] == ["VDS128"] and a[1:] == ["rA", "rB"]:
        if name.startswith("st"):
            return ("void %s(XMVECTOR, void *, int);" % base,
                    lambda: "%s(a, g_mem, 0)" % base, "void")
        return ("XMVECTOR %s(const void *, int);" % base,
                lambda: "%s(g_mem, 0)" % base, "XMVECTOR")
    kinds = a[1:]
    params, callargs = [], []
    ok = True
    imm = 1
    for k in kinds:
        if k in ("VA128", "VB128", "VC128"):
            params.append("XMVECTOR")
            callargs.append("abc"[len(callargs) % 3])
        elif k in ("vuimm", "vsimm", "PERM", "D3DType", "VMASK", "Zimm", "SHB"):
            params.append("unsigned int")
            callargs.append(str(imm))
            imm += 1
        else:
            ok = False
    if not ok:
        return None
    return ("XMVECTOR %s(%s);" % (base, ", ".join(params)),
            lambda: "%s(%s)" % (base, ", ".join(callargs)), "XMVECTOR")


def pressure_body(fn, expr, ret, live):
    """Wrap one probe in enough live __vector4 values to push the allocator
    above vr31, which is the ONLY way to see the 128-register forms.

    Measured, not assumed: with two live vectors cl.exe emits plain AltiVec
    `lvsl vr0,r0,r11` and `vmaddfp`, not `lvsl128` / `vmaddfp128`. The `128`
    suffix on a three-operand op is not a different operation, it is the same
    operation encoded so that a register number above 31 fits. So a probe that
    does not create register pressure cannot reach 20 of the 77 rows.
    """
    ls = ["    __vector4 t%d = p[%d];" % (i, i) for i in range(live)]
    acc = " ".join("s = __vaddfp(s, t%d);" % i for i in range(live))
    if ret == "void":
        act = "    %s;" % expr
    else:
        act = "    __vector4 r = %s; s = __vaddfp(s, r);" % expr
    return ("void %s(const __vector4 *p, __vector4 *q) {\n"
            "%s\n"
            "    __vector4 a = t0, b = t1, c = t2; (void)a; (void)b; (void)c;\n"
            "    __vector4 s = t0;\n"
            "%s\n"
            "    %s\n"
            "    *q = s;\n}\n" % (fn, "\n".join(ls), act, acc))


def main():
    live = 0
    if "--pressure" in sys.argv:
        i = sys.argv.index("--pressure")
        live = int(sys.argv[i + 1]) if len(sys.argv) > i + 1 else 40
    decls, bodies, skipped = [], [], []
    for name, _mask, _pat, args in ISA.VMX128:
        s = sig_for(name, args)
        if s is None:
            skipped.append(name)
            continue
        decl, call, ret = s
        decls.append(decl)
        fn = "probe_" + name
        if live:
            bodies.append(pressure_body(fn, call(), ret, live))
            continue
        if ret == "void":
            bodies.append(
                "void %s(XMVECTOR a, XMVECTOR b, XMVECTOR c) {\n"
                "    (void)b; (void)c;\n"
                "    %s;\n}\n" % (fn, call()))
        else:
            bodies.append(
                "void %s(XMVECTOR a, XMVECTOR b, XMVECTOR c) {\n"
                "    (void)b; (void)c;\n"
                "    g_sink = %s;\n}\n" % (fn, call()))

    out = [PROLOGUE]
    seen = set()
    for d in decls:
        if d not in seen:
            seen.add(d)
            out.append("    " + d + "\n")
    out.append(EPILOGUE_HEAD)
    out.extend(bodies)
    if skipped:
        out.append("// no known signature shape, not probed: %s\n"
                   % ", ".join(skipped))
    sys.stdout.write("\n".join(out) if False else "".join(out))
    print("// probes emitted: %d of %d VMX128 opcodes"
          % (len(bodies), len(ISA.VMX128)), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
