#!/usr/bin/env python3
"""board_rows.py — insert lane w-inline's rows #896-#905 into docs/BOARD.md.

Lane w-inline tooling. Each row goes into the section its status earns
(`docs/BOARD.md` "Conventions"), and the script is idempotent: it refuses to run
twice by checking for its own numbers first.
"""
import os
import sys

P = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..",
                 "docs", "BOARD.md")

OPEN_ROWS = """| **897**<sub>w-inline</sub> | **MECHANISM E IS A SYNTACTIC FACT AND IT IS WORTH 1,886 OF THE 4,711 — #877's decline is re-priced** | **MEASURED: 532 of 532 sampled family-A callers have NO same-TU callee even at `/Ob0`**, over 120 frozen workload TUs, against the standing instrument's own `fnbyte-differs-fn` witness keys. The repair is not a cost model: *a call edge whose callee is defined in this bundle and whose IL body is empty emits no branch, no REL24 and no external symbol*. Needs no size, no linkage and no schedule | docs/INLINE_PREDICATE.md §0, §1, §6 item 1; rungs/2026-08-07-w-inline.md §5; `work/w-inline/retrodict.py`, `ctl_ob0.py` | **#877 declined the cheap repair because *"the predicate ('c2 will inline this') is a COST MODEL, not a syntactic fact"*. That reasoning is right about mechanism I and wrong about the family it was applied to.** `IlBundle` already carries a special case of exactly this rule — `eh_unwind_callees` accounts the base destructor an empty constructor names, *"on the cheap side there is no funclet, so c2 emits no `bl`"* (`bundle.rs`) — so the general form is a widening of an accounting the crate has, not a new class of judgement. **Still not taken here**: `PREREG.md` §5's second floor forbids this lane shipping a port change, and E's exact source predicate is bounded by three probes and no more (spec §7) |
| **900**<sub>w-inline</sub> | **THE 48-BYTE LEAF TERM IS REAL AND NO COMPILATION SUPPLIES ITS INPUT — the port is better placed than any obj-side instrument** | **MEASURED, three derivations, two corpora.** GRID-2b's hand ladders step at `s = 112/116` = 64/68 **+ 48 exactly**, so LC:§6.18.6's term reproduces at the workload's flags. On the workload the same term must be **dropped** to score best: SAMPLE-B reads **0.9631** with the leaf bit from the `/O1` obj, **0.9716** with the term dropped, **0.9688** with it from the `/Ob0` obj; on GRID-2b the same three read **0.9980 / 0.8401 / 0.9980** | docs/INLINE_PREDICATE.md §5; rungs/2026-08-07-w-inline.md §4; `work/w-inline/grade_pair.py --both` | **LC:§6.19.6 already said the index is *"a post-allocation byte count, minus 48 for a predicate that is false in the emitted code and true only upstream of it"* — this is that sentence costing something.** `/O1` over-reports leaf (a callee whose own calls were inlined away reads leaf); `/Ob0` under-reports it (c2 decides bottom-up, so a callee's own inlinable calls are gone by the time it is priced). The truth is between and is **NOT MODELLED**. **The IL has it**: the bundle carries the callee's un-lowered body, so a recognizer can ask *"does this body contain a call"* directly — the one input where the port beats every obj-side instrument |
| **901**<sub>w-inline</sub> | **A CALL SITE INSIDE A `/EHsc` UNWIND FUNCLET IS NEVER INLINED — a site class the incumbent's captures cannot contain** | **MEASURED: on `src/system/rndobj/Utl.cpp` alone, 40 of 73 apparent falsifications of `INLINE-P` are callees whose ONLY caller is a `__unwind$N` funclet.** Every capture in LC:§6.15–§6.20 is at `/O1 /GS- /c`, where no funclet exists. Excluding funclet sites moves the one-sided falsification rate on SAMPLE-A from **0.1738 to 0.1205** | docs/INLINE_PREDICATE.md §2; `work/w-inline/PREREG.md` ADDENDUM 1 R1; `work/w-inline/scan_obj.py::caller_kind` | Third member of the family LC:§6.18.4 opened (an indirect site has no callee to price) and §6.19.9 extended (a conditional site moves the ceiling by 96 bytes). **It does not bite the port directly** — the port emits no funclets — but any obj-side grader that counts them reads the rule as far worse than it is, and this row is why `caller_kind` exists. The funclet's `$N` is also a **compilation-local counter**, so a funclet edge cannot be paired across two compilations even in principle |
"""

DECL_ROWS = """| **896**<sub>w-inline</sub> | **BOARD #877 / `w-fnbyte` §5.2 — *"the cause is c2's INLINER"*, demonstrated on `void g(){} void f(){ g(); }`** | **REFUTED for that probe and for the family it was applied to.** Recompile the identical probe at the workload's own flags with **`/Ob0` appended** — inline expansion OFF — and `?f` is **still** `4e800020`, 4 bytes, 0 relocations. There is no expansion to disable. The discriminator is one line away: `int g(int a){ return a; }` **emits the identical single `blr` word** and its call **SURVIVES `/Ob0`**, while `void g(int a){ }` does not. **The elision reads the callee's SOURCE body, not its emitted one, and is not governed by `/Ob` at all.** The bytes `w-fnbyte` reported are exactly right; the mechanism is not | family A = **1,886 of 4,711** (40 %) attributed to the wrong mechanism; **532 of 532** sampled family-A callers confirm the correction | rungs/2026-08-07-w-inline.md §5; docs/INLINE_PREDICATE.md §0–§1; `work/w-inline/ctl_ob0.py` p2/p6/p8, positive control p4 |
| **904**<sub>w-inline</sub> | **THIS LANE'S OWN GRID-2 — 360 cells, 360 HIT, and the number meant nothing** | **VACUOUS, and the stamp is kept in the tree.** Its rung was `v = v * m + m`, which is affine in the parameter, so c2 folded the whole ladder to one multiply-add and `s` ran **4 → 28** over k = 0..14: every cell sat inside SCHEDULE D's `unbounded` band and the ladder never reached the 64/68 step it was built to test. Re-frozen as GRID-2b with three **measured** rung kinds (12 B, 12 B, 8 B; gcd 4), reaching every 4-byte `s` from 4 to 136 and on to ~330 | first stamp `b8f314da…` (360 cells, `work/w-inline/grid2/GRID.sha256`), replacement `0c5f520c…` (5,376 cells) | rungs/2026-08-07-w-inline.md §3.1; `work/w-inline/grid.py` module doc |
"""

DONE_ROWS = """| **898**<sub>w-inline</sub> | **`INLINE-P` — LC:§6.15–§6.20 STATED AS ONE FUNCTION AND GRADED ON THE WORKLOAD, WHERE IT HOLDS** | **HOLD-OUT: 9,709 of 9,993 callees = 0.9716** over **100 `sha256`-frozen workload TUs never looked at before the rule was frozen**, against a majority-class baseline of **0.6434**; precision 0.969 / recall 0.988 on `INLINED-ALL`. Diagnostic SAMPLE-A (20 TUs, 12,242 callees) reads **0.9760** at baseline 0.7232. Graded in **both** directions: each TU is compiled twice, the second time with `/Ob0` appended, so `n_sites` is measured by the compiler and a rule cannot score by being conservative | rungs/2026-08-07-w-inline.md §2, §4; docs/INLINE_PREDICATE.md §2–§3; `work/w-inline/grade_pair.py`, `sample_b.txt` (`c2eeba0c…`) |
| **899**<sub>w-inline</sub> | **THE 64/68 STEP REPRODUCES ON 11,866 REAL C++ CALLEES** — `EXTERNAL` + `SELECT_ANY` workload callees, observed inline rate by index: `<=24 → .997 · 36 → .890 · 52 → .928 · 60 → .872 · 64 → .701 ‖ 68 → .157 · 72 → .000 · 92 → .036 · >=112 → .001`. LC:§6.17.4's external step and §6.17.5's 8-byte `inline` credit, on a population and at flags neither was fitted to. **It is a step and not a cliff** — index 64 reads .701 and index 68 reads .157, and those two cells hold most of the residual | rungs/2026-08-07-w-inline.md §2.3; `work/w-inline/PREREG.md` ADDENDUM 2 §3 |
| **902**<sub>w-inline</sub> | **`inline`-NESS IS OBJ-READABLE — it is the COMDAT SELECTION.** **VERIFIED on GRID-2b, 5,040 graded cells.** `SELECT_ANY` ⇔ `inline`: every `inline` free function, every in-class member and every template instantiation; `SELECT_NODUPLICATES` for every plain out-of-class definition. And the two classes' ladders differ by exactly the **8 bytes** LC:§6.17.5 measured — `member-inclass` and `member-outclass` are 672 of 672 with that one difference. Registered as `PREREG.md` P2 with the losing branch written down: had the selection not separated them, `INLINE-P`'s collapsed workload rule would have had an input nothing can compute | rungs/2026-08-07-w-inline.md §3.2; docs/INLINE_PREDICATE.md §2 table; `work/w-inline/scan_obj.py::sched_index` |
| **903**<sub>w-inline</sub> | **RECURSION — LC:§6.19.10's *"the one call-graph shape that has never appeared on either side of the pair"* — 336 of 336.** Measured at the workload's flags, k swept to 20 at both N = 1 and N = 4: a directly self-recursive callee is refused at **every** size, and `INLINE-P` calls it refused for a reason it already had — the callee's own `bl` to itself makes it **non-leaf**, which costs it the 48-byte credit and carries it past the step. **No new term.** Two other §6.19.10 gaps close in the same grid: a site with a **destructible object live across it** (`site-eh`, 336/336, identical to the straight-line control, so `/EHsc` moves the ordinary site by nothing) and a **two-level** tree whose inner callee is also same-TU (336/336) | rungs/2026-08-07-w-inline.md §3.2; `work/w-inline/grid.py` families `recurse`, `site-eh`, `two-level` |
| **905**<sub>w-inline</sub> | **A ONE-SIDED OBJ GRADE IS NOT A GRADE, AND `/Ob0` IS THE FIX.** An obj shows inline DECLINES (a surviving REL24) and cannot show INLINES, so a rule graded on it alone is improved by predicting `DECLINED` everywhere. Compiling each TU a second time with `/Ob0` appended enumerates the SITES with the real compiler. **The enumerator's own positive control passes and can go red** — `int g(int a){return a+1;}` has no internal REL24 at `/O1` and exactly one at `/Ob0`. Three confounds are handled in the file's doc rather than in prose: funclet `$N` counters do not survive a recompile (excluded from both sides); **inlining MIGRATES call sites** — 158 of `Utl.cpp`'s `/O1` edges do not exist at `/Ob0`, because an inlined callee's own calls came with it, so the grade aggregates **per callee** and never per pair; and every `INLINE-P` input is read from the `/O1` obj, never from the `/Ob0` one | rungs/2026-08-07-w-inline.md §2.1; `work/w-inline/ctl_ob0.py` (`POSITIVE CONTROL p4: PASS`), `grade_pair.py` |
"""


def main():
    s = open(P, encoding="utf-8").read()
    if "w-inline" in s:
        print("BOARD.md already carries w-inline rows — refusing to insert twice")
        return 1
    # Anchored on the HEADING, then walked back over the blank lines and the
    # `---` rule that precede it — the separators are not uniform across the
    # three sections and a fixed prefix string does not match all of them.
    for heading, rows in (("## Declined and refuted", OPEN_ROWS),
                          ("## Done", DECL_ROWS),
                          ("## Unclear", DONE_ROWS)):
        i = s.index("\n" + heading)
        while s[i - 1] in "\n-":
            i -= 1
        s = s[:i] + "\n" + rows.rstrip("\n") + s[i:]
    open(P, "w", encoding="utf-8").write(s)
    print("inserted 10 rows: #896-#905")
    return 0


if __name__ == "__main__":
    sys.exit(main())
