"""Insert lane w-fnbyte's board rows (#876-#885) into docs/BOARD.md.

Rows go into the two tables they belong in — Open for the ones a later lane has
to act on, Done for the ones this lane settled. The #322 row is amended in
place, because this lane closed it; its number is not reused.
"""

P = "docs/BOARD.md"
s = open(P, encoding="utf-8").read()

OPEN_ROWS = """| **876**<sub>w-fnbyte</sub> | **THE STANDING PER-FUNCTION ALARM WAS BLIND TO 9,375 FUNCTIONS AND HALF OF THEM ARE WRONG — `fnbyte-differs` 0 → 4,711** | **MEASURED on the 878-TU workload, both ends: `exact 29,802 → 34,466`, `partial 9,375 → 0`, `differs 0 → 4,711`, denominator 178,975 unchanged.** Of the 9,375 emitted functions FBM declined to grade, **4,664 are byte-exact and 4,711 are not**. Per shape: `tail` 4,051/7,098 exact, `seq` 609/2,150, **`framed` 0/123**, `cond-pair` 4/4. **4,529 of the 4,711 diverge at word 0** — a different body, not a near miss — across **601 of the 871 graded TUs**, in **61 signatures** | rungs/2026-08-06-w-fnbyte.md §1, §5; `work/w-fnbyte/final_metrics.txt` vs `baseline_metrics.txt` | **The alarm read 0 for its whole life because it was not looking**, which is board #232's shape with the instrument removed rather than merely unwatched (#871 predicted exactly this and understated it). **Nothing was narrowed to make it read 0 again and no emitter was patched** — a fix graded by the instrument that flagged it is circular. Every one of the 4,711 is printed by name and by word on every scan |
| **877**<sub>w-fnbyte</sub> | **THE CAUSE IS c2's INLINER, and the port's IL-level call recognizers do not model it** | **VERIFIED BY HAND against real `c2` at the workload's own `/O1 /Oi /EHsc /GR`, not inferred from the scan.** `void g(){} void f(){ g(); }` → c2 emits `?f@@YAXXZ` as **`4e800020` (`blr`), 4 bytes, 0 relocations**, and `c2rs census` at the same flags reads **`2/2 functions in class`, `?f` = `void-tail-call`**. The port would emit `b ?g@@YAXXZ` — a REL24 site and one more external symbol. That is signature **A** (1,886 functions) in four lines of source | rungs/2026-08-06-w-fnbyte.md §5.2; `work/w-fnbyte/probes/p2_void_call_inline.cpp`, `probe.sh` | Family taxonomy over all 4,711: **A** ref is a bare `blr` 1,886 · **B** c2 emitted fewer words 1,484 · **C** c2 emitted more words 1,157 · **D** shared prefix then diverge 184. **The predicate is a COST MODEL, not a syntactic fact** — "c2 will inline this" cannot be read off the IL the way a shape can — so the cheap repair (refuse a tail call whose callee is defined here and empty) is *named and not taken*, for the same reason #269 and #844 name theirs |
| **878**<sub>w-fnbyte</sub> | **IT IS THE CENSUS THAT IS WRONG TODAY, NOT AN OBJ — and it is a loaded gun for the next `functions()` widening** | **LATENT, measured: `mismatch` is 0 at both ends and stays 0.** `IlBundle::functions()` refuses every TU that carries one of the 4,711, so no wrong obj has ever been emitted. What is wrong is the **emitted census**: of 39,177 `emit-in-class` claims — the PROGRESS MASS's `f` numerator — **34,466 are confirmed byte-exact, 4,711 are confirmed wrong, 0 are unexamined** | rungs/2026-08-06-w-fnbyte.md §5.3 | **`FUNCTION_BYTE_MATCH.md` §6's sentence *"not one of the census's emitted in-class claims is wrong where it can be checked"* was true of 75.6 % of the population and is false of the rest**; corrected in place. Every one of the 4,711 is accepted by the **per-function** gate already, so a TU-level widening that admits any TU containing one ships a wrong obj — #232's transition in the bad direction, and until this row no standing instrument could have said so |
| **879**<sub>w-fnbyte</sub> | **`framed` IS 0 OF 123 — board #844's seam is not merely unwatched, its base shape does not match c2 on ONE workload function** | **MEASURED: `fnbyte-shape-framed-differs 123`, `framed-exact` absent.** 83 of them are one signature — `framed|w9/3/eq0|first@0:port=7d8802a6,ref=81630004`, the port's 9-word framed body against c2's 3-word leaf, e.g. `?back@?$vector@HV?$StlNodeAlloc@H@stlpmtx_std@@@stlpmtx_std@@QAAAAHXZ` | rungs/2026-08-06-w-fnbyte.md §5.4 | **Re-prices #871 and #875 in the direction that makes the decline more right, not less.** `w-seam` declined the seam because the alarm was blind there; the truth is stronger. No tension with #866 — that result is about the **run text** inside a framed body and this is about the **whole body**, and c2 does not compile these accessors as framed bodies at all. Whoever picks up #844 reads §5.4 before §3 of `w-seam` |
| **883**<sub>w-fnbyte</sub> | **FIVE `float` DIFFERS EXIST AT `/O1` ON THE FIXTURE CORPUS AND ZERO ON THE WORKLOAD** | **OBSERVED, not a finding of this lane's widening**: `float` with no pooled constant was **already** graded before board #322. `?fm4@@YAMMMMM@Z` and four siblings read `port=eda000f2` against `ref=ec0000f2` — an FP **destination-register** field (`f13` against `f0`) — with the first two words equal | rungs/2026-08-06-w-fnbyte.md §8 item 3; `work/w-fnbyte/fixture_gy_scan.txt` | Nobody had run FBM over the **fixtures** at `/O1`; the workload scan reads `float/exact 450 · float/differs 0`. So this is a `/O1` fixture-regime difference in the FP register model, unmeasured on any other axis and **not** priced here. The fixture `/Gy` scan is a new standing surface — it also carries `fnbyte-census-disagree 1`, likewise unbaselined |
| **884**<sub>w-fnbyte</sub> | **TRAP 6 IS LIVE: `fnbyte-exact-relocated` 0 → 4,664, i.e. EVERY newly-credited function relocates** | **MEASURED, and exactly equal to the newly-exact count** (`tail` 4,051 + `seq` 609 + `cond-pair` 4 = 4,664). `FUNCTION_BYTE_MATCH.md` trap 6 said *"the first accepted shape that relocates makes this bucket nonzero"* and predicted it would change without warning; it changed with the counter that was built for it printing the number | rungs/2026-08-06-w-fnbyte.md §8 item 4; `docs/FUNCTION_BYTE_MATCH.md` §7.6 | **`exact` is no longer a full function-identity claim for 4,664 of its 34,466.** A `.text` COMDAT's raw bytes do not contain its relocations, so two bodies calling two *different* functions are byte-identical here. Closing it means comparing relocation records against the census's callee names — a `c2-obj` rung, not this one. The gap was a constructed counterexample with instance count 0 for one day and has instance count 4,664 now |"""

DONE_ROWS = """| **880**<sub>w-fnbyte</sub> | **#322 IS CLOSED, AND THE DECLINE REASON WAS TRUE OF THE WRONG EMITTER** | **DONE.** §3.1 declined four shapes because *"the missing words encode their own `.text` offset"* — that is the **packed** emitter, and FBM's denominator is the **`/Gy` COMDAT** population, where every function starts at offset **0**. `PortC2::build`'s `/Gy` branch has composed these bodies completely since W-UNW-1; it did so **inline**, so only the whole-TU emitter could reach it. `c2_core::comdat::comdat_function_body` is that composition lifted verbatim — 22 insertions, 135 deletions, fixture gate `124 Match / 0 mismatch / 141 n-i of 265` across the lift | rungs/2026-08-06-w-fnbyte.md §3, §4; `crates/c2-core/src/comdat.rs` |
| **881**<sub>w-fnbyte</sub> | **THE RECONSTRUCTION CALLS THE EMITTER, NEVER A COPY — and that is the whole design constraint** | **DONE.** `fnbytes::complete_body` calls `comdat_body_from_selected`, which is what `PortC2::build` calls. A reconstruction written in the harness would be a second implementation free to drift, and **an alarm that is green about bytes the port does not emit is worse than the blind one it replaced**. `ComdatDecline` splits the three refusal stages (`Selector` / `Shape` / `DataRef`) because merging them mis-files the population: measured **selector 130,573 · gy-shape 0 · data-ref 0 · opt-mode 0** | rungs/2026-08-06-w-fnbyte.md §4; `crates/c2-core/src/comdat.rs`, `crates/c2-harness/src/gap/fnbytes.rs` |
| **882**<sub>w-fnbyte</sub> | **THE PER-SHAPE CENSUS AND THE NAMED WITNESSES — a bucket without its shapes is how a blind spot stays invisible** | **DONE.** Every scan now prints `graded by shape × verdict` (`fnbyte-shape-<shape>-<verdict>` keys) and, for each differing function, a **witness**: shape, port/ref/equal word counts, the first disagreeing word in hex **from both sides**, and the mangled symbol — collapsed to signatures with an example, so 1,950 STL names reporting one defect read as **61 rows** and not as 1,950. `partial by shape` prints `NONE` with its denominator rather than vanishing | rungs/2026-08-06-w-fnbyte.md §5.1; `GapReport::fn_byte_shape_census`, `fn_byte_differ_signatures` |
| **885**<sub>w-fnbyte</sub> | **31 MUTATIONS, 31 RED, 0 GREEN — every reconstructed WORD is load-bearing, per shape, against real c2 bytes** | **DONE.** `crates/c2-harness/tests/fnbyte_gy.rs` grades one specimen of each of the four shapes at the workload profile and flips **each word of the reference in turn**, requiring `Exact → Differs` every time: `tail 1/1 · framed 9/9 · seq 9/9 · cond-pair 9/9`, **28 words, all RED**. A shape graded zero times fails **by name**. Plus three code mutations (`work/w-fnbyte/mutate.sh`): restore the blind spot → RED, drop the composed branch word → RED, compare only the first half → RED | rungs/2026-08-06-w-fnbyte.md §6.1 |"""

anchor = "| **866**<sub>w-seam</sub> |"
assert s.count(anchor) == 1, "open-table anchor"
s = s.replace(anchor, OPEN_ROWS + "\n" + anchor, 1)

danchor = "| **873**<sub>w-seam</sub> |"
assert s.count(danchor) == 1, "done-table anchor"
s = s.replace(danchor, DONE_ROWS + "\n" + danchor, 1)

# #322 is closed by this lane. Amend it in place rather than mint a new number.
old322 = "| **322** | **A per-function entry point in `c2-core`**"
assert s.count(old322) == 1
s = s.replace(
    old322,
    "| **322** | **CLOSED 2026-08-06 by lane `w-fnbyte` — see #876/#880, and read #876 before quoting the projection below.** "
    "The row's own estimate (*\"FBM would go 0.16251 → **0.21488** with the port unchanged\"*) assumed the whole 9,374 were exact; "
    "**4,711 of them are wrong**, FBM went 0.16654 → **0.19259**, and `fnbyte-differs` went 0 → **4,711**. "
    "~~A per-function entry point in `c2-core`~~",
    1,
)

open(P, "w", encoding="utf-8").write(s)
print("rows inserted")
