#!/usr/bin/env python3
"""board_rows.py — insert lane w-splice's board rows (#986-#995) in numeric
position, at the end of BOARD.md's "Done" section.

Lane w-splice scratch. CLAUDE.md: a board item is added in the same commit that
mints the number, and this file is how that edit is reproducible rather than
only a diff.
"""

ROWS = r'''| **986**<sub>w-splice</sub> | **MECHANISM I's REPLACEMENT STRATUM IS SHIPPED — `SPLICE-0-PORT`, and it converts 723 emitted functions with ZERO moving the other way** | **DONE, judge-graded on the 878-TU workload.** `crates/c2-core/src/splice.rs`: when the port's whole emitted body for `F` is one call to a same-TU callee the port lowers, `F`'s `/Gy` COMDAT **is** that callee's — text, relocations, data references, no branch and no REL24 against the callee. `fnbyte-differs` **3,195 → 2,472**, `fnbyte-exact` **35,982 → 36,705**; the rule fired **723** times and **723 of 723** are byte-exact. Per `(TU, FnCensus::emit_name)` (**#918**): **723 converted, 0 regressed, 0 TUs graded at one end only** | rungs/2026-08-08-w-splice.md §1, §4; `work/w-splice/partition.txt` | **The predicate is nine clauses and not one of them reads the reference obj**, which is what separates it from **#968**'s enumeration of 726. `IlBundle::functions()` is untouched, so `mismatch` is still 0 and none of the 723 has ever reached an obj |
| **987**<sub>w-splice</sub> | **S3 MUST BE READ OFF THE IL FOR A `Seq`, NOT OFF THE EMITTED SETUP — 816 of 816, and the registered clause fired ZERO times** | **MEASURED, and it is `PREREG.md` P2 scored as the registered loss.** The clause registered before probing required the port's `setups[0]` to be empty, generalizing `tail`'s split (**#967**: 578/578 with no setup, 0/953 with one). On `seq` it converted **0**. The refusal census says why in one row: **816 of the 816** single-call `seq` differs are `S3-seq-setup-frame-only` and **none** is `S3-seq-setup-args` | rungs/2026-08-08-w-splice.md §5; key `fnbyte-splice-refused\|seq\|…` | **A `Seq` body is FRAMED, so its setup carries the `mr r31,r3` that saves `this` across the `bl` — the port's own lowering, not a transform of the callee's arguments.** c2's inlined body has no frame at all (`w-seq` §4.4). The clause now asks the IL: no chain link, no slot permutation, an operand stream that is empty or one passthrough `Load` of the first formal. **634 functions**, and the judge had already graded them — SPLICE-0 is exact on 816 of 816 (**#968**) |
| **988**<sub>w-splice</sub> | **THE INLINE DECISION IS TAKEN WHERE IT IS CATEGORICAL, NOT WHERE IT IS 97 % ACCURATE — `s ≤ 64` is unbounded in BOTH linkage classes** | **DONE as a shipped clause (S7), and it NEVER BINDS on today's port: 0 functions refused for size.** `INLINE_PREDICATE.md` §2's `index(G) = s − 4(nparams−1) − 8[inline] − 48[leaf] ≤ s`, and `N_max` is UNBOUNDED at `index ≤ 64` for EXTERNAL (§6.17.4) **and** for STATIC (`i = index/4 ≤ 16`, §6.18.9). So at `s ≤ 64` the decision is independent of linkage, of `inline`, of `nparams`, of the site count **and of the `leaf` bit §5 calls the model's one unreadable input**. Varargs (`N_max = 0`, §6.18.5) is the single categorical exception and is checked off the mangled name | rungs/2026-08-08-w-splice.md §3.2; `INLINE_UNBOUNDED_BYTES` | **An emitter may not consult a rule with a 2.84 % NOT-MODELLED residual — 3 % of a guess is a wrong emit.** It may consult the *region* in which that rule has no residual, which is a different object from the rule. `PREREG.md` P3 registered "S7 never binds" and it held: the port's lowered class is small leaves, so the bound is a safety argument that costs nothing today and will bind the moment the class grows |
| **989**<sub>w-splice</sub> | **c2 CLOSES THE SPLICE CHAIN — the fixpoint was registered as a QUESTION and both answers agree** | **MEASURED two independent ways.** `t11`, compiled: `int h(int a){return a+1;} int g(int a){return h(a);} int f(int a){return g(a);}` — c2 emits **`?h`'s two words for all three functions**. And the workload, through the relocation check the one-level rule forced into existence: **150 of 945** spliced functions relocated against the chain's *intermediate* where c2 relocates against its *end* | rungs/2026-08-08-w-splice.md §6; `work/w-splice/cells_graded.txt`, `relowitness.py` | **Mechanism E is a fixpoint (#920, #946) and mechanism I is one too, reached from the other direction.** E iterates a least fixpoint over "reduces to nothing"; I walks the chain to the first link that does not splice. Termination is structural in both — a step repeats a name (the refusal) or admits a new one — with a ceiling behind it so a broken edit refuses instead of walking forever |
| **990**<sub>w-splice</sub> | **THE RELOCATION CHECK FBM CANNOT DO, RUN PER SYMBOL ON EVERY FUNCTION THE MECHANISM MOVES: 723 of 723 agree, and #882 does not move** | **DONE, and it is the clause that decided the rung.** A `.text` COMDAT's raw data does not contain its relocations, so two bodies that are both `48000000` against different targets compare `exact` — **#882**, `fnbyte-exact-relocated` = 4,664. This mechanism *replaces a caller's relocations with its callee's*, so the one thing FBM cannot see is exactly what it changes. Verified per spliced symbol against the reference obj's own records, by target **name** and in-section **offset**: **723 no-relocs, 0 disagreements**, and `fnbyte-exact-relocated` reads **4,664 at both ends** | rungs/2026-08-08-w-splice.md §7; `work/w-splice/relocheck.txt`; key `fnbyte-spliced-reloc\|…` | **The check found 150 real disagreements and then 77 and then 1, and each one changed the rule** (**#989**, **#991**). A count of `exact` would have shipped all three intermediate versions green. `PREREG.md` §3 item 4 made a single disagreement a decline-floor failure **before** any of them existed |
| **991**<sub>w-splice</sub> | **A CHAIN THAT IS CUT OFF IS NOT A CHAIN THAT ENDED — two refusal clauses, 9 functions, and the 1 wrong relocation that bought them** | **MEASURED retreats, both costing conversions.** `S6-chain-truncated` (**6** functions): the chain's end still names a callee this TU's census carries — a parse refusal, a setup, a multi-call body — and c2 is under no such restriction. `S6-chain-open` (**3**): the end carries *any* call. One function got past the first clause — `??1CharPollableSorter@@QAA@XZ` spliced to a body branching to `??1?$_Rb_tree@PAVObject@Hmx@@…` where c2 relocates against `?clear@?$_Rb_tree@…` one link further — and that callee has **zero census rows in `Character.cpp`**, so it sits in the 9,225 `unbound` population and reads as an external | rungs/2026-08-08-w-splice.md §7.2 | **Refusing `S6-chain-open` costs 4 spliced functions of 727: 3 whose relocation the check verified CORRECT and 1 verified WRONG.** Keeping the three means keeping the one, because nothing the port can read separates them. **This is the whole of the shortfall against #968's 726** — the shipped number is 723 and the missing 3 are named rather than widened away. The rung that recovers them gives the port a defined-name set that does not come from the census |
| **992**<sub>w-splice</sub> | **EVERY ONE OF THE 2,472 RESIDUAL DIFFERS NOW NAMES THE CLAUSE THAT BLOCKS IT** | **MEASURED, published on every scan, on the `differs` path only.** `tail S3-tail-setup` **951** · `seq S2-multi-call` **725** · `tail S6-callee-parse-refused` **480** · `seq S6-callee-parse-refused` **182** · `framed S1-framed` **123** · `tail S6-chain-truncated` 6 · `tail S6-chain-open` 3 · `tail S8-caller-data-sym` 2. Sums to **2,472** | rungs/2026-08-08-w-splice.md §5.1; key `fnbyte-splice-refused\|<shape>\|<clause>` | **The refusal reason comes out of the emitter's own predicate, not a copy of it** — `splice_callee_why` returns the clause and the emitter takes `.ok()`. A separate "why did it refuse" routine is the drift `docs/GAPS.md` §6 records, and here it would price the wrong clause. **This is the work list**: `S3-tail-setup`'s 951 is #969's three fields, `S2-multi-call`'s 725 is SPLICE-N's 0 of 548, and the 662 parse refusals are #970's production table |
| **993**<sub>w-splice</sub> | **THE 723 ARE THREE TEMPLATE ROOTS AND 87 % OF THEM ARE ONE — said out loud, because #925 and #952 are the same caution twice** | **MEASURED and printed with its denominator**: 245 distinct symbols across 284 TUs and 22 source directories, but only **3** template roots — `??0?$_List_iterator` **629 (87.0 %)**, `?front@?$vector` **89 (12.3 %)**, `??0?$_Rb_tree_iterator` **5 (0.7 %)** | rungs/2026-08-08-w-splice.md §8; `work/w-splice/spread.txt` | **62 instantiations of one class template are one idiom and not 62.** #952's 143 conversions were all `??1?$_Rb_tree_base@…` and the rung said so; this one is two idioms — a `seq` constructor family and a `tail` accessor family — and the instrument prints the concentration line rather than leaving the reader to compute it. **The breadth is in the instantiations, not in the shapes** |
| **994**<sub>w-splice</sub> | **`ObjImage::text_comdat_relocs` — a relocation COUNT could not have caught any of this** | **DONE.** `crates/c2-obj/src/lib.rs`: per COMDAT, every relocation as `(offset, raw Type word, target symbol name)`, with the same fail-closed contract as every other walk. `PAIR` reports `None` because its `SymbolTableIndex` is a displacement and not an index; the `Type` word is handed back unmasked so a modifier bit cannot be rounded off | rungs/2026-08-08-w-splice.md §7 | **#882 has been a count since it was minted** (`fnbyte-exact-relocated` = 4,664 credited functions that relocate at all) and a count says nothing about *which symbol*. This is the reader that turns it into a question with an answer, and it is what a concurrent lane widening FBM to relocations needs too |
| **995**<sub>w-splice</sub> | **`PortC2::build` REFUSES A SPLICED BUNDLE ON BOTH PATHS, and the reason is the label counter** | **DONE, and unreachable today.** A spliced `Seq` loses its frame, and with it its `.pdata` record and its `$M`/`$M`/`$T` slots, while `frame_label_counter` is computed from the IL **before any body exists** and `plan_emit_order` orders on a call edge the emitted obj no longer has. None of that is measured, so an obj carrying one is refused with the reason named | rungs/2026-08-08-w-splice.md §9 | **`elide.rs` refuses only the PACKED path** — mechanism E's single `blr` never reached the label counter. This one does, so it refuses `/Gy` too. Asked through the same `splice_callee` the composition consults, so a future narrowing of `functions()`'s in-TU-callee refusal (which is a strict superset of S5) turns this into a loud refusal instead of a silent wrong obj — **#878**'s loaded gun, disarmed in the same commit that loads it |
'''

ANCHOR = "\n## Unclear — someone must read the bytes"

p = "docs/BOARD.md"
s = open(p).read()
assert ANCHOR in s, "the Done section's end marker moved"
assert "**986**" not in s, "already inserted"
open(p, "w").write(s.replace(ANCHOR, "\n" + ROWS + ANCHOR, 1))
print("inserted 10 rows")
