// GRID-N cell n8: 8 formals -> a 9-argument call.
// Generated by work/w-vsnprnc/gen_arity.py; arity is the ONLY axis.
typedef unsigned int size_t_;
extern "C" {
int *_errno(void);
typedef int (*outfn_t)(void);
extern int helper(outfn_t, char *, size_t_ , size_t_ , void *, void *, void *, void *, void *);
extern int outfn(void);
extern void _invalid_parameter_noinfo(void);

int f(char *p0, size_t_ p1, size_t_ p2, void *p3, void *p4, void *p5, void *p6, void *p7) {
    int result;
    if (p2 == 0 || p0 == 0 || p1 == 0) {
        *_errno() = 0x16;
        _invalid_parameter_noinfo();
        return -1;
    }
    result = helper(outfn, p0, p1, p2, p3, p4, p5, p6, p7);
    if (result < 0) {
        *p0 = 0;
    }
    if (result != -2) {
        return result;
    }
    *_errno() = 0x22;
    _invalid_parameter_noinfo();
    return -1;
}
}
