#!/usr/bin/env python3
"""w-counted — generate the /Ox ACCEPTED-SET CROSS for `counted_accum_loop`.

`fixtures/cpp/wbdnz_ctr.cpp` grades eleven cells: all seven accumulate opcodes
on a SIGNED counter, exactly ONE unsigned cell (`p_uns`, `-=`), one braced body
and the two `simm16` init edges. The class's free axes are opcode x counter
signedness, so **six of the fourteen opcode x signedness cells have never been
compiled at any mode**, and the question this lane was dispatched on is whether
the `/Ox` half of the accepted set is graded at all.

One function per TU, so a red cell names itself instead of reddening a
twenty-function verdict. `n_add_s` is the NEGATIVE control: `+=` is outside the
class (c2 strength-reduces the loop away entirely) and the reader must refuse
it, which is what shows the grid can tell in from out.

    python3 work/w-counted/gen_cells.py     # writes work/w-counted/cells/
"""
import os

R = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
D = os.path.join(R, "work/w-counted/cells")
os.makedirs(D, exist_ok=True)
ops = [("sub", "-="), ("mul", "*="), ("and", "&="), ("or", "|="),
       ("xor", "^="), ("shl", "<<="), ("sar", ">>=")]
hdr = ("// w-counted — the /Ox ACCEPTED-SET CROSS. Generated by work/w-counted/gen_cells.py.\n"
       "// One function per TU, every cell inside counted_accum_loop's closed recognizer.\n"
       "// The axes crossed: accumulate opcode (7) x counter signedness (2), plus the\n"
       "// simm16 init edges and the braced body on BOTH signednesses. wbdnz_ctr.cpp\n"
       "// grades the signed column and exactly ONE unsigned cell; this file is the rest.\n\n")
cells = []
for name, op in ops:
    for sgn, ty in (("s", "int"), ("u", "unsigned")):
        init = "1" if op in ("*=", "<<=", ">>=") else ("-1" if op == "&=" else "0")
        cells.append(("x_%s_%s" % (name, sgn),
                      "int c_%s_%s(%s n, int k) { int s = %s; for (%s i = 0; i < n; ++i) s %s k; return s; }\n"
                      % (name, sgn, ty, init, ty, op)))
cells.append(("x_hi_s", "int c_hi_s(int n, int k) { int s = 32767; for (int i = 0; i < n; ++i) s *= k; return s; }\n"))
cells.append(("x_hi_u", "int c_hi_u(unsigned n, int k) { int s = 32767; for (unsigned i = 0; i < n; ++i) s *= k; return s; }\n"))
cells.append(("x_lo_s", "int c_lo_s(int n, int k) { int s = -32768; for (int i = 0; i < n; ++i) s *= k; return s; }\n"))
cells.append(("x_lo_u", "int c_lo_u(unsigned n, int k) { int s = -32768; for (unsigned i = 0; i < n; ++i) s *= k; return s; }\n"))
cells.append(("x_braced_s", "int c_br_s(int n, int k) { int s = 0; for (int i = 0; i < n; ++i) { s -= k; } return s; }\n"))
cells.append(("x_braced_u", "int c_br_u(unsigned n, int k) { int s = 0; for (unsigned i = 0; i < n; ++i) { s ^= k; } return s; }\n"))
cells.append(("n_add_s", "int c_add_s(int n, int k) { int s = 0; for (int i = 0; i < n; ++i) s += k; return s; }\n"))
for n, b in cells:
    open(os.path.join(D, n + ".cpp"), "w").write(hdr + b)
with open(os.path.join(D, "list.txt"), "w") as f:
    for n, _ in cells:
        f.write("z:" + os.path.join(D, n + ".cpp").replace("/", "\\") + "\n")
print("%d cells -> %s" % (len(cells), D))
